In [1]:
from scripts import mapping
import pandas as pd

In [2]:
ranges_continuous = mapping.get_ranges2()

In [7]:
preds = pd.read_csv("data/processed/preds_ibd_cat_pr.csv")
preds

     SamplingOperations_code   IBD_pred  region
0         S02000010_20080811  14.174752      18
1         S02000010_20100719  15.456491      18
2         S02000010_20150811  13.785765      18
3         S02000010_20160825  14.733583      18
4         S02000010_20170703  16.039005      18
...                      ...        ...     ...
5658      S06700075_20120611  19.918207       2
5659      S06700094_20210830  18.284056       2
5660      S06700590_20210830  18.547747       2
5661      S06710014_20210823  19.789796       2
5662      S06820089_20120217  19.960351       2

[5663 rows x 3 columns]

In [8]:
send_results = mapping.get_results2(preds, ranges_continuous, pred_col="IBD_pred", output_file="holanuria.csv")
send_results

Assigned groups based on HERlvl1Name.
Saved predictions to holanuria.csv

     IBD_EQR_Status
0          Moderate
1              Good
2          Moderate
3              Good
4              Good
...             ...
5658           High
5659           Good
5660           Good
5661           High
5662           High

[5663 rows x 1 columns]