In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

path = "../../data/raw/"
dfs = {}

# read all dataframes and keep them in dfs
for parquet in os.listdir(path):  # List all files in the directory
    if parquet.endswith(".parquet"):
        name = parquet.split(".parquet")[0]  # Get name without extension
        dfs[name] = pd.read_parquet(os.path.join(path, parquet))  # Use os.path.join for paths
        print(f"Loaded {name} with shape {dfs[name].shape}")

Loaded 01_DiatomInventories_GTstudentproject_B with shape (1643872, 8)
Loaded 02_InfoSites_GTstudentproject_B with shape (8404, 11)
Loaded 03_IBD_GTstudentproject_test with shape (5063, 2)
Loaded 03_IBD_GTstudentproject_train with shape (43783, 4)
Loaded 04_PressureStatus_GTstudentproject_B with shape (49231, 30)
Loaded 05_EnvParamMeans_GTstudentproject_B with shape (3763903, 8)
Loaded 06_ListEnvParam_GNNprojectGT_B with shape (192, 14)
Loaded 07_TaxaCode_GTstudentproject_B with shape (2292, 2)

In [5]:
departamentos = dfs[list(dfs.keys())[2]]

In [7]:
departamentos

         CodeDepartement               Parametre_code
0     S04207000_20130812  To be defined by your model
1     S03257335_20200803  To be defined by your model
2     S03226300_20110916  To be defined by your model
3     S04104200_20190731  To be defined by your model
4     S06175600_20170904  To be defined by your model
...                  ...                          ...
5058  S05173420_20190926  To be defined by your model
5059  S04056000_20120808  To be defined by your model
5060  S03199200_20190710  To be defined by your model
5061  S05035200_20160914  To be defined by your model
5062  S02020300_20210526  To be defined by your model

[5063 rows x 2 columns]

In [12]:
pressure = dfs[list(dfs.keys())[4]]
pressure

,SamplingOperations_code,CodeSite_SamplingOperations,Date_SamplingOperation,Nitrogencompounds_Status1Y,Nitrogencompounds_Status180D,Nitrogencompounds_Status90D,Nitrates_Status1Y,Nitrates_Status180D,Nitrates_Status90D,Phosphorouscompounds_Status1Y,...,OrganicMatter_Status90D,SuspendedMatter_Status1Y,SuspendedMatter_Status180D,SuspendedMatter_Status90D,OrganicMicropollutants_Status1Y,OrganicMicropollutants_Status180D,OrganicMicropollutants_Status90D,MineralMicropollutants_Status1Y,MineralMicropollutants_Status180D,MineralMicropollutants_Status90D
0,S02000008_20170703,S02000008,2017-07-03,Good,Good,Good,Moderate,Moderate,Moderate,Good,...,Bad,High,High,High,Good,Good,Good,Good,Good,Good
1,S02000008_20200708,S02000008,2020-07-08,Good,Good,Good,Moderate,Moderate,Moderate,Moderate,...,Bad,High,High,High,Good,Good,Good,Good,Good,Good
2,S02000010_20070906,S02000010,2007-09-06,Good,Good,Good,Good,Good,Good,High,...,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good
3,S02000010_20080811,S02000010,2008-08-11,Good,Good,Good,Good,Good,Good,High,...,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate
4,S02000010_20090721,S02000010,2009-07-21,Good,Good,Good,Good,Good,Good,Good,...,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49226,S06710040_20090617,S06710040,2009-06-17,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,...,Unassessed,High,High,High,Good,Good,Good,Unassessed,Unassessed,Unassessed
49227,S06330110_20220913,S06330110,2022-09-13,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,...,Unassessed,Unassessed,Unassessed,Unassessed,Good,Good,Good,Unassessed,Unassessed,Unassessed
49228,S06330240_20220920,S06330240,2022-09-20,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,...,Unassessed,Unassessed,Unassessed,Unassessed,Good,Good,Good,Unassessed,Unassessed,Unassessed
49229,S06830110_20220831,S06830110,2022-08-31,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,...,Unassessed,Unassessed,Unassessed,Unassessed,Good,Good,Good,Unassessed,Unassessed,Unassessed
49230,S03013212_20190604,S03013212,2019-06-04,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,...,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Unassessed,Good,Good,Good

In [15]:
dep = pressure [['SamplingOperations_code', 'CodeSite_SamplingOperations']]
sites  = dfs[list(dfs.keys())[1]]  
dep = pd.merge(dep,sites , on = 'CodeSite_SamplingOperations', how = 'left' )

info de sites para todos

In [16]:
dep

,SamplingOperations_code,CodeSite_SamplingOperations,Longitude_Lambert93,Latitude_Lambert93,Watershed,CodeDepartement,HERlvl1Code,HERlvl1Name,HERlvl2Code,HERlvl2Name,Altitude,Streamsize
0,S02000008_20170703,S02000008,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,Collines du Sundgau,0.0,TP
1,S02000008_20200708,S02000008,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,Collines du Sundgau,0.0,TP
2,S02000010_20070906,S02000010,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,Alsace- plaine,246.0,None
3,S02000010_20080811,S02000010,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,Alsace- plaine,246.0,None
4,S02000010_20090721,S02000010,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,Alsace- plaine,246.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...
49226,S06710040_20090617,S06710040,946543.0,6229144.0,Rhône-Méditerranée,83,6,MEDITERRANEEN,108,Maures Esterel,24.0,TP
49227,S06330110_20220913,S06330110,935367.0,6486679.0,Rhône-Méditerranée,38,5,JURA-PREALPES DU NORD,79,Massifs Calcaires Chartreuse Aravis,256.0,P
49228,S06330240_20220920,S06330240,933597.0,6478724.0,Rhône-Méditerranée,38,5,JURA-PREALPES DU NORD,79,Massifs Calcaires Chartreuse Aravis,243.0,TP
49229,S06830110_20220831,S06830110,931109.0,6472568.0,Rhône-Méditerranée,38,5,JURA-PREALPES DU NORD,79,Massifs Calcaires Chartreuse Aravis,235.0,TP
49230,S03013212_20190604,S03013212,720824.0,6831336.0,Seine-Normandie,77,9,TABLES CALCAIRES,36,BP-Ile de France,98.0,TP

In [23]:
# Normaliza tipos/espacios
dep['SamplingOperations_code'] = dep['SamplingOperations_code'].astype(str).str.strip()
departamentos['CodeDepartement'] = departamentos['CodeDepartement'].astype(str).str.strip()

# Conjunto de códigos válidos
valid_codes = departamentos['CodeDepartement'].unique()

# Filtro (semi-join): dep solo con códigos presentes en departamentos
dep_filtrado = dep[dep['SamplingOperations_code'].isin(valid_codes)]

In [26]:
dep_test= dep_filtrado

In [27]:
dep_codes = dep

In [28]:
dep_codes.to_parquet("../../data/processed/dep_codes.parquet", index=False)

In [29]:
dep_test.to_parquet("../../data/processed/dep_test.parquet", index=False)