In [1]:
# Data manipulation and numerical computation
import numpy as np
import pandas as pd
import os

# Load data

In [2]:
path = "../../data/processed/"
dfs = {}

# read 03_CLEAN_COMPLETE_DF.parquet
df1 = pd.read_parquet(os.path.join(path, "taxones_pressure_epm_train.parquet"))
df2 = pd.read_parquet(os.path.join(path, "taxones_pressure_epm_predict.parquet"))
df = pd.concat([df1, df2], ignore_index=True)

In [3]:
# change unassessed values to NaN
df = df.replace("Unassessed", np.nan)
df = df.replace("None", np.nan)

# index SamplingOperations_code
df = df.set_index('SamplingOperations_code')
 
# DROP HERlvl2Code	Altitude Longitude_Lambert93	Latitude_Lambert93	Watershed	CodeDepartement	HERlvl1Code
df = df.drop(columns=['HERlvl2Code', 'HERlvl2Name', 'HERlvl1Name', 'Altitude','Longitude_Lambert93','Latitude_Lambert93','Watershed','CodeDepartement', 'Date_SamplingOperation'])
df

,CodeSite_SamplingOperations_x,TotalAbundance_SamplingOperation,Achaa01,Achac01,Achaf01,Achaf02,Achal01,Acham01,Achan01,Achat01,...,Mean90Days_5986,Mean90Days_6249,Mean90Days_6372,Mean90Days_6598,Mean90Days_6600,Mean90Days_7074,Mean90Days_XOMP,IBD,IBD_EQR,IBD_EQR_Status
SamplingOperations_code,,,,,,,,,,,,,,,,,,,,,
S02000008_20170703,S02000008,405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.6,0.502924,Poor
S02000008_20200708,S02000008,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0200,8.0,0.409357,Poor
S02000010_20070906,S02000010,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000650,NaN,NaN,0.00165,0.5735,14.3,0.777778,Moderate
S02000010_20090721,S02000010,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000650,NaN,NaN,0.00165,0.5735,15.0,0.818713,Good
S02000010_20110723,S02000010,398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000650,NaN,NaN,0.00165,0.5735,16.0,0.877193,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S06940940_20100708,S06940940,438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S06940940_20230623,S06940940,408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.001,NaN,0.000395,NaN,NaN,0.00026,0.1635,NaN,NaN,NaN
S06960950_20160629,S06960950,401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S06960950_20180719,S06960950,416,NaN,NaN,NaN,19.230769,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S06970900_20150601,S06970900,432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# For each region

In [4]:
import cleandf

In [5]:
# For all regions 1, 2, ..., 22
regiondfs = {}
for region in range(1, 23):
    print(f"Region: {region}")
    regiondf = df[df['HERlvl1Code'] == region]

    cleanregion = cleandf.IWANTMYXCLEAN(regiondf, thresh_high_missing=.90)
    regiondfs[region] = cleanregion

Region: 1
Dropped exact duplicate columns: ['Achac01', 'Achal01', 'Achca01', 'Achch01', 'Achcl01', 'Achco01', 'Achco03', 'Achcy01', 'Achde01', 'Achde02', 'Achdi01', 'Achdi02', 'Achel01', 'Achen01', 'Achex03', 'Achfl01', 'Achfr01', 'Achgr01', 'Achgr02', 'Achha01', 'Achhe01', 'Achhi01', 'Achho01', 'Achho02', 'Achim01', 'Achim02', 'Achim03', 'Achin01', 'Achin02', 'Achjo01', 'Achko01', 'Achkr01', 'Achkr03', 'Achkr04', 'Achku01', 'Achla01', 'Achla05', 'Achle01', 'Achle02', 'Achli02', 'Achli04', 'Achlo01', 'Achlu01', 'Achlu02', 'Achmo01', 'Achmo02', 'Achna01', 'Achna02', 'Achni01', 'Achno01', 'Achpa01', 'Achpe01', 'Achpe02', 'Achpl01', 'Achpo01', 'Achpr01', 'Achpr02', 'Achps01', 'Achps02', 'Achps03', 'Achpu01', 'Achro01', 'Achro03', 'Achru02', 'Achsc01', 'Achse01', 'Achse02', 'Achsi01', 'Achst01', 'Achst02', 'Achst04', 'Achsu02', 'Achsu04', 'Achtu01', 'Achzi01', 'Actde01', 'Actno01', 'Actro01', 'Actse01', 'Actsp01', 'Actsu01', 'Actvu01', 'Adlaq01', 'Adlbr01', 'Adlmu01', 'Adlmu02', 'Adlpa01', 'Afrre01', 'Ampae01', 'Ampaf01', 'Ampal01', 'Ampbi01', 'Ampbu01', 'Ampco01', 'Ampcu01', 'Ampde01', 'Ampdi01', 'Ampdi02', 'Ampdu01', 'Ampei01', 'Ampex01', 'Ampfo01', 'Ampfo02', 'Amphe01', 'Amphi01', 'Ampli01', 'Ampme01', 'Ampmi01', 'Ampmi02', 'Ampne01', 'Ampne02', 'Amppa01', 'Amppo01', 'Amppo02', 'Amppr01', 'Ampps01', 'Ampri01', 'Ampst01', 'Ampst02', 'Ampsu01', 'Ampsu02', 'Ampsu03', 'Ampsu04', 'Amptu01', 'Ampve02', 'Ampvi01', 'Anaba01', 'Anemi01', 'Anetu01', 'Anoeu01', 'Anoga01', 'Anoin01', 'Anosp01', 'Aulal01', 'Aulbr01', 'Aulcr01', 'Aulcr02', 'Auldi01', 'Aulis01', 'Aulit01', 'Aulli01', 'Aulpa01', 'Aulps01', 'Aulps02', 'Aulsu02', 'Aulva01', 'Azpno01', 'Bacul01', 'Braca01', 'Brali01', 'Brapr01', 'Braps01', 'Breke01', 'Calae02', 'Calal01', 'Calau01', 'Calbi01', 'Calfa01', 'Calfo02', 'Calhy01', 'Calla01', 'Calla02', 'Calla03', 'Calle01', 'Calmi01', 'Calpa01', 'Calpu01', 'Calsc01', 'Caltr01', 'Calve01', 'Calwe01', 'Camcy01', 'Camhi01', 'Capcr01', 'Catad01', 'Cavpa01', 'Cenre01', 'Cergr01', 'Chaal01', 'Chabe01', 'Chafa01', 'Chamu01', 'Chare01', 'Charh01', 'Chasc01', 'Chath01', 'Clico01', 'Cliin01', 'Cocbr01', 'Cocca01', 'Coccl01', 'Cocco01', 'Cocde01', 'Cocdi02', 'Cocgr01', 'Cochu02', 'Cocin01', 'Cocla01', 'Cocle01', 'Cocme01', 'Cocne01', 'Cocps01', 'Cocre01', 'Cocro01', 'Cocsc01', 'Cocse01', 'Cocsu01', 'Conwe01', 'Cosco01', 'Cosla01', 'Cosla02', 'Craac01', 'Craac02', 'Craha01', 'Crari01', 'Crasv01', 'Cravi01', 'Crazi01', 'Creru01', 'Creth01', 'Ctepu01', 'Cycbo01', 'Cyccy01', 'Cycde01', 'Cycde02', 'Cycgl01', 'Cycir01', 'Cyckr01', 'Cycku01', 'Cycop01', 'Cycpl01', 'Cycpl02', 'Cycsc01', 'Cycst02', 'Cycst03', 'Cycst04', 'Cycsu01', 'Cycth01', 'Cylgr01', 'Cymal01', 'Cymal02', 'Cyman01', 'Cyman02', 'Cyman03', 'Cyman04', 'Cymap01', 'Cymas01', 'Cymbe01', 'Cymbi01', 'Cymbr01', 'Cymbu01', 'Cymci01', 'Cymcu01', 'Cymcy01', 'Cymdi01', 'Cymdo01', 'Cymeh01', 'Cymel02', 'Cymex03', 'Cymfr01', 'Cymga01', 'Cymhe01', 'Cymhe02', 'Cymhu01', 'Cymin01', 'Cymin02', 'Cymin03', 'Cymka01', 'Cymko01', 'Cymku01', 'Cymla02', 'Cymla03', 'Cymlu01', 'Cymma01', 'Cymme02', 'Cymna02', 'Cymob01', 'Cymob02', 'Cympa01', 'Cympl01', 'Cympr01', 'Cympr02', 'Cympr03', 'Cympu01', 'Cymrh01', 'Cymru01', 'Cymsi02', 'Cymsp01', 'Cymst01', 'Cymsu01', 'Cymsu02', 'Cymsu03', 'Cymsu04', 'Cymsu06', 'Cymsu08', 'Cymsu09', 'Cymtr01', 'Cymtu04', 'Cymvu01', 'Delap01', 'Delco01', 'Delde01', 'Delkr01', 'Delve01', 'Dener01', 'Denfr01', 'Denpa01', 'Dense01', 'Densu01', 'Densu02', 'Diade01', 'Diapy01', 'Diate02', 'Diavi01', 'Dicda01', 'Dimna01', 'Dipab01', 'Dipae01', 'Dipbo01', 'Dipbo02', 'Dipbu01', 'Dipca01', 'Dipde01', 'Dipfo01', 'Dipfo02', 'Diphi01', 'Dipmi01', 'Dipmo01', 'Dippa01', 'Dipps01', 'Dippu01', 'Dipst01', 'Dipsu01', 'Dipti01', 'Disin01', 'Disst01', 'Encae01', 'Encaf01', 'Encal01', 'Encau01', 'Encbl01', 'Encbo01', 'Encel01', 'Encfa01', 'Encfo02', 'Encge01', 'Encgr01', 'Enche01', 'Encho01', 'Enchu01', 'Encin01', 'Enckr01', 'Enckr02', 'Encla01', 'Encla02', 'Enclu01', 'Encme01', 'Encmi01', 'Encmi02', 'Encmu01', 'Encne02', 'Encne03', 'Encno01', 'Encob01', 'Encpa01', 'Encpe01', 'Encpr02', 'Encre01', 'Encre02', 'Encro01', 'Encro02', 'Encsp01', 'Encsu01', 'Encsu02', 'Encsy01', 'Encth01', 'Encva01', 'Entor01', 'Entpa01', 'Eolar01', 'Eolbe01', 'Eolch01', 'Eolcr01', 'Eolin01', 'Epifr01', 'Epiin01', 'Epiop01', 'Epipa01', 'Epire01', 'Epiru01', 'Epism01', 'Epitu01', 'Ethpu01', 'Eucau01', 'Eucdi01', 'Eunam01', 'Eunar02', 'Eunar04', 'Eunau01', 'Eunbe01', 'Eunbi01', 'Eunbi02', 'Eunbi03', 'Eunbi04', 'Eunbo02', 'Eunch01', 'Eunci01', 'Eunci02', 'Eunci03', 'Euncu01', 'Eunde01', 'Eundi01', 'Eundi02', 'Eundo01', 'Eunel01', 'Eunen01', 'Eunfa01', 'Eunfl01', 'Eunfo02', 'Eunge01', 'Eunge02', 'Eungi01', 'Eungl01', 'Eungl02', 'Eungr01', 'Eunin02', 'Eunis01', 'Eunkr01', 'Eunla01', 'Eunla02', 'Eunme01', 'Eunme02', 'Eunme03', 'Eunmi01', 'Eunmi02', 'Eunmo01', 'Eunmu01', 'Eunmy01', 'Eunna01', 'Eunne01', 'Eunne02', 'Eunny01', 'Eunoc01', 'Eunor01', 'Eunpa01', 'Eunpa03', 'Eunpa04', 'Eunpa05', 'Eunpe01', 'Eunpe02', 'Eunpe03', 'Eunpr01', 'Eunps01', 'Eunps02', 'Eunrh01', 'Eunse01', 'Eunse02', 'Eunse03', 'Eunsi01', 'Eunso01', 'Eunst01', 'Eunsu01', 'Eunsu03', 'Eunsu04', 'Eunta01', 'Eunte02', 'Eunth01', 'Euntr01', 'Euntr02', 'Eunur01', 'Eunva01', 'Eunva02', 'Eunyb01', 'Exipu01', 'Falcl01', 'Falcr01', 'Falom01', 'Falpy01', 'Fraac01', 'Fraac02', 'Fraac03', 'Fraae01', 'Fraal01', 'Fraaq01', 'Fraat01', 'Frabi02', 'Frabi04', 'Frabi05', 'Frabo01', 'Fraca05', 'Fraco02', 'Fradi01', 'Frael01', 'Fraex01', 'Frafo01', 'Frafr01', 'Frage01', 'Frage02', 'Fragr02', 'Frahe01', 'Frain01', 'Frain02', 'Fraka01', 'Frala01', 'Frala03', 'Fralo01', 'Frame01', 'Frami01', 'Frami02', 'Frami04', 'Framu01', 'Frane01', 'Frane03', 'Frani01', 'Fraos01', 'Frapa02', 'Frape02', 'Frape03', 'Frapo01', 'Fraps01', 'Fraps02', 'Frapu01', 'Fraro01', 'Frasi01', 'Frasu01', 'Frasu02', 'Frate02', 'Frate03', 'Fratr01', 'Fraul01', 'Fraul02', 'Fraun01', 'Fruam01', 'Fruap01', 'Fruau01', 'Frucr01', 'Frucu01', 'Frudi01', 'Frukr01', 'Fruli01', 'Frune01', 'Frune02', 'Frupa01', 'Frupu01', 'Fruqu01', 'Frure01', 'Frurh01', 'Frusa01', 'Fruse01', 'Frusp01', 'Fruvi01', 'Fruwe01', 'Geige01', 'Geihi01', 'Geita01', 'Geren01', 'Glotr01', 'Gomae01', 'Gomam01', 'Goman01', 'Goman06', 'Gombo01', 'Gombo03', 'Gombr01', 'Gomca03', 'Gomca05', 'Gomcl03', 'Gomco01', 'Gomco02', 'Gomco03', 'Gomco05', 'Gomcu01', 'Gomcu03', 'Gomda01', 'Gomde01', 'Gomde02', 'Gomdi01', 'Gomdr01', 'Gomen01', 'Gomer01', 'Gomer02', 'Gomex02', 'Gomfo01', 'Gomfr01', 'Gomgr02', 'Gomgr03', 'Gomgr04', 'Gomha01', 'Gomhe01', 'Gomho01', 'Gomin01', 'Gomin02', 'Gomin04', 'Gomin05', 'Gomja01', 'Gomje01', 'Gomko01', 'Gomla02', 'Gomla03', 'Gomla06', 'Gomli01', 'Gomli02', 'Gomli03', 'Gomlo01', 'Gomlo02', 'Gomma01', 'Gomme01', 'Gomna01', 'Gomoa01', 'Gomob01', 'Gomob02', 'Gomoh01', 'Gomol01', 'Gomop01', 'Gompa02', 'Gompa03', 'Gompa04', 'Gompa05', 'Gompe01', 'Gompl01', 'Gompr01', 'Gompr02', 'Gomps01', 'Gomps02', 'Gomps03', 'Gompu01', 'Gompy01', 'Gomsa01', 'Gomsi01', 'Gomsp01', 'Gomsp02', 'Gomst01', 'Gomst02', 'Gomsu01', 'Gomsu02', 'Gomsu04', 'Gomsu05', 'Gomta01', 'Gomta02', 'Gomtr01', 'Gomtu01', 'Gomtu02', 'Gomun01', 'Gomva01', 'Gomva03', 'Gomva04', 'Gomva05', 'Gomve01', 'Gomvi01', 'Gomze01', 'Grama01', 'Grase01', 'Grusi01', 'Gyrli01', 'Gyrob01', 'Gyrsc01', 'Halac01', 'Halap01', 'Halbu01', 'Halcy01', 'Halho01', 'Halno01', 'Halol01', 'Halpe01', 'Halsu01', 'Halva01', 'Hanab01', 'Hanau01', 'Hanca01', 'Hanco01', 'Hanmo01', 'Hanps01', 'Hanre01', 'Hasdu01', 'Himfa01', 'Himso01', 'Hipar01', 'Hipca01', 'Hipco01', 'Hipco02', 'Hipge01', 'Hipne01', 'Hipol01', 'Hipps01', 'Hippu01', 'Hipru01', 'Hipsu01', 'Hombu01', 'Homca01', 'Homsu01', 'Humbr01', 'Humga01', 'Humsc01', 'Hydtr01', 'Hydwh01', 'Karam01', 'Karob01', 'Karpl01', 'Kobja01', 'Kobpa01', 'Kobps01', 'Kobsa01', 'Kobsu01', 'Kolsu01', 'Kurae01', 'Lacla01', 'Lemex01', 'Lemhu01', 'Lepmi01', 'Linau01', 'Linba01', 'Linbo01', 'Linco01', 'Linco02', 'Linfo01', 'Linpr01', 'Linte01', 'Lutac01', 'Lutco01', 'Lutfr01', 'Luthl01', 'Lutin01', 'Lutna01', 'Lutpe01', 'Lutpe02', 'Lutps01', 'Lutro01', 'Lutsa01', 'Lutsi01', 'Lutsp01', 'Lutve01', 'Masac01', 'Masba01', 'Masel01', 'Masex01', 'Masex02', 'Masin01', 'Masla01', 'Maspa01', 'Massm01', 'Masva01', 'Mayas01', 'Mayca01', 'Mayca02', 'Mayin01', 'Melcr01', 'Meldi01', 'Meldi02', 'Melgr01', 'Melit01', 'Melja01', 'Mello01', 'Melly01', 'Melmo01', 'Melmu01', 'Melny01', 'Melsc01', 'Melsp01', 'Melte02', 'Mesme01', 'Mickr01', 'Micpa01', 'Minch01', 'Muegi01', 'Muesp01', 'Nankr01', 'Nantr01', 'Navab01', 'Navab02', 'Navab03', 'Navac01', 'Navac03', 'Navad01', 'Navad02', 'Navag01', 'Navag02', 'Naval01', 'Naval02', 'Navam01', 'Navam02', 'Navam03', 'Navam04', 'Navam06', 'Navam07', 'Navan01', 'Navan03', 'Navan04', 'Navan06', 'Navap01', 'Navap02', 'Navaq02', 'Navar01', 'Navar03', 'Navat01', 'Navau01', 'Navba01', 'Navba02', 'Navbi01', 'Navbi02', 'Navbi03', 'Navbj01', 'Navbo01', 'Navbr01', 'Navbr03', 'Navbr04', 'Navbr05', 'Navbr06', 'Navbr07', 'Navbu01', 'Navbu02', 'Navca01', 'Navca02', 'Navca03', 'Navca04', 'Navca05', 'Navca06', 'Navca09', 'Navce01', 'Navch01', 'Navci02', 'Navcl01', 'Navcl02', 'Navcl03', 'Navcl04', 'Navco02', 'Navco03', 'Navco04', 'Navco06', 'Navcr01', 'Navcr02', 'Navcr03', 'Navcr06', 'Navcr08', 'Navcu01', 'Navcu02', 'Navde01', 'Navde02', 'Navde04', 'Navde05', 'Navde06', 'Navde07', 'Navdi01', 'Navdi02', 'Navdi05', 'Navdi07', 'Navdi08', 'Navdi09', 'Navdi10', 'Navdo01', 'Naveg01', 'Navei01', 'Navel01', 'Navel02', 'Navel03', 'Navev01', 'Navex03', 'Navfa01', 'Navfa02', 'Navfe01', 'Navfl01', 'Navfo01', 'Navfo02', 'Navfo03', 'Navfr01', 'Navga01', 'Navge01', 'Navge03', 'Navgi01', 'Navgl01', 'Navgo01', 'Navgr02', 'Navgr03', 'Navha01', 'Navha03', 'Navha04', 'Navha05', 'Navha06', 'Navha07', 'Navha08', 'Navhe01', 'Navhe03', 'Navho01', 'Navhu01', 'Navhu02', 'Navim01', 'Navin01', 'Navin02', 'Navin03', 'Navin04', 'Navin05', 'Navin07', 'Navin08', 'Navin09', 'Navin10', 'Navir01', 'Navir02', 'Navja02', 'Navja03', 'Navju01', 'Navko01', 'Navko02', 'Navkr01', 'Navku01', 'Navla02', 'Navla03', 'Navla05', 'Navla06', 'Navla07', 'Navle03', 'Navle04', 'Navle06', 'Navli01', 'Navli02', 'Navli03', 'Navlo01', 'Navlo02', 'Navlo03', 'Navlu01', 'Navlu03', 'Navma01', 'Navma02', 'Navma03', 'Navma04', 'Navma05', 'Navme01', 'Navme02', 'Navme03', 'Navme05', 'Navmi01', 'Navmi03', 'Navmi04', 'Navmi05', 'Navmi06', 'Navmi07', 'Navmi08', 'Navmo01', 'Navmo02', 'Navmo03', 'Navmo04', 'Navmo06', 'Navmo07', 'Navmo10', 'Navmu01', 'Navmu03', 'Navmu04', 'Navmu05', 'Navmu07', 'Navna01', 'Navne01', 'Navne02', 'Navni01', 'Navno01', 'Navnu01', 'Navny01', 'Navob01', 'Navob02', 'Navob03', 'Navob05', 'Navop01', 'Navop02', 'Navpa02', 'Navpa03', 'Navpa04', 'Navpa05', 'Navpa06', 'Navpa07', 'Navpe01', 'Navpe02', 'Navpe03', 'Navpe04', 'Navph01', 'Navph02', 'Navpl01', 'Navpr02', 'Navpr03', 'Navps03', 'Navps04', 'Navps05', 'Navps07', 'Navps09', 'Navps11', 'Navps12', 'Navpu01', 'Navpu02', 'Navpu03', 'Navpu04', 'Navpy01', 'Navqu01', 'Navra03', 'Navra04', 'Navre01', 'Navre02', 'Navre03', 'Navre05', 'Navre06', 'Navrh03', 'Navri01', 'Navri02', 'Navri03', 'Navri04', 'Navro01', 'Navro02', 'Navru01', 'Navsa01', 'Navsa02', 'Navsa04', 'Navsa05', 'Navsa07', 'Navsc01', 'Navsc02', 'Navsc03', 'Navsc05', 'Navsc06', 'Navsc07', 'Navsc08', 'Navse01', 'Navse03', 'Navse04', 'Navse06', 'Navse07', 'Navsi02', 'Navsi03', 'Navsl01', 'Navsm01', 'Navsp01', 'Navsp03', 'Navst01', 'Navst02', 'Navst03', 'Navst06', 'Navst07', 'Navsu01', 'Navsu02', 'Navsu04', 'Navsu06', 'Navsu10', 'Navsu11', 'Navsu12', 'Navsu13', 'Navsu14', 'Navsu16', 'Navsu17', 'Navsu18', 'Navsu19', 'Navsu20', 'Navsy02', 'Navta01', 'Navta02', 'Navte02', 'Navte03', 'Navth01', 'Navto01', 'Navtr01', 'Navtr03', 'Navtr04', 'Navtu01', 'Navtu02', 'Navul01', 'Navum01', 'Navum02', 'Navun01', 'Navva01', 'Navva02', 'Navva04', 'Navva05', 'Navva06', 'Navve01', 'Navve02', 'Navve05', 'Navve07', 'Navvi04', 'Navwe01', 'Navwi01', 'Navwi02', 'Navwi04', 'Navwy01', 'Navza01', 'Navze01', 'Neiaf01', 'Neiam01', 'Neiap01', 'Neibi01', 'Neibi02', 'Neibi03', 'Neibi04', 'Neica01', 'Neico01', 'Neicu01', 'Neide01', 'Neiel01', 'Neihe01', 'Neihu01', 'Neiin01', 'Neiir01', 'Neilo01', 'Neipe01', 'Neipr01', 'Neips01', 'Neise01', 'Neisu01', 'Neite01', 'Neive01', 'Neoco01', 'Nitac01', 'Nitac02', 'Nitac03', 'Nitac06', 'Nitae01', 'Nitae02', 'Nitag01', 'Nital01', 'Nital03', 'Nitam02', 'Nitam03', 'Nitam04', 'Nitan01', 'Nitau01', 'Nitau02', 'Nitba01', 'Nitba02', 'Nitba03', 'Nitba04', 'Nitbe02', 'Nitbi01', 'Nitbr01', 'Nitbr02', 'Nitbr03', 'Nitca01', 'Nitca02', 'Nitco01', 'Nitco03', 'Nitco04', 'Nitco06', 'Nitcu01', 'Nitcu02', 'Nitcu03', 'Nitde01', 'Nitde02', 'Nitde04', 'Nitde05', 'Nitde06', 'Nitdi01', 'Nitdi02', 'Nitdi03', 'Nitdi05', 'Nitdi06', 'Nitdu01', 'Nitep01', 'Nitet01', 'Niteu01', 'Nitfa01', 'Nitfi01', 'Nitfi02', 'Nitfl01', 'Nitfl02', 'Nitfo02', 'Nitfr01', 'Nitfu01', 'Nitge01', 'Nitgi01', 'Nitgo01', 'Nitgr01', 'Nitgr03', 'Nitha01', 'Nitho01', 'Nitho02', 'Nithu01', 'Nitin01', 'Nitin03', 'Nitin04', 'Nitin05', 'Nitju01', 'Nitla01', 'Nitla02', 'Nitla04', 'Nitla05', 'Nitla06', 'Nitla07', 'Nitle01', 'Nitle02', 'Nitli01', 'Nitli02', 'Nitli04', 'Nitma01', 'Nitmi02', 'Nitmi03', 'Nitmi04', 'Nitmo01', 'Nitmo02', 'Nitna01', 'Nitov01', 'Nitpa04', 'Nitpa05', 'Nitpa06', 'Nitpa07', 'Nitpa08', 'Nitpa09', 'Nitpe01', 'Nitpe02', 'Nitpe04', 'Nitpi01', 'Nitpl01', 'Nitps02', 'Nitpu01', 'Nitra01', 'Nitre02', 'Nitre03', 'Nitre04', 'Nitrh01', 'Nitro01', 'Nitro02', 'Nitro03', 'Nitsc01', 'Nitse01', 'Nitsi02', 'Nitsi03', 'Nitsp01', 'Nitst01', 'Nitsu02', 'Nitsu03', 'Nitsu04', 'Nitsu06', 'Nitsu07', 'Nitsu08', 'Nitsy01', 'Nitta01', 'Nitte01', 'Nitth01', 'Nitth02', 'Nittr02', 'Nittu01', 'Nitva01', 'Nitva02', 'Nitve01', 'Nitve02', 'Nitvi01', 'Nitvi02', 'Nitwu01', 'Nitzu01', 'Nupca01', 'Nupde01', 'Nupel01', 'Nupex01', 'Nupfe01', 'Nupim01', 'Nupim02', 'Nupma01', 'Nupne01', 'Nuppa01', 'Nuppa02', 'Nuppr01', 'Nuppr02', 'Nupru01', 'Nupsc01', 'Nupsi01', 'Nupsu01', 'Nuptr01', 'Nupvy01', 'Nupwe01', 'Odoau01', 'Odosp01', 'Opebu01', 'Opema01', 'Opemi01', 'Opepa01', 'Ortro01', 'Panps01', 'Panro01', 'Parde01', 'Parhe01', 'Parmi01', 'Parrh01', 'Parsu01', 'Perfi01', 'Perpe01', 'Pinac01', 'Pinac02', 'Pinac03', 'Pinac04', 'Pinam01', 'Pinan01', 'Pinan02', 'Pinan03', 'Pinap01', 'Pinbi01', 'Pinbr01', 'Pinbr02', 'Pinca01', 'Pincl01', 'Pinde01', 'Pindi01', 'Pindi02', 'Pindo01', 'Pindu01', 'Pinel01', 'Pinel02', 'Pinex01', 'Pinfa01', 'Pinfe01', 'Pinfr01', 'Pinfr02', 'Pingi01', 'Pingl01', 'Pingr01', 'Pingr02', 'Pinin02', 'Pinin03', 'Pinis01', 'Pinkn01', 'Pinkr01', 'Pinkr02', 'Pinku01', 'Pinla02', 'Pinle01', 'Pinlu01', 'Pinma01', 'Pinma02', 'Pinma03', 'Pinma05', 'Pinme01', 'Pinme02', 'Pinmi01', 'Pinmo01', 'Pinmo02', 'Pinmo03', 'Pinmu01', 'Pinna01', 'Pinne01', 'Pinno01', 'Pinno02', 'Pinpa01', 'Pinpa02', 'Pinpe01', 'Pinpe02', 'Pinpe04', 'Pinpe05', 'Pinpl01', 'Pinpo01', 'Pinpo02', 'Pinps01', 'Pinra01', 'Pinre01', 'Pinrh01', 'Pinrh02', 'Pinrh03', 'Pinru01', 'Pinru02', 'Pinsa01', 'Pinsa02', 'Pinsa03', 'Pinsc01', 'Pinsc02', 'Pinsc03', 'Pinsc04', 'Pinsi01', 'Pinsi02', 'Pinsi03', 'Pinsi04', 'Pinst01', 'Pinst02', 'Pinsu01', 'Pinsu02', 'Pinsu03', 'Pinsu04', 'Pinsu05', 'Pinsu06', 'Pinsu07', 'Pinsu08', 'Pinsu09', 'Pinsu10', 'Pinsu11', 'Pinte01', 'Pinth01', 'Pintr01', 'Pinvi01', 'Pinvi02', 'Plaab01', 'Plaam01', 'Plaat01', 'Plaau01', 'Plaba02', 'Plabi01', 'Plabr01', 'Placa01', 'Placl01', 'Placl02', 'Pladi01', 'Plaga01', 'Plaga02', 'Plaga03', 'Plaha01', 'Plaha02', 'Plahi01', 'Plain01', 'Plaki01', 'Plala01', 'Plalu01', 'Plama01', 'Plame01', 'Plami01', 'Plana01', 'Plaob01', 'Plapa02', 'Plape01', 'Plape02', 'Plapo01', 'Plaps01', 'Plapu01', 'Plaro01', 'Plaro02', 'Plaro05', 'Plasi01', 'Plast01', 'Plata01', 'Plats01', 'Plava01', 'Plava02', 'Plavi01', 'Plean01', 'Plebr01', 'Plede01', 'Pleku01', 'Plela01', 'Pleob01', 'Plepr01', 'Plesa01', 'Plesp01', 'Plewo01', 'Pretu01', 'Prohu01', 'Psaab01', 'Psaal01', 'Psabr01', 'Psabu01', 'Psaco01', 'Psafr01', 'Psapu01', 'Psasa01', 'Pse(a01', 'Psebi01', 'Psebo01', 'Pseca01', 'Pseco01', 'Psege01', 'Pseoc01', 'Pseop01', 'Psepa02', 'Psepo01', 'Psero01', 'Psesm01', 'Psevu01', 'Punbo01', 'Pungl01', 'Pyxco01', 'Rhaam01', 'Rhami01', 'Rhasu01', 'Rhipr01', 'Rhobr01', 'Rhogi01', 'Rhogi02', 'Rhote01', 'Rhova01', 'Scema01', 'Scemu01', 'Schbr01', 'Schcr01', 'Schex01', 'Schla01', 'Selab01', 'Selar01', 'Selar02', 'Selau01', 'Selba01', 'Selbl01', 'Selbo01', 'Selca01', 'Selch01', 'Selco01', 'Selda01', 'Seldi01', 'Selel01', 'Sella01', 'Sella02', 'Selpa01', 'Selps01', 'Selps02', 'Selps03', 'Selra01', 'Selre01', 'Selrh02', 'Selro01', 'Selru01', 'Selsc01', 'Selsu01', 'Selsu02', 'Selut01', 'Selve01', 'Semin01', 'Semro01', 'Skaoe01', 'Skape01', 'Skepe01', 'Skesu01', 'Spisp01', 'Staac01', 'Staac02', 'Staac03', 'Staac04', 'Staag01', 'Staal01', 'Staam01', 'Staam02', 'Staam03', 'Stabo01', 'Stabo02', 'Stabo03', 'Stabr01', 'Stach01', 'Staco01', 'Stacr01', 'Stadi01', 'Stadu01', 'Stadu02', 'Staex01', 'Stagr01', 'Stagr02', 'Stahe01', 'Stain01', 'Stain02', 'Stain03', 'Stakr02', 'Stala01', 'Stala02', 'Stala03', 'Stale01', 'Stale04', 'Stalo01', 'Stama01', 'Stami01', 'Stamu01', 'Stana01', 'Stane01', 'Staob01', 'Staol01', 'Staol02', 'Staph01', 'Stapl01', 'Stapo01', 'Stapr01', 'Stapu01', 'Stare01', 'Stare02', 'Staro01', 'Stasa01', 'Stase01', 'Stasi01', 'Stasm01', 'Stasp01', 'Stast01', 'Stasu01', 'Stasv01', 'State01', 'Staun01', 'Stave01', 'Stawi01', 'Steal01', 'Stebr01', 'Steco01', 'Stede01', 'Stedu01', 'Steme01', 'Stemi01', 'Stena01', 'Stene01', 'Stero01', 'Steve01', 'Surac01', 'Sural01', 'Suram01', 'Surbi01', 'Surbi02', 'Surbi03', 'Surbo01', 'Surbr02', 'Surca01', 'Surch01', 'Surcr01', 'Surde01', 'Surel01', 'Surhe01', 'Surhi01', 'Surli01', 'Surma01', 'Surna01', 'Surol01', 'Surov01', 'Surpa01', 'Surre01', 'Surro02', 'Surst01', 'Surst02', 'Sursu01', 'Sursu02', 'Surte01', 'Surun01', 'Surve01', 'Survi01', 'Synac01', 'Synaf01', 'Synam01', 'Synam02', 'Synba01', 'Synbe01', 'Synca01', 'Syncr01', 'Synda01', 'Synde02', 'Synfa01', 'Synfa02', 'Synfl01', 'Synla01', 'Synma01', 'Synmo01', 'Synmo02', 'Synna01', 'Synpa01', 'Synpl01', 'Synva01', 'Tabfe01', 'Tabin01', 'Tabta01', 'Tetgl01', 'Tetla01', 'Thaba01', 'Thabr01', 'Thadu01', 'Thage01', 'Thani01', 'Thaps01', 'Thavi01', 'Traac01', 'Traas01', 'Traau01', 'Trire01', 'Trybr01', 'Tryca01', 'Tryco01', 'Tryde01', 'Trygr01', 'Tryku01', 'Tryle01', 'Trysu01', 'Tryvi01', 'Tscmi01', 'Ulngr01', 'Witan01', 'Withu01', 'Witps01', 'Witsu01', 'Witsy01', 'Zygsu01', 'Mean180Days_1166', 'Mean180Days_1592', 'Mean180Days_1593', 'Mean180Days_1644', 'Mean180Days_1647', 'Mean180Days_1648', 'Mean180Days_1770', 'Mean180Days_2923', 'Mean180Days_6249', 'Mean180Days_6600', 'Mean1Y_1166', 'Mean1Y_1644', 'Mean1Y_1647', 'Mean1Y_1648', 'Mean1Y_1770', 'Mean1Y_2923', 'Mean1Y_6249', 'Mean1Y_6600', 'Mean90Days_1166', 'Mean90Days_1173', 'Mean90Days_1207', 'Mean90Days_1592', 'Mean90Days_1593', 'Mean90Days_1644', 'Mean90Days_1647', 'Mean90Days_1648', 'Mean90Days_1723', 'Mean90Days_1770', 'Mean90Days_1777', 'Mean90Days_1811', 'Mean90Days_2539', 'Mean90Days_2923', 'Mean90Days_3336', 'Mean90Days_5275', 'Mean90Days_5986', 'Mean90Days_6249', 'Mean90Days_6598', 'Mean90Days_6600']

In [6]:
regiondfs[1]

,TotalAbundance_SamplingOperation,Achat02,Achde03,Achla02,Achli03,Achmi02,Achpy01,Achri01,Achsu01,Achth01,...,Mean90Days_1841,Mean90Days_1955,Mean90Days_1958,Mean90Days_1959,Mean90Days_2879,IBD,IBD_EQR,IBD_EQR_Status,Uncommon_Taxons,QuasiConstant_Numeric
SamplingOperations_code,,,,,,,,,,,,,,,,,,,,,
S05168100_20070809,400,45.000000,NaN,NaN,NaN,80.000000,682.500000,NaN,50.000000,NaN,...,0.850000,NaN,NaN,NaN,NaN,20.0,1.0,High,5.000000,1.000000
S05168100_20080806,400,60.000000,NaN,NaN,NaN,25.000000,765.000000,15.0,NaN,NaN,...,1.250000,NaN,NaN,NaN,NaN,20.0,1.0,High,12.500000,1.156650
S05168100_20090625,400,NaN,NaN,NaN,NaN,100.000000,637.500000,NaN,5.000000,NaN,...,1.000000,0.1,0.065,0.02,0.000065,20.0,1.0,High,22.504200,1.400400
S05168100_20100629,414,24.154589,NaN,NaN,NaN,36.231884,826.086957,NaN,38.647343,NaN,...,NaN,NaN,NaN,NaN,NaN,20.0,1.0,High,1.461467,1.145617
S05168100_20110809,400,2.500000,NaN,NaN,NaN,90.000000,692.500000,22.5,22.500000,NaN,...,1.650000,NaN,NaN,NaN,NaN,20.0,1.0,High,15.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S06175540_20150728,407,34.398034,NaN,NaN,NaN,27.027027,508.599509,NaN,31.941032,NaN,...,1.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.571234,1.284505
S06175600_20170904,400,NaN,NaN,NaN,10.00000,5.000000,422.500000,NaN,NaN,NaN,...,1.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,213.703200,1.283169
S06175600_20180926,411,301.703163,NaN,NaN,26.76399,48.661800,209.245742,NaN,51.094891,NaN,...,1.666667,0.1,0.065,0.02,0.000135,NaN,NaN,NaN,81.454907,1.591889
S06175645_20220809,418,47.846890,502.392344,NaN,NaN,33.492823,287.081340,NaN,NaN,NaN,...,0.695000,0.1,0.065,0.02,0.000065,NaN,NaN,NaN,53.698332,1.316626
S06175840_20090624,416,NaN,NaN,NaN,NaN,266.826923,57.692308,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.997842,2.116900

# CatBoostClassifier

In [ ]:
from ilboosted import MultiRegionBoostedClassifier

In [ ]:
auto = MultiRegionBoostedClassifier(regiondfs, random_state=67, verbose=True, models=["CatBoost"])
auto.process_missing_class(scoring="accuracy", n_iter_per_model=5, max_splits=5, calibrate=True)

In [ ]:
manifest = auto.save_all(outdir="models", compress=3, make_figs=True)
manifest

In [ ]:
reports = auto.save_all_reports(outdir="models")
reports

In [20]:
all_preds = auto.all_inferred()
all_preds.to_csv("all_regions_inferred.csv", index=False)

In [ ]:
for i in range(1, 23):
    print(f"\n Region {i} report:")
    auto.print_report(i)
    print("\n")

In [ ]:
auto.results

In [ ]:
for i in range(1, 23):
    print(f"Region {i}:")
    print(auto.results[i]["best_name"], auto.results[i]["oof_bal_acc"])

# Get predictions

In [ ]:
all_cls = all_preds.set_index('SamplingOperations_code')
yhat_te = all_cls['yhat_te'][all_cls['yhat_te'].notna()]
yhat_te = yhat_te.to_frame()
yhat_te.to_csv('Status.csv')
yhat_te

                          yhat_te
SamplingOperations_code
S05169000_20130911           High
S05169000_20200819           High
S05172000_20210813           Good
S05172050_20210824           Good
S05172350_20120827           High
...                           ...
S03128500_20120723       Moderate
S03128640_20130718       Moderate
S03128640_20181011       Moderate
S03128732_20210817           Good
S03129170_20150630           High

[5663 rows x 1 columns]