In [1]:
from scripts import mapping
import pandas as pd

In [2]:
ranges_continuous = mapping.get_ranges2()

In [7]:
preds = pd.read_parquet("results/013_Catboost_FullIBD_Training_pred.parquet")
preds = preds[['SamplingOperations_code','IBD_pred']]
preds.to_csv("results/013_Catboost_Full_IBD_Training/013_IBD.csv", index=False)
preds

      SamplingOperations_code   IBD_pred
43568      S02000010_20080811  13.765716
43569      S02000010_20100719  15.386578
43570      S02000010_20150811  13.417963
43571      S02000010_20160825  14.207038
43572      S02000010_20170703  15.749292
...                       ...        ...
49226      S06940940_20100708  16.094491
49227      S06940940_20230623  15.392658
49228      S06960950_20160629  19.942872
49229      S06960950_20180719  20.084038
49230      S06970900_20150601  19.991076

[5663 rows x 2 columns]

In [6]:
send_results = mapping.get_results2(preds, ranges_continuous, pred_col="IBD_pred", output_file="results/013_Catboost_Full_IBD_Training/013_Status.csv")
send_results.head()

Assigned groups based on HERlvl1Name.
Saved predictions to results/013_Catboost_Full_IBD_Training/013_Status.csv

                        IBD_EQR_Status
SamplingOperations_code
S02000010_20080811            Moderate
S02000010_20100719                Good
S02000010_20150811            Moderate
S02000010_20160825            Moderate
S02000010_20170703                Good