In [1]:
from scripts import mapping
import pandas as pd

In [2]:
ranges_continuous = mapping.get_ranges2()

In [3]:
preds = pd.read_csv("results/011_Catboost_Regression_Full_t/011_IBD.csv")
preds.head()

  SamplingOperations_code   IBD_pred
0      S02000010_20080811  13.923305
1      S02000010_20100719  15.618174
2      S02000010_20150811  13.511121
3      S02000010_20160825  14.599235
4      S02000010_20170703  16.000024

In [4]:
send_results = mapping.get_results2(preds, ranges_continuous, pred_col="IBD_pred", output_file="results\\011_Catboost_Regression_Full_t\\011_Status.csv")
send_results.head()

Assigned groups based on HERlvl1Name.
Saved predictions to results\011_Catboost_Regression_Full_t\011_Status.csv

                        IBD_EQR_Status
SamplingOperations_code
S02000010_20080811            Moderate
S02000010_20100719                Good
S02000010_20150811            Moderate
S02000010_20160825                Good
S02000010_20170703                Good