In [1]:
from scripts import mapping
import pandas as pd

import importlib
importlib.reload(mapping)

In [2]:
ranges_continuous = mapping.get_ranges2()

In [3]:
preds = pd.read_csv("results/011_Catboost_Regression_Full_t/011_IBD.csv")
preds

     SamplingOperations_code   IBD_pred
0         S02000010_20080811  13.923305
1         S02000010_20100719  15.618174
2         S02000010_20150811  13.511121
3         S02000010_20160825  14.599235
4         S02000010_20170703  16.000024
...                      ...        ...
5658      S06940940_20100708  16.145701
5659      S06940940_20230623  15.413047
5660      S06960950_20160629  19.904753
5661      S06960950_20180719  19.983617
5662      S06970900_20150601  19.973405

[5663 rows x 2 columns]

In [4]:
send_results = mapping.get_results2(preds, ranges_continuous, pred_col="IBD_pred", output_file="results\\011_Catboost_Regression_Full_t\\011_Status.csv")
send_results

Assigned groups based on HERlvl1Name.
Saved predictions to results\011_Catboost_Regression_Full_t\011_Status.csv

                        IBD_EQR_Status
SamplingOperations_code
S02000010_20080811            Moderate
S02000010_20100719                Good
S02000010_20150811            Moderate
S02000010_20160825                Good
S02000010_20170703                Good
...                                ...
S06940940_20100708            Moderate
S06940940_20230623            Moderate
S06960950_20160629                High
S06960950_20180719                High
S06970900_20150601                High

[5663 rows x 1 columns]