# 07_TaxaCode_GTstudentproject_B

In [1]:
import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import cohen_kappa_score
import plotly.express as px
import plotly.graph_objects as go

In [2]:
sns.set(style="ticks", context="notebook", palette="deep")
pd.set_option('display.max_columns', None)

In [5]:
path = "data/raw/"
dfs = {}

# read all dataframes and keep them in dfs
for parquet in os.listdir(path):  # List all files in the directory
    if parquet.endswith(".parquet"):
        name = parquet.split(".parquet")[0]  # Get name without extension
        dfs[name] = pd.read_parquet(os.path.join(path, parquet))  # Use os.path.join for paths
        print(f"Loaded {name} with shape {dfs[name].shape}")

Loaded 01_DiatomInventories_GTstudentproject_B with shape (1643872, 8)
Loaded 02_InfoSites_GTstudentproject_B with shape (8404, 11)
Loaded 03_IBD_GTstudentproject_test with shape (5063, 2)
Loaded 03_IBD_GTstudentproject_train with shape (43783, 4)
Loaded 04_PressureStatus_GTstudentproject_B with shape (49231, 30)
Loaded 05_EnvParamMeans_GTstudentproject_B with shape (3763903, 8)
Loaded 06_ListEnvParam_GNNprojectGT_B with shape (192, 14)
Loaded 07_TaxaCode_GTstudentproject_B with shape (2292, 2)

In [6]:
dfs[list(dfs.keys())[7]]

                 CodeDepartement Parametre_code
0      Achnanthes aapajaervensis        Achaa01
1             Achnanthes affinis        Achaf01
2        Achnanthes amphicephala        Acham01
3              Achnanthes atomus        Achat01
4       Achnanthes biasolettiana        Achbi01
...                          ...            ...
2287        Witkowskia hustedtii        Withu01
2288  Witkowskia pseudoclementis        Witps01
2289     Witkowskia subclementis        Witsu01
2290       Witkowskia symmetrica        Witsy01
2291         Zygoceros surirella        Zygsu01

[2292 rows x 2 columns]

In [8]:
dfs[list(dfs.keys())[7]].head(20)

              CodeDepartement Parametre_code
0   Achnanthes aapajaervensis        Achaa01
1          Achnanthes affinis        Achaf01
2     Achnanthes amphicephala        Acham01
3           Achnanthes atomus        Achat01
4    Achnanthes biasolettiana        Achbi01
5         Achnanthes bioretii        Achbi02
6         Achnanthes brevipes        Achbr01
7        Achnanthes carissima        Achca01
8         Achnanthes catenata        Achca02
9        Achnanthes chlidanos        Achch01
10          Achnanthes clevei        Achcl01
11       Achnanthes coarctata        Achco01
12       Achnanthes conspicua        Achco02
13      Achnanthes convergens        Achco03
14          Achnanthes crassa        Achcr01
15      Achnanthes cyclophora        Achcy01
16       Achnanthes daonensis        Achda01
17            Achnanthes daui        Achda02
18         Achnanthes deflexa        Achde01
19          Achnanthes didyma        Achdi01

In [ ]:
dfs[list(dfs.keys())[7]].nunique()

CodeDepartement    2292
Parametre_code     2292
dtype: int64