In [21]:
# Data manipulation and numerical computation
import numpy as np
import pandas as pd
import os


# view all the columns in a dataframe
pd.pandas.set_option('display.max_columns', None)
# view all the rows in a dataframe
pd.pandas.set_option('display.max_rows', None)

# Load data

In [22]:
path = "../../data/processed/"
dfs = {}

# read 03_CLEAN_COMPLETE_DF.parquet
df1 = pd.read_parquet(os.path.join(path, "taxones_pressure_train.parquet"))
df2 = pd.read_parquet(os.path.join(path, "taxones_pressure_predict.parquet"))
df = pd.concat([df1, df2], ignore_index=True)

In [3]:
df.head(3)

,SamplingOperations_code,CodeSite_SamplingOperations,Date_SamplingOperation,TotalAbundance_SamplingOperation,Achaa01,Achac01,Achaf01,Achaf02,Achal01,Acham01,Achan01,Achat01,Achat02,Achat03,Achba01,Achbi01,Achbi02,Achbr01,Achca01,Achca02,Achca03,Achca04,Achch01,Achcl01,Achco01,Achco02,Achco03,Achco04,Achcr01,Achcy01,Achda01,Achda02,Achde01,Achde02,Achde03,Achdi01,Achdi02,Achdr01,Achel01,Achen01,Acheu01,Achex01,Achex02,Achex03,Achfl01,Achfr01,Achfu01,Achge01,Achgr01,Achgr02,Achgr03,Achha01,Achhe01,Achhi01,Achho01,Achho02,Achho03,Achhu01,Achim01,Achim02,Achim03,Achin01,Achin02,Achja01,Achja02,Achjo01,Achko01,Achkr01,Achkr02,Achkr03,Achkr04,Achku01,Achla01,Achla02,Achla03,Achla04,Achla05,Achla06,Achle01,Achle02,Achli01,Achli02,Achli03,Achli04,Achlo01,Achlu01,Achlu02,Achma01,Achmi01,Achmi02,Achmi03,Achmo01,Achmo02,Achna01,Achna02,Achne01,Achni01,Achno01,Achob01,Achpa01,Achpe01,Achpe02,Achpf01,Achpl01,Achpo01,Achpr01,Achpr02,Achps01,Achps02,Achps03,Achps04,Achpu01,Achpy01,Achre01,Achri01,Achro01,Achro02,Achro03,Achro04,Achru01,Achru02,Achsa01,Achsc01,Achse01,Achse02,Achsi01,Achst01,Achst02,Achst03,Achst04,Achsu01,Achsu02,Achsu03,Achsu04,Achsu05,Achsu06,Achsu07,Achte01,Achth01,Achtr01,Achtr02,Achtr03,Achtu01,Achzh01,Achzi01,Actde01,Actno01,Actro01,Actse01,Actsp01,Actsu01,Actvu01,Adlaq01,Adlba01,Adlbr01,Adlbr02,Adlmi01,Adlmu01,Adlmu02,Adlpa01,Adlsu01,Afrre01,Ampae01,Ampaf01,Ampal01,Ampat01,Ampbi01,Ampbu01,Ampco01,Ampcu01,Ampde01,Ampdi01,Ampdi02,Ampdu01,Ampei01,Ampex01,Ampfo01,Ampfo02,Amphe01,Amphi01,Ampin01,Ampin02,Ampli01,Ampma01,Ampme01,Ampmi01,Ampmi02,Ampmo01,Ampne01,Ampne02,Ampno01,Ampol01,Ampov01,Amppa01,Amppe01,Amppe02,Amppo01,Amppo02,Amppr01,Ampps01,Ampri01,Ampst01,Ampst02,Ampsu01,Ampsu02,Ampsu03,Ampsu04,Amptu01,Ampve01,Ampve02,Ampvi01,Anaba01,Anemi01,Anetu01,Anoeu01,Anoga01,Anoin01,Anosp01,Astfo01,Aulal01,Aulam01,Aulbr01,Aulcr01,Aulcr02,Auldi01,Aulgr01,Aulis01,Aulit01,Aulli01,Aulni01,Aulpa01,Aulps01,Aulps02,Aulsu01,Aulsu02,Aulte01,Aulva01,Azpno01,Bacci01,Bacpa01,Bacul01,Berru01,Bible01,Birbi01,Brabr01,Braca01,Brali01,Brane01,Brane02,Brapr01,Braps01,Breke01,Calae01,Calae02,Calal01,Calau01,Calba01,Calbi01,Calfa01,Calfo01,Calfo02,Calhy01,Calla01,Calla02,Calla03,Calle01,Calmi01,Calpa01,Calpu01,Calsc01,Calsi01,Caltr01,Calve01,Calwe01,Camcy01,Camhi01,Capcr01,Catad01,Cavpa01,Cenre01,Cergr01,Chaal01,Chabe01,Chafa01,Chamu01,Chare01,Charh01,Chasc01,Chath01,Clico01,Cliin01,Cocbr01,Cocca01,Coccl01,Cocco01,Cocde01,Cocdi01,Cocdi02,Coceu01,Cocgr01,Cochu01,Cochu02,Cocin01,Cocla01,Cocle01,Cocli01,Cocme01,Cocne01,Cocne02,Cocne03,Cocpa01,Cocpe01,Cocpl01,Cocps01,Cocps02,Cocre01,Cocro01,Cocsc01,Cocse01,Cocsu01,Conwe01,Cosco01,Cosla01,Cosla02,Craac01,Craac02,Craha01,Crari01,Crasu01,Crasv01,Cravi01,Crazi01,Creru01,Creth01,Ctepu01,Cycat01,Cycbo01,Cycco01,Cyccy01,Cycde01,Cycde02,Cycdi01,Cycdu01,Cycex01,Cycgl01,Cycir01,Cyckr01,Cycku01,Cycme01,Cycme02,Cycmi01,Cycop01,Cycpl01,Cycpl02,Cycps01,Cycsc01,Cycsc02,Cycst01,Cycst02,Cycst03,Cycst04,Cycsu01,Cycth01,Cycwo01,Cylgr01,Cymaf01,Cymaf02,Cymal01,Cymal02,Cymam01,Cyman01,Cyman02,Cyman03,Cyman04,Cymap01,Cymas01,Cymbe01,Cymbi01,Cymbr01,Cymbu01,Cymci01,Cymco01,Cymcu01,Cymcy01,Cymdi01,Cymdo01,Cymeh01,Cymel01,Cymel02,Cymex01,Cymex02,Cymex03,Cymfl01,Cymfr01,Cymga01,Cymhe01,Cymhe02,Cymhu01,Cymin01,Cymin02,Cymin03,Cymka01,Cymko01,Cymku01,Cymla01,Cymla02,Cymla03,Cymlu01,Cymma01,Cymme01,Cymme02,Cymmi01,Cymna01,Cymna02,Cymne01,Cymne02,Cymne03,Cymob01,Cymob02,Cympa01,Cympe01,Cympe02,Cympl01,Cympr01,Cympr02,Cympr03,Cympu01,Cymre01,Cymrh01,Cymru01,Cymsi01,Cymsi02,Cymsi03,Cymso01,Cymsp01,Cymst01,Cymsu01,Cymsu02,Cymsu03,Cymsu04,Cymsu05,Cymsu06,Cymsu07,Cymsu08,Cymsu09,Cymtr01,Cymtr02,Cymtu01,Cymtu02,Cymtu03,Cymtu04,Cymve01,Cymvu01,Delal01,Delap01,Delco01,Delde01,Delde02,Delkr01,Delve01,Dener01,Denfr01,Denku01,Denpa01,Dense01,Densu01,Densu02,Denta01,Dente01,Diabi01,Diaco01,Diade01,Diaeh01,Diaga01,Diahy01,Diame01,Diamo01,Diapa01,Diapr01,Diapy01,Diate01,Diate02,Diavi01,Diavu01,Dicda01,Didge01,Dimna01,Dipab01,Dipae01,Dipbo01,Dipbo02,Dipbu01,Dipca01,Dipca02,Dipde01,Dipel01,Dipfo01,Dipfo02,Diphi01,Dipkr01,Dipma01,Dipmi01,Dipmo01,Dipob01,Dippa01,Dippa02,Dippe01,Dippr01,Dipps01,Dippu01,Dipse01,Dipst01,Dipsu01,Dipti01,Disin01,Disst01,Dorko01,Encae01,Encaf01,Encal01,Encal02,Encau01,Encbl01,Encbo01,Encbr01,Encca01,Encce01,Encel01,Encfa01,Encfo01,Encfo02,Encge01,Encgr01,Enche01,Encho01,Enchu01,Encin01,Enckr01,Enckr02,Encla01,Encla02,Enclu01,Encme01,Encmi01,Encmi02,Encmi03,Encmi04,Encmu01,Encne01,Encne02,Encne03,Encno01,Encob01,Encpa01,Encpe01,Encpr01,Encpr02,Encre01,Encre02,Encro01,Encro02,Encsi01,Encsi02,Encsp01,Encsu01,Encsu02,Encsu03,Encsy01,Encta01,Encth01,Encva01,Encvu01,Entor01,Entpa01,Eolar01,Eolbe01,Eolch01,Eolco01,Eolcr01,Eolin01,Eolrh01,Epifr01,Epigo01,Epiin01,Epiop01,Epipa01,Epire01,Epiru01,Epism01,Episo01,Epitu01,Ethpu01,Eucal01,Eucau01,Eucdi01,Eucla01,Eunam01,Eunar01,Eunar02,Eunar03,Eunar04,Eunau01,Eunbe01,Eunbi01,Eunbi02,Eunbi03,Eunbi04,Eunbi05,Eunbo01,Eunbo02,Eunbo03,Eunch01,Eunci01,Eunci02,Eunci03,Euncu01,Eunde01,Eundi01,Eundi02,Eundo01,Eunel01,Eunen01,Eunfa01,Eunfl01,Eunfo01,Eunfo02,Eunge01,Eunge02,Eungi01,Eungl01,Eungl02,Eungr01,Eunim01,Eunin01,Eunin02,Eunis01,Eunkr01,Eunla01,Eunla02,Eunme01,Eunme02,Eunme03,Eunmi01,Eunmi02,Eunmo01,Eunmu01,Eunmy01,Eunna01,Eunne01,Eunne02,Eunny01,Eunoc01,Eunor01,Eunpa01,Eunpa02,Eunpa03,Eunpa04,Eunpa05,Eunpe01,Eunpe02,Eunpe03,Eunpr01,Eunps01,Eunps02,Eunrh01,Eunse01,Eunse02,Eunse03,Eunsi01,Eunso01,Eunst01,Eunsu01,Eunsu02,Eunsu03,Eunsu04,Eunta01,Eunte01,Eunte02,Eunth01,Euntr01,Euntr02,Eunur01,Eunva01,Eunva02,Eunyb01,Exipu01,Exiva01,Falcl01,Falcr01,Falom01,Falpy01,Fraac01,Fraac02,Fraac03,Fraae01,Fraal01,Fraam01,Fraam02,Fraan01,Fraaq01,Fraat01,Fraau01,Frabi01,Frabi02,Frabi03,Frabi04,Frabi05,Frabo01,Frabr01,Fraca01,Fraca02,Fraca03,Fraca04,Fraca05,Fraco01,Fraco02,Fracr01,Frade01,Frade02,Fradi01,Frael01,Fraex01,Frafo01,Frafr01,Frage01,Frage02,Fragr01,Fragr02,Fraha01,Frahe01,Frain01,Frain02,Fraka01,Frala01,Frala02,Frala03,Frale01,Fralo01,Frame01,Frame02,Frami01,Frami02,Frami03,Frami04,Framu01,Frana01,Frana02,Frane01,Frane02,Frane03,Frane04,Frani01,Fraol01,Fraos01,Frapa01,Frapa02,Frapa03,Frape01,Frape02,Frape03,Frape04,Frapi01,Frapo01,Fraps01,Fraps02,Frapu01,Frara01,Frare01,Frari01,Fraro01,Fraru01,Frasa01,Frasa02,Frasi01,Frasu01,Frasu02,Frate01,Frate02,Frate03,Fratr01,Fraul01,Fraul02,Fraun01,Frave01,Fravi01,Fravi02,Fruad01,Fruam01,Fruap01,Fruau01,Fruco01,Frucr01,Frucu01,Frudi01,Fruer01,Frukr01,Fruli01,Fruma01,Frune01,Frune02,Frupa01,Frupu01,Fruqu01,Frure01,Frurh01,Frusa01,Fruse01,Frusp01,Fruve01,Fruvi01,Fruvu01,Fruwe01,Geiac01,Geige01,Geihi01,Geita01,Geren01,Glotr01,Gomac01,Gomac02,Gomac03,Gomae01,Gomaf01,Gomag01,Gomam01,Goman01,Goman02,Goman03,Goman04,Goman05,Goman06,Gomau01,Gomau02,Gomba01,Gombo01,Gombo02,Gombo03,Gombr01,Gombr02,Gomca01,Gomca02,Gomca03,Gomca04,Gomca05,Gomcl01,Gomcl02,Gomcl03,Gomco01,Gomco02,Gomco03,Gomco04,Gomco05,Gomcu01,Gomcu02,Gomcu03,Gomcy01,Gomda01,Gomde01,Gomde02,Gomdi01,Gomdr01,Gomel01,Gomen01,Gomer01,Gomer02,Gomex01,Gomex02,Gomfo01,Gomfr01,Gomgr01,Gomgr02,Gomgr03,Gomgr04,Gomha01,Gomhe01,Gomho01,Gomho02,Gomin01,Gomin02,Gomin03,Gomin04,Gomin05,Gomin06,Gomit01,Gomja01,Gomje01,Gomko01,Gomla01,Gomla02,Gomla03,Gomla04,Gomla05,Gomla06,Gomli01,Gomli02,Gomli03,Gomli04,Gomli05,Gomlo01,Gomlo02,Gomma01,Gomme01,Gommi01,Gommi02,Gommi03,Gommi04,Gommi05,Gomna01,Gomoa01,Gomob01,Gomob02,Gomoc01,Gomoh01,Gomol01,Gomol02,Gomol03,Gomol04,Gomop01,Gompa01,Gompa02,Gompa03,Gompa04,Gompa05,Gompa06,Gompe01,Gompl01,Gompr01,Gompr02,Gompr03,Gomps01,Gomps02,Gomps03,Gompu01,Gompu02,Gompy01,Gomrh01,Gomro01,Gomsa01,Gomsi01,Gomsp01,Gomsp02,Gomst01,Gomst02,Gomsu01,Gomsu02,Gomsu03,Gomsu04,Gomsu05,Gomta01,Gomta02,Gomte01,Gomte02,Gomtr01,Gomtr02,Gomtu01,Gomtu02,Gomun01,Gomut01,Gomva01,Gomva02,Gomva03,Gomva04,Gomva05,Gomve01,Gomvi01,Gomvi02,Gomvi03,Gomze01,Grama01,Grase01,Grusi01,Gruta01,Gyrac01,Gyrat01,Gyrli01,Gyrob01,Gyrsc01,Halac01,Halap01,Halbu01,Halco01,Halcy01,Halho01,Halmo01,Halno01,Halol01,Halpe01,Halsu01,Halva01,Hanab01,Hanam01,Hanar01,Hanau01,Hanca01,Hanco01,Hanmo01,Hanps01,Hanre01,Hasdu01,Himex01,Himfa01,Himmi01,Himso01,Himve01,Hipar01,Hipca01,Hipca02,Hipco01,Hipco02,Hipge01,Hiplu01,Hipne01,Hipol01,Hipps01,Hippu01,Hipru01,Hipsu01,Hombu01,Homca01,Homco01,Homsu01,Humar01,Humbr01,Humco01,Humga01,Humpe01,Humsc01,Hydtr01,Hydwh01,Hygba01,Karam01,Karcl01,Karob01,Karpl01,Kobja01,Kobpa01,Kobps01,Kobsa01,Kobsu01,Kolsu01,Kurae01,Lacla01,Lemex01,Lemhu01,Lepmi01,Linau01,Linba01,Linbo01,Linco01,Linco02,Linco03,Linfo01,Linpr01,Linra01,Linte01,Lutac01,Lutco01,Lutfr01,Lutgo01,Luthl01,Lutin01,Lutna01,Lutpe01,Lutpe02,Lutps01,Lutro01,Lutsa01,Lutsi01,Lutsp01,Lutve01,Masac01,Masba01,Masel01,Masex01,Masex02,Masin01,Masla01,Maspa01,Massm01,Masva01,Mayas01,Mayca01,Mayca02,Mayin01,Melar01,Melcr01,Meldi01,Meldi02,Melgr01,Melit01,Melja01,Mello01,Melly01,Melmo01,Melmu01,Melny01,Melpf01,Melpu01,Melsc01,Melsp01,Melte01,Melte02,Melva01,Merci01,Merco01,Mesme01,Micgr01,Mickr01,Micpa01,Micpo01,Minch01,Monpr01,Muegi01,Muesp01,Nankr01,Nanso01,Nantr01,Navab01,Navab02,Navab03,Navac01,Navac02,Navac03,Navad01,Navad02,Navag01,Navag02,Navag03,Naval01,Naval02,Navam01,Navam02,Navam03,Navam04,Navam05,Navam06,Navam07,Navan01,Navan02,Navan03,Navan04,Navan05,Navan06,Navap01,Navap02,Navaq01,Navaq02,Navar01,Navar02,Navar03,Navar04,Navas01,Navat01,Navat02,Navau01,Navba01,Navba02,Navba03,Navbi01,Navbi02,Navbi03,Navbj01,Navbo01,Navbr01,Navbr02,Navbr03,Navbr04,Navbr05,Navbr06,Navbr07,Navbu01,Navbu02,Navca01,Navca02,Navca03,Navca04,Navca05,Navca06,Navca07,Navca08,Navca09,Navca10,Navca11,Navce01,Navch01,Navci01,Navci02,Navcl01,Navcl02,Navcl03,Navcl04,Navco01,Navco02,Navco03,Navco04,Navco05,Navco06,Navco07,Navcr01,Navcr02,Navcr03,Navcr04,Navcr05,Navcr06,Navcr07,Navcr08,Navcr09,Navcr10,Navcu01,Navcu02,Navde01,Navde02,Navde03,Navde04,Navde05,Navde06,Navde07,Navde08,Navdi01,Navdi02,Navdi03,Navdi04,Navdi05,Navdi06,Navdi07,Navdi08,Navdi09,Navdi10,Navdo01,Naveg01,Navei01,Navel01,Navel02,Navel03,Navel04,Naver01,Navev01,Navex01,Navex02,Navex03,Navfa01,Navfa02,Navfe01,Navfl01,Navfo01,Navfo02,Navfo03,Navfr01,Navga01,Navge01,Navge02,Navge03,Navgi01,Navgl01,Navgo01,Navgr01,Navgr02,Navgr03,Navha01,Navha02,Navha03,Navha04,Navha05,Navha06,Navha07,Navha08,Navhe01,Navhe02,Navhe03,Navhe04,Navhi01,Navho01,Navhu01,Navhu02,Navig01,Navig02,Navim01,Navin01,Navin02,Navin03,Navin04,Navin05,Navin06,Navin07,Navin08,Navin09,Navin10,Navir01,Navir02,Navja01,Navja02,Navja03,Navjo01,Navju01,Navko01,Navko02,Navkr01,Navku01,Navla01,Navla02,Navla03,Navla04,Navla05,Navla06,Navla07,Navle01,Navle02,Navle03,Navle04,Navle05,Navle06,Navli01,Navli02,Navli03,Navlo01,Navlo02,Navlo03,Navlu01,Navlu02,Navlu03,Navma01,Navma02,Navma03,Navma04,Navma05,Navme01,Navme02,Navme03,Navme04,Navme05,Navme06,Navmi01,Navmi02,Navmi03,Navmi04,Navmi05,Navmi06,Navmi07,Navmi08,Navmi09,Navmo01,Navmo02,Navmo03,Navmo04,Navmo05,Navmo06,Navmo07,Navmo08,Navmo09,Navmo10,Navmu01,Navmu02,Navmu03,Navmu04,Navmu05,Navmu06,Navmu07,Navna01,Navne01,Navne02,Navni01,Navno01,Navno02,Navno03,Navnu01,Navny01,Navob01,Navob02,Navob03,Navob04,Navob05,Navob06,Navoc01,Navol01,Navop01,Navop02,Navop03,Navpa01,Navpa02,Navpa03,Navpa04,Navpa05,Navpa06,Navpa07,Navpe01,Navpe02,Navpe03,Navpe04,Navpe05,Navpe06,Navph01,Navph02,Navpl01,Navpr01,Navpr02,Navpr03,Navps01,Navps02,Navps03,Navps04,Navps05,Navps06,Navps07,Navps08,Navps09,Navps10,Navps11,Navps12,Navpu01,Navpu02,Navpu03,Navpu04,Navpy01,Navqu01,Navra01,Navra02,Navra03,Navra04,Navre01,Navre02,Navre03,Navre04,Navre05,Navre06,Navrh01,Navrh02,Navrh03,Navri01,Navri02,Navri03,Navri04,Navro01,Navro02,Navru01,Navsa01,Navsa02,Navsa03,Navsa04,Navsa05,Navsa06,Navsa07,Navsc01,Navsc02,Navsc03,Navsc04,Navsc05,Navsc06,Navsc07,Navsc08,Navse01,Navse02,Navse03,Navse04,Navse05,Navse06,Navse07,Navsi01,Navsi02,Navsi03,Navsi04,Navsl01,Navsm01,Navso01,Navsp01,Navsp02,Navsp03,Navst01,Navst02,Navst03,Navst04,Navst05,Navst06,Navst07,Navsu01,Navsu02,Navsu03,Navsu04,Navsu05,Navsu06,Navsu07,Navsu08,Navsu09,Navsu10,Navsu11,Navsu12,Navsu13,Navsu14,Navsu15,Navsu16,Navsu17,Navsu18,Navsu19,Navsu20,Navsy01,Navsy02,Navta01,Navta02,Navte01,Navte02,Navte03,Navth01,Navto01,Navtr01,Navtr02,Navtr03,Navtr04,Navtr05,Navtr06,Navtr07,Navtu01,Navtu02,Navul01,Navum01,Navum02,Navun01,Navut01,Navva01,Navva02,Navva03,Navva04,Navva05,Navva06,Navve01,Navve02,Navve03,Navve04,Navve05,Navve06,Navve07,Navvi01,Navvi02,Navvi03,Navvi04,Navwe01,Navwi01,Navwi02,Navwi03,Navwi04,Navwy01,Navza01,Navze01,Neiaf01,Neial01,Neiam01,Neiap01,Neibi01,Neibi02,Neibi03,Neibi04,Neica01,Neico01,Neicu01,Neide01,Neidu01,Neiel01,Neihe01,Neihu01,Neiin01,Neiir01,Neilo01,Neipe01,Neipr01,Neips01,Neise01,Neisu01,Neite01,Neive01,Neoco01,Nitab01,Nitac01,Nitac02,Nitac03,Nitac04,Nitac05,Nitac06,Nitad01,Nitae01,Nitae02,Nitag01,Nitag02,Nital01,Nital02,Nital03,Nitam01,Nitam02,Nitam03,Nitam04,Nitan01,Nitan02,Nitar01,Nitar02,Nitau01,Nitau02,Nitba01,Nitba02,Nitba03,Nitba04,Nitbe01,Nitbe02,Nitbi01,Nitbr01,Nitbr02,Nitbr03,Nitca01,Nitca02,Nitca03,Nitcl01,Nitco01,Nitco02,Nitco03,Nitco04,Nitco05,Nitco06,Nitco07,Nitcu01,Nitcu02,Nitcu03,Nitde01,Nitde02,Nitde03,Nitde04,Nitde05,Nitde06,Nitdi01,Nitdi02,Nitdi03,Nitdi04,Nitdi05,Nitdi06,Nitdr01,Nitdu01,Nitel01,Nitep01,Nitet01,Niteu01,Nitfa01,Nitfi01,Nitfi02,Nitfl01,Nitfl02,Nitfo01,Nitfo02,Nitfr01,Nitfr02,Nitfr03,Nitfu01,Nitge01,Nitgi01,Nitgo01,Nitgr01,Nitgr02,Nitgr03,Nitha01,Nitha02,Nithe01,Nitho01,Nitho02,Nithu01,Nitin01,Nitin02,Nitin03,Nitin04,Nitin05,Nitju01,Nitla01,Nitla02,Nitla03,Nitla04,Nitla05,Nitla06,Nitla07,Nitle01,Nitle02,Nitli01,Nitli02,Nitli03,Nitli04,Nitlo01,Nitma01,Nitme01,Nitmi01,Nitmi02,Nitmi03,Nitmi04,Nitmo01,Nitmo02,Nitna01,Nitob01,Nitov01,Nitpa01,Nitpa02,Nitpa03,Nitpa04,Nitpa05,Nitpa06,Nitpa07,Nitpa08,Nitpa09,Nitpe01,Nitpe02,Nitpe03,Nitpe04,Nitpi01,Nitpl01,Nitps01,Nitps02,Nitpu01,Nitpu02,Nitpu03,Nitpu04,Nitra01,Nitre01,Nitre02,Nitre03,Nitre04,Nitrh01,Nitro01,Nitro02,Nitro03,Nitsc01,Nitse01,Nitsi01,Nitsi02,Nitsi03,Nitso01,Nitso02,Nitso03,Nitso04,Nitsp01,Nitst01,Nitsu01,Nitsu02,Nitsu03,Nitsu04,Nitsu05,Nitsu06,Nitsu07,Nitsu08,Nitsu09,Nitsy01,Nitta01,Nitte01,Nitte02,Nitth01,Nitth02,Nittr01,Nittr02,Nittu01,Nitva01,Nitva02,Nitve01,Nitve02,Nitvi01,Nitvi02,Nitwu01,Nitzu01,Nupca01,Nupde01,Nupel01,Nupex01,Nupfe01,Nupim01,Nupim02,Nupla01,Nupma01,Nupne01,Nuppa01,Nuppa02,Nuppr01,Nuppr02,Nupru01,Nupsc01,Nupsi01,Nupsu01,Nuptr01,Nupvy01,Nupwe01,Odoau01,Odohy01,Odomu01,Odone01,Odosp01,Opebu01,Opema01,Opemi01,Opeol01,Opepa01,Ortro01,Panco01,Panco02,Pande01,Panoc01,Panpo01,Panps01,Panro01,Panwu01,Parde01,Parhe01,Parmi01,Parpr01,Parrh01,Parsu01,Pendi01,Perfi01,Perpe01,Pinac01,Pinac02,Pinac03,Pinac04,Pinam01,Pinan01,Pinan02,Pinan03,Pinap01,Pinbi01,Pinbo01,Pinbr01,Pinbr02,Pinca01,Pincl01,Pinde01,Pindi01,Pindi02,Pindo01,Pindu01,Pinel01,Pinel02,Pinex01,Pinfa01,Pinfe01,Pinfr01,Pinfr02,Pingi01,Pingl01,Pingr01,Pingr02,Pinin01,Pinin02,Pinin03,Pinis01,Pinkn01,Pinkr01,Pinkr02,Pinku01,Pinla01,Pinla02,Pinle01,Pinlu01,Pinma01,Pinma02,Pinma03,Pinma04,Pinma05,Pinme01,Pinme02,Pinmi01,Pinmo01,Pinmo02,Pinmo03,Pinmu01,Pinna01,Pinne01,Pinno01,Pinno02,Pinob01,Pinov01,Pinpa01,Pinpa02,Pinpe01,Pinpe02,Pinpe03,Pinpe04,Pinpe05,Pinpl01,Pinpo01,Pinpo02,Pinps01,Pinra01,Pinre01,Pinrh01,Pinrh02,Pinrh03,Pinru01,Pinru02,Pinsa01,Pinsa02,Pinsa03,Pinsc01,Pinsc02,Pinsc03,Pinsc04,Pinsi01,Pinsi02,Pinsi03,Pinsi04,Pinst01,Pinst02,Pinsu01,Pinsu02,Pinsu03,Pinsu04,Pinsu05,Pinsu06,Pinsu07,Pinsu08,Pinsu09,Pinsu10,Pinsu11,Pinte01,Pinth01,Pintr01,Pinvi01,Pinvi02,Plaab01,Plaam01,Plaap01,Plaat01,Plaau01,Plaba01,Plaba02,Plabi01,Plabr01,Placa01,Placl01,Placl02,Placu01,Pladi01,Pladu01,Plael01,Plaga01,Plaga02,Plaga03,Plaha01,Plaha02,Plahi01,Plain01,Plaki01,Plala01,Plala02,Plalu01,Plama01,Plame01,Plami01,Plami02,Plana01,Plaob01,Plaoe01,Plapa01,Plapa02,Plape01,Plape02,Plape03,Plapl01,Plapo01,Plaps01,Plapu01,Plare01,Plaro01,Plaro02,Plaro03,Plaro04,Plaro05,Plasa01,Plasi01,Plast01,Plata01,Plats01,Plava01,Plava02,Plavi01,Plawe01,Plean01,Plebr01,Plede01,Pleku01,Plela01,Pleno01,Pleob01,Plepr01,Plesa01,Plesc01,Plesp01,Plewo01,Porpe01,Pratr01,Prepr01,Prepr02,Pretu01,Prohu01,Psaab01,Psaac01,Psaal01,Psabi01,Psabr01,Psabu01,Psaco01,Psafr01,Psahe01,Psami01,Psaob01,Psapu01,Psasa01,Psave01,Pse(a01,Pseal01,Psebi01,Psebo01,Psebr01,Pseca01,Psecl01,Pseco01,Psege01,Pseme01,Pseoc01,Pseop01,Psepa01,Psepa02,Psepo01,Psero01,Psesm01,Pseso01,Psevu01,Pulob01,Punbo01,Pundi01,Pungl01,Punov01,Punpr01,Punra01,Pyxco01,Reifo01,Reisi01,Reiun01,Rhaam01,Rhami01,Rhasu01,Rhipr01,Rhoab01,Rhobr01,Rhogi01,Rhogi02,Rhote01,Rhova01,Rosan01,Scema01,Scemu01,Schbr01,Schcr01,Schex01,Schla01,Selab01,Selar01,Selar02,Selat01,Selau01,Selba01,Selbl01,Selbo01,Selca01,Selch01,Selco01,Selcr01,Selda01,Seldi01,Selel01,Selja01,Sella01,Sella02,Selmu01,Selni01,Selpa01,Selps01,Selps02,Selps03,Selpu01,Selra01,Selre01,Selrh01,Selrh02,Selro01,Selru01,Selsa01,Selsa02,Selsc01,Selsu01,Selsu02,Seltr01,Selut01,Selve01,Semin01,Semro01,Skaoe01,Skape01,Skepe01,Skesu01,Spisp01,Staac01,Staac02,Staac03,Staac04,Staag01,Staal01,Staam01,Staam02,Staam03,Staan01,Stabe01,Stabo01,Stabo02,Stabo03,Stabr01,Stach01,Staco01,Staco02,Stacr01,Stadi01,Stadu01,Stadu02,Staex01,Stagr01,Stagr02,Stahe01,Stain01,Stain02,Stain03,Stakr01,Stakr02,Stala01,Stala02,Stala03,Stale01,Stale02,Stale03,Stale04,Stalo01,Stama01,Stami01,Stamu01,Stana01,Stane01,Stane02,Staob01,Staol01,Staol02,Staov01,Stapa01,Staph01,Stapi01,Stapi02,Stapl01,Stapo01,Stapr01,Stapu01,Stare01,Stare02,Staro01,Stasa01,Stase01,Stasi01,Stasm01,Stasp01,Stast01,Stasu01,Stasv01,State01,Stath01,Staun01,Stave01,Stawi01,Steal01,Stebr01,Steco01,Stede01,Stedu01,Steha01,Stein01,Steme01,Stemi01,Stena01,Stene01,Stepa01,Stero01,Stete01,Stetr01,Steve01,Surac01,Sural01,Suram01,Suran01,Surbi01,Surbi02,Surbi03,Surbo01,Surbr01,Surbr02,Surca01,Surch01,Surcr01,Surde01,Surel01,Surhe01,Surhi01,Surla01,Surli01,Surli02,Surma01,Surmi01,Surna01,Surol01,Surov01,Surpa01,Surre01,Surro01,Surro02,Surst01,Surst02,Sursu01,Sursu02,Surte01,Surte02,Surun01,Surve01,Survi01,Synac01,Synac02,Synaf01,Synam01,Synam02,Synba01,Synbe01,Synbi01,Synbi02,Synca01,Syncr01,Synda01,Synde01,Synde02,Synfa01,Synfa02,Synfl01,Synla01,Synma01,Synmi01,Synmo01,Synmo02,Synna01,Synpa01,Synpl01,Synru01,Synso01,Synul01,Synva01,Tabfa01,Tabfe01,Tabfl01,Tabin01,Tabta01,Tabve01,Tetgl01,Tetla01,Tetru01,Thaba01,Thabr01,Thadu01,Thage01,Thani01,Thaps01,Thavi01,Traac01,Traas01,Traau01,Triex01,Trire01,Tryan01,Tryan02,Tryap01,Trybr01,Tryca01,Tryco01,Tryco02,Tryde01,Trygr01,Tryku01,Tryle01,Trysu01,Tryvi01,Tscmi01,Ulngr01,Ulnul01,Vibtr01,Witan01,Withu01,Witps01,Witsu01,Witsy01,Zygsu01,Longitude_Lambert93,Latitude_Lambert93,Watershed,CodeDepartement,HERlvl1Code,HERlvl1Name,HERlvl2Code,HERlvl2Name,Altitude,Streamsize,Nitrogencompounds_Status1Y,Nitrogencompounds_Status180D,Nitrogencompounds_Status90D,Nitrates_Status1Y,Nitrates_Status180D,Nitrates_Status90D,Phosphorouscompounds_Status1Y,Phosphorouscompounds_Status180D,Phosphorouscompounds_Status90D,Acidification_Status1Y,Acidification_Status180D,Acidification_Status90D,PAH_Status1Y,PAH_Status180D,PAH_Status90D,OrganicMatter_Status1Y,OrganicMatter_Status180D,OrganicMatter_Status90D,SuspendedMatter_Status1Y,SuspendedMatter_Status180D,SuspendedMatter_Status90D,OrganicMicropollutants_Status1Y,OrganicMicropollutants_Status180D,OrganicMicropollutants_Status90D,MineralMicropollutants_Status1Y,MineralMicropollutants_Status180D,MineralMicropollutants_Status90D,IBD,IBD_EQR,IBD_EQR_Status

In [23]:
envmeans = pd.read_parquet("C:\\Users\\herie\\OneDrive - Fundacion Universidad de las Americas Puebla\\Proyectos\\En Proceso\\Clasificacion-de-Calidad-del-Agua-IBD-EQR\\data\\raw\\05_EnvParamMeans_GTstudentproject_B.parquet")

In [25]:
envparam = pd.read_parquet("C:\\Users\\herie\\OneDrive - Fundacion Universidad de las Americas Puebla\\Proyectos\\En Proceso\\Clasificacion-de-Calidad-del-Agua-IBD-EQR\\data\\raw\\06_ListEnvParam_GNNprojectGT_B.parquet")

In [26]:
envparam

,Pressure,Parameter_label_eng,Parameter_label_fr,Parameter_code,Parameter_unit,Threshold_HighGood,Note_HighGood,Threshold_GoodModerate,Note_GoodModerate,Threshold_ModeratePoor,Note_ModeratePoor,Threshold_PoorBad,Note_PoorBad,NoteOther
0,Acidification,Aluminium,Aluminium,1370,µg / L,5.000000,pH<6.5,10.00000,pH<6.5,50.0000,pH<6.5,100.00,pH<6.5,None
1,Acidification,Aluminium,Aluminium,1370,µg / L,100.000000,pH>6.5,200.00000,pH>6.5,400.0000,pH>6.5,800.00,pH>6.5,None
2,Acidification,pH,Potentiel en Hydrogène (pH),1302,None,6.500000,minimum,6.00000,minimum,5.5000,minimum,4.50,minimum,None
3,Acidification,pH,Potentiel en Hydrogène (pH),1302,None,8.200000,maximum,9.00000,maximum,9.5000,maximum,10.00,maximum,None
4,Mineral Micropollutants,Arsenic,Arsenic,1369,µg / L,1.000000,None,10.00000,None,100.0000,None,270.00,None,None
5,Mineral Micropollutants,Cadmium,Cadmium,1388,µg / L,0.001000,CaCO3 ≤ 50 mg/L,0.01000,CaCO3 ≤ 50 mg/L,0.1000,CaCO3 ≤ 50 mg/L,0.37,CaCO3 ≤ 50 mg/L,None
6,Mineral Micropollutants,Cadmium,Cadmium,1388,µg / L,0.004000,50 < CaCO3 ≤ 200 mg/L,0.04000,50 < CaCO3 ≤ 200 mg/L,0.3700,50 < CaCO3 ≤ 200 mg/L,1.30,50 < CaCO3 ≤ 200 mg/L,None
7,Mineral Micropollutants,Cadmium,Cadmium,1388,µg / L,0.009000,CaCO3 > 200 mg/L,0.09000,CaCO3 > 200 mg/L,0.8500,CaCO3 > 200 mg/L,3.00,CaCO3 > 200 mg/L,None
8,Mineral Micropollutants,Chromium,Chrome,1389,µg / L,0.040000,CaCO3 ≤ 50 mg/L,0.40000,CaCO3 ≤ 50 mg/L,3.6000,CaCO3 ≤ 50 mg/L,70.00,CaCO3 ≤ 50 mg/L,None
9,Mineral Micropollutants,Chromium,Chrome,1389,µg / L,0.180000,50 < CaCO3 ≤ 200 mg/L,1.80000,50 < CaCO3 ≤ 200 mg/L,18.0000,50 < CaCO3 ≤ 200 mg/L,350.00,50 < CaCO3 ≤ 200 mg/L,None
10,Mineral Micropollutants,Chromium,Chrome,1389,µg / L,0.360000,CaCO3 > 200 mg/L,3.60000,CaCO3 > 200 mg/L,36.0000,CaCO3 > 200 mg/L,700.00,CaCO3 > 200 mg/L,None
11,Mineral Micropollutants,Copper,Cuivre,1392,µg / L,0.017000,CaCO3 ≤ 50 mg/L,0.17000,CaCO3 ≤ 50 mg/L,1.7000,CaCO3 ≤ 50 mg/L,2.50,CaCO3 ≤ 50 mg/L,None
12,Mineral Micropollutants,Copper,Cuivre,1392,µg / L,0.100000,50 < CaCO3 ≤ 200 mg/L,1.00000,50 < CaCO3 ≤ 200 mg/L,10.0000,50 < CaCO3 ≤ 200 mg/L,15.00,50 < CaCO3 ≤ 200 mg/L,None
13,Mineral Micropollutants,Copper,Cuivre,1392,µg / L,0.270000,CaCO3 > 200 mg/L,2.70000,CaCO3 > 200 mg/L,27.0000,CaCO3 > 200 mg/L,40.00,CaCO3 > 200 mg/L,None
14,Mineral Micropollutants,Free cyanides,Cyanures libres,1084,µg / L,0.020000,None,0.20000,None,2.0000,None,240.00,None,None
15,Mineral Micropollutants,Lead,Plomb,1382,µg / L,0.210000,CaCO3 ≤ 50 mg/L,2.10000,CaCO3 ≤ 50 mg/L,21.0000,CaCO3 ≤ 50 mg/L,100.00,CaCO3 ≤ 50 mg/L,None
16,Mineral Micropollutants,Lead,Plomb,1382,µg / L,0.520000,50 < CaCO3 ≤ 200 mg/L,5.20000,50 < CaCO3 ≤ 200 mg/L,52.0000,50 < CaCO3 ≤ 200 mg/L,250.00,50 < CaCO3 ≤ 200 mg/L,None
17,Mineral Micropollutants,Lead,Plomb,1382,µg / L,1.000000,CaCO3 > 200 mg/L,10.00000,CaCO3 > 200 mg/L,100.0000,CaCO3 > 200 mg/L,500.00,CaCO3 > 200 mg/L,None
18,Mineral Micropollutants,Mercury,Mercure,1387,µg / L,0.007000,None,0.07000,None,0.7000,None,3.00,None,None
19,Mineral Micropollutants,Nickel,Nickel,1386,µg / L,0.250000,CaCO3 ≤ 50 mg/L,2.50000,CaCO3 ≤ 50 mg/L,25.0000,CaCO3 ≤ 50 mg/L,140.00,CaCO3 ≤ 50 mg/L,None
20,Mineral Micropollutants,Nickel,Nickel,1386,µg / L,0.620000,50 < CaCO3 ≤ 200 mg/L,6.20000,50 < CaCO3 ≤ 200 mg/L,62.0000,50 < CaCO3 ≤ 200 mg/L,360.00,50 < CaCO3 ≤ 200 mg/L,None
21,Mineral Micropollutants,Nickel,Nickel,1386,µg / L,1.200000,CaCO3 > 200 mg/L,12.00000,CaCO3 > 200 mg/L,120.0000,CaCO3 > 200 mg/L,720.00,CaCO3 > 200 mg/L,None
22,Mineral Micropollutants,Tin,Etain,1380,µg / L,1.000000,None,10.00000,None,100.0000,None,55000.00,None,None
23,Mineral Micropollutants,Zinc,Zinc,1383,µg / L,0.230000,CaCO3 ≤ 50 mg/L,2.30000,CaCO3 ≤ 50 mg/L,23.0000,CaCO3 ≤ 50 mg/L,52.00,CaCO3 ≤ 50 mg/L,None
24,Mineral Micropollutants,Zinc,Zinc,1383,µg / L,0.430000,50 < CaCO3 ≤ 200 mg/L,4.30000,50 < CaCO3 ≤ 200 mg/L,43.0000,50 < CaCO3 ≤ 200 mg/L,98.00,50 < CaCO3 ≤ 200 mg/L,None
25,Mineral Micropollutants,Zinc,Zinc,1383,µg / L,1.400000,CaCO3 > 200 mg/L,14.00000,CaCO3 > 200 mg/L,140.0000,CaCO3 > 200 mg/L,330.00,CaCO3 > 200 mg/L,None
26,Nitrogen compounds,Ammonium,Ammonium,1335,mg NH4 / L,0.100000,None,0.50000,None,2.0000,None,5.00,None,None
27,Nitrogen compounds,Kjeldahl nitrogen,Azote Kjeldahl,1319,mg N / L,1.000000,None,2.00000,None,4.0000,None,10.00,None,None
28,Nitrogen compounds,Nitrites,Nitrites,1339,mg NO2 / L,0.030000,None,0.30000,None,0.5000,None,1.00,None,None
29,Nitrates,Nitrates,Nitrates,1340,mg NO3 / L,2.000000,None,10.00000,None,25.0000,None,50.00,None,None
30,Organic Matter,Ammonium,Ammonium,1335,mg NH4 / L,0.500000,None,1.50000,None,4.0000,None,8.00,None,None
31,Organic Matter,BOD5,Demande Biochimique en oxygène en 5 jours (D.B...,1313,mg O2 / L,3.000000,None,6.00000,None,10.0000,None,25.00,None,None
32,Organic Matter,Chemical oxygen demand,Demande Chimique en Oxygène (DCO),1314,mg O2 / L,20.000000,None,30.00000,None,40.0000,None,80.00,None,None
33,Organic Matter,Dissolved oxygen,Oxygène dissous,1311,mg O2 / L,8.000000,None,6.00000,None,4.0000,None,3.00,None,None
34,Organic Matter,Kjeldahl nitrogen,Azote Kjeldahl,1319,mg N / L,1.000000,None,2.00000,None,6.0000,None,12.00,None,None
35,Organic Matter,O2 saturation,Taux de saturation en oxygène,1312,%,90.000000,None,70.00000,None,50.0000,None,30.00,None,None
36,Organic Matter,Organic carbon,Carbone Organique,1841,mg C / L,5.000000,None,7.00000,None,10.0000,None,15.00,None,None
37,Organic Micropollutants,4-n-nonylphenol,4-n-nonylphénol,5474,µg / L,0.033000,None,0.33000,None,3.3000,None,21.00,None,None
38,Organic Micropollutants,4-nonylphenols,4-nonylphenols ramifiés,1958,µg / L,0.033000,None,0.33000,None,3.3000,None,21.00,None,None
39,Organic Micropollutants,Benzene,Benzène,1114,µg / L,0.500000,None,5.00000,None,5.0000,None,5000.00,None,None
40,Organic Micropollutants,C10-13-chloroalcanes,C10-C13-CHLOROALCANES,1955,µg / L,0.050000,None,0.50000,None,5.0000,None,14.00,None,None
41,Organic Micropollutants,Chloroaniline-2,Chloroaniline-2,1593,µg / L,0.001000,None,0.01000,None,0.1000,None,10.00,None,None
42,Organic Micropollutants,Chloroaniline-3,Chloroaniline-3,1592,µg / L,0.001000,None,0.01000,None,0.1000,None,10.00,None,None
43,Organic Micropollutants,Chloroaniline-4,Chloroaniline-4,1591,µg / L,0.001000,None,0.01000,None,0.1000,None,10.00,None,None
44,Organic Micropollutants,Chloroforme,Chloroforme,1135,µg / L,1.200000,None,12.00000,None,120.0000,None,18000.00,None,None
45,Organic Micropollutants,"Chloronitrobenzene-1,2","Chloronitrobenzène-1,2",1469,µg / L,3.000000,None,30.00000,None,300.0000,None,3000.00,None,None
46,Organic Micropollutants,"Chloronitrobenzene-1,3","Chloronitrobenzène-1,3",1468,µg / L,3.000000,None,30.00000,None,300.0000,None,3000.00,None,None
47,Organic Micropollutants,"Chloronitrobenzene-1,4","Chloronitrobenzène-1,4",1470,µg / L,3.000000,None,30.00000,None,300.0000,None,3000.00,None,None
48,Organic Micropollutants,Chlorure triphenyletain,Chlorure de triphenyletain,1777,µg / L,0.002000,None,0.02000,None,0.2000,None,2.00,None,None
49,Organic Micropollutants,Cresol,Cresol,5275,µg / L,10.000000,None,100.00000,None,1000.0000,None,1400.00,None,"In the Seq-Eau list, there are three distinct ..."
50,Organic Micropollutants,Dibutyletain,Dibutylétain cation,7074,µg / L,0.090000,None,0.90000,None,9.0000,None,900.00,None,None
51,Organic Micropollutants,"Dichloroaniline-3,4","Dichloroaniline-3,4",1586,µg / L,0.003000,None,0.03000,None,0.3000,None,9.00,None,None
52,Organic Micropollutants,Dichlorobenzene,"Somme des 1,2-Dichlorobenzène +1,3-Dichloroben...",6249,µg / L,2.000000,None,20.00000,None,200.0000,None,740.00,None,Not directly available in the Naiades raw data...
53,Organic Micropollutants,Dichlorobenzene 12,"Dichlorobenzene-1,2",1165,µg / L,2.000000,None,20.00000,None,200.0000,None,740.00,None,None
54,Organic Micropollutants,Dichlorobenzene 13,"Dichlorobenzène-1,3",1164,µg / L,2.000000,None,20.00000,None,200.0000,None,740.00,None,None
55,Organic Micropollutants,Dichlorobenzene 14,"Dichlorobenzène-1,4",1166,µg / L,2.000000,None,20.00000,None,200.0000,None,740.00,None,None
56,Organic Micropollutants,Dichloroethane 12,"Dichloroéthane-1,2",1160,µg / L,110.000000,None,1100.00000,None,11000.0000,None,120000.00,None,None
57,Organic Micropollutants,"Dichloroethylene-1,2 cis","Dichloroéthylène-1,2 cis",1456,µg / L,110.000000,None,1100.00000,None,11000.0000,None,120000.00,None,None
58,Organic Micropollutants,Dichloromethane,Dichlorométhane,1168,µg / L,6.800000,None,68.00000,None,680.0000,None,68000.00,None,None
59,Organic Micropollutants,"Dichlorophenol-2,3","Dichlorophénol-2,3",1645,µg / L,2.000000,None,20.00000,None,200.0000,None,940.00,None,None
60,Organic Micropollutants,"Dichlorophenol-2,4","Dichlorophenol-2,4",1486,µg / L,2.000000,None,20.00000,None,200.0000,None,940.00,None,None
61,Organic Micropollutants,"Dichlorophenol-2,4+2,5","Somme du Dichlorophenol-2,4 et du Dichlorophen...",3336,µg / L,2.000000,None,20.00000,None,200.0000,None,940.00,None,None
62,Organic Micropollutants,"Dichlorophenol-2,5","Dichlorophénol-2,5",1649,µg / L,2.000000,None,20.00000,None,200.0000,None,940.00,None,None
63,Organic Micropollutants,"Dichlorophenol-2,6","Dichlorophénol-2,6",1648,µg / L,2.000000,None,20.00000,None,200.0000,None,940.00,None,None
64,Organic Micropollutants,"Dichlorophenol-3,4","Dichlorophénol-3,4",1647,µg / L,2.000000,None,20.00000,None,200.0000,None,940.00,None,None
65,Organic Micropollutants,"Dichlorophenol-3,5","Dichlorophénol-3,5",1646,µg / L,2.000000,None,20.00000,None,200.0000,None,940.00,None,None
66,Organic Micropollutants,Dichlorure dibutyletain,Dibutylétain cation,7074,µg / L,0.090000,None,0.90000,None,9.0000,None,900.00,None,None
67,Organic Micropollutants,Dihexyl phtalate,Dihexyl phtalate,2539,µg / L,NaN,None,0.30000,None,NaN,None,NaN,None,None
68,Organic Micropollutants,EDTA,EDTA,1493,µg / L,4.000000,None,41.00000,None,410.0000,None,41000.00,None,None
69,Organic Micropollutants,Hexachlorobenzene,Hexachlorobenzène,1199,µg / L,0.000700,None,0.00700,None,0.0700,None,7.00,None,None
70,Organic Micropollutants,Hexachlorobutadiene,Hexachlorobutadiène,1652,µg / L,0.010000,None,0.10000,None,1.0000,None,120.00,None,None
71,Organic Micropollutants,Nonylphenols,Nonylphénols mélange (linéaire ou ramifiés),6598,µg / L,0.033000,None,0.33000,None,3.3000,None,21.00,None,None
72,Organic Micropollutants,Octylphenol,Octylphenol,2904,µg / L,0.010000,None,0.10000,None,1.0000,None,90.00,None,None
73,Organic Micropollutants,Oxyde de dibutyletain,Oxyde de dibutylétain,1770,µg / L,0.090000,None,0.90000,None,9.0000,None,900.00,None,None
74,Organic Micropollutants,PBDE 203,octabromodiphényl éther (congénère 203),5986,µg / L,0.020000,None,0.20000,None,2.4000,None,NaN,None,None
75,Organic Micropollutants,Pentachlorophenol,Pentachlorophénol,1235,µg / L,0.010000,None,0.10000,None,1.0000,None,54.00,None,None
76,Organic Micropollutants,Sum of 13 PBDE,Somme des 13 PBDE,2923,µg / L,0.020000,None,0.20000,None,2.4000,None,NaN,None,Not in the Seq_eau list - Threshold set identi...
77,Organic Micropollutants,Sum of PBDE 194 to 205,Somme des octaBDE : PBDE 194 à 205,6047,µg / L,0.020000,None,0.20000,None,2.4000,None,NaN,None,Not in the Seq_eau list - Threshold set identi...
78,Organic Micropollutants,Toluene,Toluene,1278,µg / L,10.000000,None,100.00000,None,1000.0000,None,1500.00,None,None
79,Organic Micropollutants,Tributyletain,Tributylétain cation,2879,µg / L,0.000040,None,0.00040,None,0.0040,None,0.05,None,None
80,Organic Micropollutants,"Trichlorobenzene-1,2,3","Trichlorobenzène-1,2,3",1630,µg / L,0.300000,None,3.00000,None,30.0000,None,350.00,None,None
81,Organic Micropollutants,"Trichlorobenzene-1,2,4","Trichlorobenzène-1,2,4",1283,µg / L,0.300000,None,3.00000,None,30.0000,None,350.00,None,None
82,Organic Micropollutants,"Trichlorobenzene-1,3,5","Trichlorobenzène-1,3,5",1629,µg / L,0.300000,None,3.00000,None,30.0000,None,350.00,None,None
83,Organic Micropollutants,"Trichlorophenol-2,3,4","Trichlorophénol-2,3,4",1644,µg / L,0.050000,None,0.50000,None,4.5000,None,450.00,None,Not in the Seq_eau list - Threshold set identi...
84,Organic Micropollutants,"Trichlorophenol-2,3,5","Trichlorophénol-2,3,5",1643,µg / L,0.050000,None,0.50000,None,4.5000,None,450.00,None,None
85,Organic Micropollutants,"Trichlorophenol-2,3,6","Trichlorophénol-2,3,6",1642,µg / L,0.050000,None,0.50000,None,4.5000,None,450.00,None,None
86,Organic Micropollutants,"Trichlorophenol-2,4,5","Trichlorophenol-2,4,5",1548,µg / L,0.050000,None,0.50000,None,4.5000,None,450.00,None,None
87,Organic Micropollutants,"Trichlorophenol-2,4,6","Trichlorophénol-2,4,6",1549,µg / L,0.050000,None,0.50000,None,4.5000,None,450.00,None,None
88,Organic Micropollutants,"Trichlorophenol-3,4,5","Trichlorophénol-3,4,5",1723,µg / L,0.050000,None,0.50000,None,4.5000,None,450.00,None,None
89,Organic Micropollutants,Triphenyletain,Triphénylétain cation,6372,µg / L,0.002000,None,0.02000,None,0.2000,None,2.00,None,None
90,Organic Micropollutants,Xylene,Xylène,1780,µg / L,0.100000,None,1.00000,None,10.0000,None,1000.00,None,Somme des différents isomères du Xylène : Xylè...
91,Organic Micropollutants,Xylene meta + para,Somme du Xylène-méta et du Xylène-para,2925,µg / L,0.100000,None,1.00000,None,10.0000,None,1000.00,None,None
92,Organic Micropollutants,Xylene ortho+meta+para,None,XOMP,µg / L,0.100000,None,1.00000,None,10.0000,None,1000.00,None,Not directly available in the Naiades raw data...
93,Organic Micropollutants,Xylene-meta,Xylène-méta,1293,µg / L,0.100000,None,1.00000,None,10.0000,None,1000.00,None,None
94,Organic Micropollutants,Xylene-ortho,Xylène-ortho,1292,µg / L,0.100000,None,1.00000,None,10.0000,None,1000.00,None,None
95,Organic Micropollutants,Xylene-para,Xylène-para,1294,µg / L,0.100000,None,1.00000,None,10.0000,None,1000.00,None,None
96,Organic Micropollutants,p-octylphenol,p-octylphénols (mélange),6600,µg / L,0.010000,None,0.10000,None,1.0000,None,90.00,None,None
97,Organic Micropollutants,para-tert-Octylphenol,4-tert-Octylphenol,1959,µg / L,0.010000,None,0.10000,None,1.0000,None,90.00,None,None
98,PAH,Acenaphtene,Acénaphtène,1453,µg / L,0.070000,None,0.70000,None,160.0000,None,NaN,None,None
99,PAH,Acenaphtylene,Acénaphtylène,1622,µg / L,0.040000,None,0.40000,None,99.0000,None,NaN,None,None
100,PAH,Anthracene,Anthracène,1458,µg / L,0.009000,None,0.09000,None,21.0000,None,NaN,None,None
101,PAH,Benzo(a)anthracene,Benzo(a)anthracène,1082,µg / L,0.000500,None,0.00500,None,1.2000,None,NaN,None,None
102,PAH,Benzo(a)pyrene,Benzo(a)pyrène,1115,µg / L,0.000030,None,0.00030,None,0.0800,None,NaN,None,None
103,PAH,Benzo(b)fluoranthene,Benzo(b)fluoranthène,1116,µg / L,0.000100,None,0.00100,None,0.3000,None,NaN,None,None
104,PAH,"Benzo(g,h,i)perylene","Benzo(g,h,i)pérylène",1118,µg / L,0.000300,None,0.00300,None,0.6000,None,NaN,None,None
105,PAH,Benzo(k)fluoranthene,Benzo(k)fluoranthène,1117,µg / L,0.000300,None,0.00300,None,0.8000,None,NaN,None,None
106,PAH,Chrysene,Chrysène,1476,µg / L,0.000600,None,0.00600,None,1.5000,None,NaN,None,None
107,PAH,"Dibenzo(a,h)anthracene","Dibenzo(a,h)anthracène",1621,µg / L,0.000006,None,0.00006,None,0.0140,None,NaN,None,None
108,PAH,Fluoranthene,Fluoranthène,1191,µg / L,0.002400,None,0.02400,None,6.0000,None,NaN,None,None
109,PAH,Fluorene,Fluorène,1623,µg / L,0.030000,None,0.30000,None,77.0000,None,NaN,None,None
110,PAH,Indeno (123cd) pyrene,"Indéno(1,2,3-cd)pyrène",1204,µg / L,0.000160,None,0.00160,None,0.4000,None,NaN,None,None
111,PAH,Naphtalene,Naphtalène,1517,µg / L,0.190000,None,1.90000,None,460.0000,None,NaN,None,None
112,PAH,Phenanthrene,Phénanthrène,1524,µg / L,0.011000,None,0.11000,None,27.0000,None,NaN,None,None
113,PAH,Pyrene,Pyrène,1537,µg / L,0.002400,None,0.02400,None,6.0000,None,NaN,None,None
114,Pesticides,"2,4-D","2,4-D",1141,µg / L,1.000000,None,10.00000,None,100.0000,None,2700.00,None,None
115,Pesticides,"2,4-D-ester","2,4-D isopropyl ester",2872,µg / L,0.000010,None,0.00010,None,0.0010,None,0.10,None,None
116,Pesticides,"2,4-MCPA","2,4-MCPA",1212,µg / L,0.150000,None,1.50000,None,15.0000,None,620.00,None,None
117,Pesticides,Aclonifene,Aclonifène,1688,µg / L,0.007000,None,0.07000,None,0.7000,None,7.00,None,None
118,Pesticides,Alachlore,Alachlore,1101,µg / L,0.300000,None,3.00000,None,30.0000,None,1400.00,None,None
119,Pesticides,Aldicarbe,Aldicarbe,1102,µg / L,0.005000,None,0.05000,None,0.5000,None,50.00,None,None
120,Pesticides,Aldrine,Aldrine,1103,µg / L,0.001000,None,0.01000,None,0.1000,None,1.00,None,None
121,Pesticides,Aminotriazole,Aminotriazole,1105,µg / L,3.800000,None,38.00000,None,380.0000,None,3800.00,None,None
122,Pesticides,Atrazine,Atrazine,1107,µg / L,0.020000,None,0.20000,None,2.0000,None,20.00,None,None
123,Pesticides,Atrazine desethyl,Atrazine déséthyl,1108,µg / L,0.020000,None,0.20000,None,2.0000,None,20.00,None,None
124,Pesticides,Bentazone,Bentazone,1113,µg / L,19.000000,None,190.00000,None,1900.0000,None,62000.00,None,None
125,Pesticides,Bifenox,Bifénox,1119,µg / L,0.007000,None,0.07000,None,0.7000,None,65.00,None,None
126,Pesticides,Captane,Captane,1128,µg / L,0.170000,None,1.70000,None,17.0000,None,34.00,None,None
127,Pesticides,Carbendazime,Carbendazime,1129,µg / L,0.000700,None,0.00700,None,0.0700,None,7.00,None,None
128,Pesticides,Carbofuran,Carbofuran,1130,µg / L,0.001500,None,0.01500,None,0.1500,None,1.50,None,None
129,Pesticides,Chlorfenvinphos,Chlorfenvinphos,1464,µg / L,0.000300,None,0.00300,None,0.0300,None,0.30,None,None
130,Pesticides,Chlorothalonil,Chlorothalonil,1473,µg / L,0.000400,None,0.00400,None,0.0400,None,3.60,None,None
131,Pesticides,Chlorpyriphos-ethyl,Chlorpyriphos-éthyl,1083,µg / L,0.000050,None,0.00050,None,0.0050,None,0.05,None,None
132,Pesticides,Chlortoluron,Chlortoluron,1136,µg / L,0.100000,None,1.00000,None,10.0000,None,24.00,None,None
133,Pesticides,Cymoxanil,Cymoxanil,1139,µg / L,0.006000,None,0.06000,None,0.6000,None,60.00,None,None
134,Pesticides,Cyprodinil,Cyprodinil,1359,µg / L,0.010000,None,0.10000,None,1.0000,None,100.00,None,None
135,Pesticides,DDD 24',DDD 24',1143,µg / L,0.000600,None,0.00600,None,0.0600,None,0.60,None,None
136,Pesticides,DDD 44',DDD 44',1144,µg / L,0.000600,None,0.00600,None,0.0600,None,0.60,None,None
137,Pesticides,DDE 24',DDE 24',1145,µg / L,0.030000,None,0.30000,None,3.5000,None,30.00,None,None
138,Pesticides,DDE 44',DDE 44',1146,µg / L,0.030000,None,0.30000,None,3.5000,None,30.00,None,None
139,Pesticides,DDT 24',DDT 24',1147,µg / L,0.000200,None,0.00200,None,0.0200,None,0.20,None,None
140,Pesticides,DDT 44',DDT 44',None,µg / L,0.000200,None,0.00200,None,0.0200,None,0.20,None,Not in the original file of thresholds sent by...
141,Pesticides,Deltamethrine,Deltaméthrine,1149,µg / L,0.000020,None,0.00020,None,0.0020,None,0.02,None,None
142,Pesticides,Dicamba,Dicamba,1480,µg / L,0.390000,None,3.90000,None,39.0000,None,3900.00,None,None
143,Pesticides,Dichlorprop,Dichlorprop,1169,µg / L,0.050000,None,0.50000,None,5.0000,None,500.00,None,None
144,Pesticides,Dieldrine,Dieldrine,1173,µg / L,0.000500,None,0.00500,None,0.0500,None,0.50,None,None
145,Pesticides,Dinitrocresol,Dinitrocresol,1490,µg / L,0.070000,None,0.70000,None,7.0000,None,66.00,None,Called DNOC in the SEQ-Eau documents.
146,Pesticides,Dinoterbe,Dinoterbe,1176,µg / L,0.000300,None,0.00300,None,0.0300,None,0.30,None,None
147,Pesticides,Diquat,Diquat,1699,µg / L,0.020000,None,0.20000,None,2.0000,None,18.00,None,None
148,Pesticides,Diuron,Diuron,1177,µg / L,0.020000,None,0.20000,None,2.0000,None,20.00,None,None
149,Pesticides,Endosulfan,Endosulfan,1743,µg / L,0.002000,None,0.02000,None,0.2000,None,0.30,None,None
150,Pesticides,Endrine,Endrine,1181,µg / L,0.000300,None,0.00300,None,0.0300,None,0.30,None,None
151,Pesticides,Ethofumesate,Ethofumésate,1184,µg / L,0.080000,None,0.80000,None,8.0000,None,800.00,None,None
152,Pesticides,Fenpropidine,Fenpropidine,1700,µg / L,0.000600,None,0.00600,None,0.0600,None,6.00,None,None
153,Pesticides,Fenpropimorphe,Fenpropimorphe,1189,µg / L,0.220000,None,2.20000,None,22.0000,None,2200.00,None,None

In [8]:
import pandas as pd
import re

# 0) Harmonize names and types
em = envmeans.rename(columns={"Parametre_code":"Parameter_code",
                              "Parametre_label":"Parameter_label"}).copy()
em["Parameter_code"] = em["Parameter_code"].astype(str).str.strip()

ep = envparam.rename(columns={"Parameter_code":"Parameter_code"}).copy()
ep["Parameter_code"] = ep["Parameter_code"].astype(str).str.strip()

In [9]:
# 1) Long form of thresholds with band labels
bands = [
    ("HighGood",       "Threshold_HighGood",       "Note_HighGood"),
    ("GoodModerate",   "Threshold_GoodModerate",   "Note_GoodModerate"),
    ("ModeratePoor",   "Threshold_ModeratePoor",   "Note_ModeratePoor"),
    ("PoorBad",        "Threshold_PoorBad",        "Note_PoorBad"),
]
parts = []
keep_meta = ["Parameter_code","Pressure","Parameter_label_eng",
             "Parameter_label_fr","Parameter_unit"]
for band, thr_col, note_col in bands:
    t = ep[keep_meta + [thr_col, note_col]].rename(
        columns={thr_col:"Threshold", note_col:"Note"}
    ).copy()
    t["Band"] = band
    parts.append(t)

ep_long = pd.concat(parts, ignore_index=True)

In [10]:
# 2) Wide thresholds: one row per Parameter_code
def slug(x: str) -> str:
    x = "none" if pd.isna(x) or x=="" else str(x)
    return re.sub(r"\W+", "_", x.strip().lower())

ep_long["note_slug"] = ep_long["Note"].map(slug)
ep_long["colname"]   = "TH_" + ep_long["Band"] + "__" + ep_long["note_slug"]

thr_wide = (ep_long
            .pivot_table(index="Parameter_code",
                         columns="colname",
                         values="Threshold",
                         aggfunc="first"))

# choose one row of metadata per Parameter_code
meta = (ep_long
        .sort_values(["Parameter_code","Band"])  # stable pick
        .drop_duplicates("Parameter_code")
        [["Parameter_code","Pressure","Parameter_label_eng",
          "Parameter_label_fr","Parameter_unit"]]
        .set_index("Parameter_code"))

ep_wide = meta.join(thr_wide).reset_index()

In [11]:






# 3) Merge with envmeans (keeps 1 row per OP×parameter; no duplication from ep_wide)
env_merged = em.merge(ep_wide, on="Parameter_code", how="left")

# Optionally sanity-check
# env_merged.sample(5)
# env_merged.columns  # now includes TH_HighGood__*, TH_GoodModerate__*, etc.

In [12]:
env_merged

,CodeSite_SamplingOperations,SamplingOperations_code,Pressure_x,Parameter_code,Parameter_label,Mean1Y,Mean180Days,Mean90Days,Pressure_y,Parameter_label_eng,Parameter_label_fr,Parameter_unit,TH_GoodModerate__50_caco3_200_mg_l,TH_GoodModerate__caco3_200_mg_l,TH_GoodModerate__caco3_50_mg_l,TH_GoodModerate__maximum,TH_GoodModerate__minimum,TH_GoodModerate__none,TH_GoodModerate__ph_6_5,TH_HighGood__50_caco3_200_mg_l,TH_HighGood__caco3_200_mg_l,TH_HighGood__caco3_50_mg_l,TH_HighGood__maximum,TH_HighGood__minimum,TH_HighGood__none,TH_HighGood__ph_6_5,TH_ModeratePoor__50_caco3_200_mg_l,TH_ModeratePoor__caco3_200_mg_l,TH_ModeratePoor__caco3_50_mg_l,TH_ModeratePoor__maximum,TH_ModeratePoor__minimum,TH_ModeratePoor__none,TH_ModeratePoor__ph_6_5,TH_PoorBad__50_caco3_200_mg_l,TH_PoorBad__caco3_200_mg_l,TH_PoorBad__caco3_50_mg_l,TH_PoorBad__maximum,TH_PoorBad__minimum,TH_PoorBad__none,TH_PoorBad__ph_6_5
0,2000008,S02000008_20170703,Nitrogen compounds,1319,Azote Kjeldahl,0.335000,0.335000,0.33500,Nitrogen compounds,Kjeldahl nitrogen,Azote Kjeldahl,mg N / L,NaN,NaN,NaN,NaN,NaN,2.0000,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,4.000,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN
1,2000008,S02000008_20170703,Nitrogen compounds,1335,Ammonium,0.103333,0.103333,0.05000,Nitrogen compounds,Ammonium,Ammonium,mg NH4 / L,NaN,NaN,NaN,NaN,NaN,0.5000,NaN,NaN,NaN,NaN,NaN,NaN,0.10000,NaN,NaN,NaN,NaN,NaN,NaN,2.000,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
2,2000008,S02000008_20170703,Nitrogen compounds,1339,Nitrites,0.113333,0.113333,0.12000,Nitrogen compounds,Nitrites,Nitrites,mg NO2 / L,NaN,NaN,NaN,NaN,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,0.03000,NaN,NaN,NaN,NaN,NaN,NaN,0.500,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,2000008,S02000008_20170703,Nitrates,1340,Nitrates,18.600000,18.600000,16.00000,Nitrates,Nitrates,Nitrates,mg NO3 / L,NaN,NaN,NaN,NaN,NaN,10.0000,NaN,NaN,NaN,NaN,NaN,NaN,2.00000,NaN,NaN,NaN,NaN,NaN,NaN,25.000,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN
4,2000008,S02000008_20200708,Nitrogen compounds,1335,Ammonium,0.210000,0.210000,0.29000,Nitrogen compounds,Ammonium,Ammonium,mg NH4 / L,NaN,NaN,NaN,NaN,NaN,0.5000,NaN,NaN,NaN,NaN,NaN,NaN,0.10000,NaN,NaN,NaN,NaN,NaN,NaN,2.000,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3763898,6940940,S06940940_20230623,Pesticides,1699,Diquat,0.020000,0.020000,0.02000,Pesticides,Diquat,Diquat,µg / L,NaN,NaN,NaN,NaN,NaN,0.2000,NaN,NaN,NaN,NaN,NaN,NaN,0.02000,NaN,NaN,NaN,NaN,NaN,NaN,2.000,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN
3763899,6940940,S06940940_20230623,Pesticides,1700,Fenpropidine,0.006500,0.006500,0.00650,Pesticides,Fenpropidine,Fenpropidine,µg / L,NaN,NaN,NaN,NaN,NaN,0.0060,NaN,NaN,NaN,NaN,NaN,NaN,0.00060,NaN,NaN,NaN,NaN,NaN,NaN,0.060,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN
3763900,6940940,S06940940_20230623,Pesticides,1911,Imazaméthabenz-méthyl,0.006500,0.006500,0.00650,Pesticides,Imazamethabenz-methyl,Imazaméthabenz-méthyl,µg / L,NaN,NaN,NaN,NaN,NaN,120.0000,NaN,NaN,NaN,NaN,NaN,NaN,12.00000,NaN,NaN,NaN,NaN,NaN,NaN,1200.000,NaN,NaN,NaN,NaN,NaN,NaN,120000.0,NaN
3763901,6940940,S06940940_20230623,Pesticides,1975,fosetyl-aluminium,0.013500,0.013500,0.01350,Pesticides,fosetyl-aluminium,fosetyl-aluminium,µg / L,NaN,NaN,NaN,NaN,NaN,5.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.000,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,NaN
3763902,6940940,S06940940_20230623,Pesticides,2872,"2,4-D isopropyl ester",0.003350,0.003350,0.00335,Pesticides,"2,4-D-ester","2,4-D isopropyl ester",µg / L,NaN,NaN,NaN,NaN,NaN,0.0001,NaN,NaN,NaN,NaN,NaN,NaN,0.00001,NaN,NaN,NaN,NaN,NaN,NaN,0.001,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN

In [13]:
import numpy as np
import pandas as pd

env_merged = env_merged.rename(columns={"Pressure_x":"Pressure",
                                        "Pressure_y":"Pressure_meta"})

# pick the first non-null per band by preference
prefer = ["none","maximum","minimum","ph_6_5","caco3_50_mg_l","caco3_200_mg_l","50_caco3_200_mg_l"]

for band in ["HighGood","GoodModerate","ModeratePoor","PoorBad"]:
    cols = [c for k in prefer
              for c in [f"TH_{band}__{k}"] if c in env_merged.columns]
    env_merged[f"TH_{band}"] = env_merged[cols].bfill(axis=1).iloc[:,0]

# keep tidy set
keep = ["CodeSite_SamplingOperations","SamplingOperations_code",
        "Parameter_code","Parameter_label","Pressure","Parameter_unit",
        "Mean1Y","Mean180Days","Mean90Days",
        "TH_HighGood","TH_GoodModerate","TH_ModeratePoor","TH_PoorBad"]
env_tidy = env_merged[keep].copy()
env_tidy

,CodeSite_SamplingOperations,SamplingOperations_code,Parameter_code,Parameter_label,Pressure,Parameter_unit,Mean1Y,Mean180Days,Mean90Days,TH_HighGood,TH_GoodModerate,TH_ModeratePoor,TH_PoorBad
0,2000008,S02000008_20170703,1319,Azote Kjeldahl,Nitrogen compounds,mg N / L,0.335000,0.335000,0.33500,1.00000,2.0000,4.000,10.0
1,2000008,S02000008_20170703,1335,Ammonium,Nitrogen compounds,mg NH4 / L,0.103333,0.103333,0.05000,0.10000,0.5000,2.000,5.0
2,2000008,S02000008_20170703,1339,Nitrites,Nitrogen compounds,mg NO2 / L,0.113333,0.113333,0.12000,0.03000,0.3000,0.500,1.0
3,2000008,S02000008_20170703,1340,Nitrates,Nitrates,mg NO3 / L,18.600000,18.600000,16.00000,2.00000,10.0000,25.000,50.0
4,2000008,S02000008_20200708,1335,Ammonium,Nitrogen compounds,mg NH4 / L,0.210000,0.210000,0.29000,0.10000,0.5000,2.000,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3763898,6940940,S06940940_20230623,1699,Diquat,Pesticides,µg / L,0.020000,0.020000,0.02000,0.02000,0.2000,2.000,18.0
3763899,6940940,S06940940_20230623,1700,Fenpropidine,Pesticides,µg / L,0.006500,0.006500,0.00650,0.00060,0.0060,0.060,6.0
3763900,6940940,S06940940_20230623,1911,Imazaméthabenz-méthyl,Pesticides,µg / L,0.006500,0.006500,0.00650,12.00000,120.0000,1200.000,120000.0
3763901,6940940,S06940940_20230623,1975,fosetyl-aluminium,Pesticides,µg / L,0.013500,0.013500,0.01350,NaN,5.0000,50.000,5000.0
3763902,6940940,S06940940_20230623,2872,"2,4-D isopropyl ester",Pesticides,µg / L,0.003350,0.003350,0.00335,0.00001,0.0001,0.001,0.1

In [14]:
env_tidy.head(5)

,CodeSite_SamplingOperations,SamplingOperations_code,Parameter_code,Parameter_label,Pressure,Parameter_unit,Mean1Y,Mean180Days,Mean90Days,TH_HighGood,TH_GoodModerate,TH_ModeratePoor,TH_PoorBad
0,2000008,S02000008_20170703,1319,Azote Kjeldahl,Nitrogen compounds,mg N / L,0.335000,0.335000,0.335,1.00,2.0,4.0,10.0
1,2000008,S02000008_20170703,1335,Ammonium,Nitrogen compounds,mg NH4 / L,0.103333,0.103333,0.050,0.10,0.5,2.0,5.0
2,2000008,S02000008_20170703,1339,Nitrites,Nitrogen compounds,mg NO2 / L,0.113333,0.113333,0.120,0.03,0.3,0.5,1.0
3,2000008,S02000008_20170703,1340,Nitrates,Nitrates,mg NO3 / L,18.600000,18.600000,16.000,2.00,10.0,25.0,50.0
4,2000008,S02000008_20200708,1335,Ammonium,Nitrogen compounds,mg NH4 / L,0.210000,0.210000,0.290,0.10,0.5,2.0,5.0

In [15]:
import re
import pandas as pd

# env_tidy is your 12-col table shown in the message

def slug(s):
    s = str(s) if pd.notna(s) else ""
    return re.sub(r"\W+","_", s.strip().lower())

# stable, readable parameter key: "<code>_<label>"
env_tidy = env_tidy.copy()
env_tidy["param_key"] = (
    env_tidy["Parameter_code"].astype(str) + "_" + env_tidy["Parameter_label"].map(slug)
)

value_cols = ["Mean1Y","Mean180Days","Mean90Days",
              "TH_HighGood","TH_GoodModerate","TH_ModeratePoor","TH_PoorBad"]

In [16]:

# pivot: one row per SamplingOperations_code; columns = param_key × value
wide = (env_tidy
        .pivot_table(index="SamplingOperations_code",
                     columns="param_key",
                     values=value_cols,
                     aggfunc="first")      # use "mean"/"max" if duplicates exist
       )

# flatten MultiIndex columns to "param__metric"
wide.columns = [f"{p}__{m}" for m,p in wide.columns]
wide = wide.sort_index(axis=1)

In [17]:


# join to df (df can be indexed or not)
df_idx = df.set_index("SamplingOperations_code", drop=False)
final = df_idx.join(wide, how="left")
# final.index is SamplingOperations_code

In [18]:
final

                        SamplingOperations_code CodeSite_SamplingOperations  \
SamplingOperations_code
S02000008_20170703           S02000008_20170703                   S02000008
S02000008_20200708           S02000008_20200708                   S02000008
S02000010_20070906           S02000010_20070906                   S02000010
S02000010_20090721           S02000010_20090721                   S02000010
S02000010_20110723           S02000010_20110723                   S02000010
...                                         ...                         ...
S06940940_20100708           S06940940_20100708                   S06940940
S06940940_20230623           S06940940_20230623                   S06940940
S06960950_20160629           S06960950_20160629                   S06960950
S06960950_20180719           S06960950_20180719                   S06960950
S06970900_20150601           S06970900_20150601                   S06970900

                        Date_SamplingOperation  \
SamplingOperations_code
S02000008_20170703                  2017-07-03
S02000008_20200708                  2020-07-08
S02000010_20070906                  2007-09-06
S02000010_20090721                  2009-07-21
S02000010_20110723                  2011-07-23
...                                        ...
S06940940_20100708                  2010-07-08
S06940940_20230623                  2023-06-23
S06960950_20160629                  2016-06-29
S06960950_20180719                  2018-07-19
S06970900_20150601                  2015-06-01

                         TotalAbundance_SamplingOperation  Achaa01  Achac01  \
SamplingOperations_code
S02000008_20170703                                    405      NaN      NaN
S02000008_20200708                                    400      NaN      NaN
S02000010_20070906                                    400      NaN      NaN
S02000010_20090721                                    400      NaN      NaN
S02000010_20110723                                    398      NaN      NaN
...                                                   ...      ...      ...
S06940940_20100708                                    438      NaN      NaN
S06940940_20230623                                    408      NaN      NaN
S06960950_20160629                                    401      NaN      NaN
S06960950_20180719                                    416      NaN      NaN
S06970900_20150601                                    432      NaN      NaN

                         Achaf01    Achaf02  Achal01  Acham01  Achan01  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN      NaN      NaN
S02000008_20200708           NaN        NaN      NaN      NaN      NaN
S02000010_20070906           NaN        NaN      NaN      NaN      NaN
S02000010_20090721           NaN        NaN      NaN      NaN      NaN
S02000010_20110723           NaN        NaN      NaN      NaN      NaN
...                          ...        ...      ...      ...      ...
S06940940_20100708           NaN        NaN      NaN      NaN      NaN
S06940940_20230623           NaN        NaN      NaN      NaN      NaN
S06960950_20160629           NaN        NaN      NaN      NaN      NaN
S06960950_20180719           NaN  19.230769      NaN      NaN      NaN
S06970900_20150601           NaN        NaN      NaN      NaN      NaN

                         Achat01   Achat02  Achat03  Achba01  Achbi01  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN       NaN      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN  6.944444      NaN      NaN      NaN

                         Achbi02   Achbr01  Achca01  Achca02  Achca03  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN  2.283105      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN       NaN      NaN      NaN      NaN

                         Achca04  Achch01  Achcl01  Achco01  Achco02  Achco03  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achco04  Achcr01  Achcy01  Achda01  Achda02  Achde01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achde02  Achde03  Achdi01  Achdi02  Achdr01  Achel01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achen01    Acheu01  Achex01   Achex02  Achex03  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN       NaN      NaN
S02000008_20200708           NaN        NaN      NaN       NaN      NaN
S02000010_20070906           NaN   2.500000      NaN       NaN      NaN
S02000010_20090721           NaN  20.000000      5.0       NaN      NaN
S02000010_20110723           NaN        NaN      NaN       NaN      NaN
...                          ...        ...      ...       ...      ...
S06940940_20100708           NaN        NaN      NaN       NaN      NaN
S06940940_20230623           NaN   4.901961      NaN       NaN      NaN
S06960950_20160629           NaN        NaN      NaN  2.493766      NaN
S06960950_20180719           NaN        NaN      NaN       NaN      NaN
S06970900_20150601           NaN        NaN      NaN       NaN      NaN

                         Achfl01  Achfr01  Achfu01  Achge01  Achgr01  Achgr02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      2.5      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achgr03  Achha01  Achhe01  Achhi01  Achho01  Achho02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achho03  Achhu01  Achim01  Achim02  Achim03  Achin01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achin02  Achja01  Achja02  Achjo01  Achko01  Achkr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                          Achkr02  Achkr03  Achkr04  Achku01  Achla01  \
SamplingOperations_code
S02000008_20170703            NaN      NaN      NaN      NaN      NaN
S02000008_20200708       5.000000      NaN      NaN      NaN      NaN
S02000010_20070906            NaN      NaN      NaN      NaN      NaN
S02000010_20090721            NaN      NaN      NaN      NaN      NaN
S02000010_20110723            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06940940_20100708            NaN      NaN      NaN      NaN      NaN
S06940940_20230623       4.901961      NaN      NaN      NaN      NaN
S06960950_20160629            NaN      NaN      NaN      NaN      NaN
S06960950_20180719            NaN      NaN      NaN      NaN      NaN
S06970900_20150601            NaN      NaN      NaN      NaN      NaN

                           Achla02  Achla03  Achla04  Achla05  Achla06  \
SamplingOperations_code
S02000008_20170703        7.407407      NaN      NaN      NaN      NaN
S02000008_20200708        7.500000      NaN      NaN      NaN      NaN
S02000010_20070906             NaN      NaN      NaN      NaN      NaN
S02000010_20090721       15.000000      NaN      5.0      NaN      NaN
S02000010_20110723             NaN      NaN      NaN      NaN      NaN
...                            ...      ...      ...      ...      ...
S06940940_20100708             NaN      NaN      NaN      NaN      NaN
S06940940_20230623             NaN      NaN      NaN      NaN      NaN
S06960950_20160629             NaN      NaN      NaN      NaN      NaN
S06960950_20180719             NaN      NaN      NaN      NaN      NaN
S06970900_20150601             NaN      NaN      NaN      NaN      NaN

                         Achle01  Achle02  Achli01  Achli02  Achli03  Achli04  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achlo01  Achlu01  Achlu02  Achma01  Achmi01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN

                            Achmi02    Achmi03  Achmo01  Achmo02  Achna01  \
SamplingOperations_code
S02000008_20170703        88.888889        NaN      NaN      NaN      NaN
S02000008_20200708        12.500000        NaN      NaN      NaN      NaN
S02000010_20070906              NaN        NaN      NaN      NaN      NaN
S02000010_20090721       135.000000        NaN      NaN      NaN      NaN
S02000010_20110723        15.075377        NaN      NaN      NaN      NaN
...                             ...        ...      ...      ...      ...
S06940940_20100708         9.132420        NaN      NaN      NaN      NaN
S06940940_20230623       375.000000  14.705882      NaN      NaN      NaN
S06960950_20160629        87.281796        NaN      NaN      NaN      NaN
S06960950_20180719       298.076923        NaN      NaN      NaN      NaN
S06970900_20150601       173.611111        NaN      NaN      NaN      NaN

                         Achna02  Achne01  Achni01  Achno01  Achob01  Achpa01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpe01  Achpe02  Achpf01  Achpl01  Achpo01  Achpr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpr02  Achps01  Achps02  Achps03  Achps04  Achpu01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN

In [19]:
# if Unassessed in variable, change to NaN
final = final.replace("Unassessed", np.nan)
final

                        SamplingOperations_code CodeSite_SamplingOperations  \
SamplingOperations_code
S02000008_20170703           S02000008_20170703                   S02000008
S02000008_20200708           S02000008_20200708                   S02000008
S02000010_20070906           S02000010_20070906                   S02000010
S02000010_20090721           S02000010_20090721                   S02000010
S02000010_20110723           S02000010_20110723                   S02000010
...                                         ...                         ...
S06940940_20100708           S06940940_20100708                   S06940940
S06940940_20230623           S06940940_20230623                   S06940940
S06960950_20160629           S06960950_20160629                   S06960950
S06960950_20180719           S06960950_20180719                   S06960950
S06970900_20150601           S06970900_20150601                   S06970900

                        Date_SamplingOperation  \
SamplingOperations_code
S02000008_20170703                  2017-07-03
S02000008_20200708                  2020-07-08
S02000010_20070906                  2007-09-06
S02000010_20090721                  2009-07-21
S02000010_20110723                  2011-07-23
...                                        ...
S06940940_20100708                  2010-07-08
S06940940_20230623                  2023-06-23
S06960950_20160629                  2016-06-29
S06960950_20180719                  2018-07-19
S06970900_20150601                  2015-06-01

                         TotalAbundance_SamplingOperation  Achaa01  Achac01  \
SamplingOperations_code
S02000008_20170703                                    405      NaN      NaN
S02000008_20200708                                    400      NaN      NaN
S02000010_20070906                                    400      NaN      NaN
S02000010_20090721                                    400      NaN      NaN
S02000010_20110723                                    398      NaN      NaN
...                                                   ...      ...      ...
S06940940_20100708                                    438      NaN      NaN
S06940940_20230623                                    408      NaN      NaN
S06960950_20160629                                    401      NaN      NaN
S06960950_20180719                                    416      NaN      NaN
S06970900_20150601                                    432      NaN      NaN

                         Achaf01    Achaf02  Achal01  Acham01  Achan01  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN      NaN      NaN
S02000008_20200708           NaN        NaN      NaN      NaN      NaN
S02000010_20070906           NaN        NaN      NaN      NaN      NaN
S02000010_20090721           NaN        NaN      NaN      NaN      NaN
S02000010_20110723           NaN        NaN      NaN      NaN      NaN
...                          ...        ...      ...      ...      ...
S06940940_20100708           NaN        NaN      NaN      NaN      NaN
S06940940_20230623           NaN        NaN      NaN      NaN      NaN
S06960950_20160629           NaN        NaN      NaN      NaN      NaN
S06960950_20180719           NaN  19.230769      NaN      NaN      NaN
S06970900_20150601           NaN        NaN      NaN      NaN      NaN

                         Achat01   Achat02  Achat03  Achba01  Achbi01  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN       NaN      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN  6.944444      NaN      NaN      NaN

                         Achbi02   Achbr01  Achca01  Achca02  Achca03  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN  2.283105      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN       NaN      NaN      NaN      NaN

                         Achca04  Achch01  Achcl01  Achco01  Achco02  Achco03  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achco04  Achcr01  Achcy01  Achda01  Achda02  Achde01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achde02  Achde03  Achdi01  Achdi02  Achdr01  Achel01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achen01    Acheu01  Achex01   Achex02  Achex03  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN       NaN      NaN
S02000008_20200708           NaN        NaN      NaN       NaN      NaN
S02000010_20070906           NaN   2.500000      NaN       NaN      NaN
S02000010_20090721           NaN  20.000000      5.0       NaN      NaN
S02000010_20110723           NaN        NaN      NaN       NaN      NaN
...                          ...        ...      ...       ...      ...
S06940940_20100708           NaN        NaN      NaN       NaN      NaN
S06940940_20230623           NaN   4.901961      NaN       NaN      NaN
S06960950_20160629           NaN        NaN      NaN  2.493766      NaN
S06960950_20180719           NaN        NaN      NaN       NaN      NaN
S06970900_20150601           NaN        NaN      NaN       NaN      NaN

                         Achfl01  Achfr01  Achfu01  Achge01  Achgr01  Achgr02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      2.5      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achgr03  Achha01  Achhe01  Achhi01  Achho01  Achho02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achho03  Achhu01  Achim01  Achim02  Achim03  Achin01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achin02  Achja01  Achja02  Achjo01  Achko01  Achkr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                          Achkr02  Achkr03  Achkr04  Achku01  Achla01  \
SamplingOperations_code
S02000008_20170703            NaN      NaN      NaN      NaN      NaN
S02000008_20200708       5.000000      NaN      NaN      NaN      NaN
S02000010_20070906            NaN      NaN      NaN      NaN      NaN
S02000010_20090721            NaN      NaN      NaN      NaN      NaN
S02000010_20110723            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06940940_20100708            NaN      NaN      NaN      NaN      NaN
S06940940_20230623       4.901961      NaN      NaN      NaN      NaN
S06960950_20160629            NaN      NaN      NaN      NaN      NaN
S06960950_20180719            NaN      NaN      NaN      NaN      NaN
S06970900_20150601            NaN      NaN      NaN      NaN      NaN

                           Achla02  Achla03  Achla04  Achla05  Achla06  \
SamplingOperations_code
S02000008_20170703        7.407407      NaN      NaN      NaN      NaN
S02000008_20200708        7.500000      NaN      NaN      NaN      NaN
S02000010_20070906             NaN      NaN      NaN      NaN      NaN
S02000010_20090721       15.000000      NaN      5.0      NaN      NaN
S02000010_20110723             NaN      NaN      NaN      NaN      NaN
...                            ...      ...      ...      ...      ...
S06940940_20100708             NaN      NaN      NaN      NaN      NaN
S06940940_20230623             NaN      NaN      NaN      NaN      NaN
S06960950_20160629             NaN      NaN      NaN      NaN      NaN
S06960950_20180719             NaN      NaN      NaN      NaN      NaN
S06970900_20150601             NaN      NaN      NaN      NaN      NaN

                         Achle01  Achle02  Achli01  Achli02  Achli03  Achli04  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achlo01  Achlu01  Achlu02  Achma01  Achmi01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN

                            Achmi02    Achmi03  Achmo01  Achmo02  Achna01  \
SamplingOperations_code
S02000008_20170703        88.888889        NaN      NaN      NaN      NaN
S02000008_20200708        12.500000        NaN      NaN      NaN      NaN
S02000010_20070906              NaN        NaN      NaN      NaN      NaN
S02000010_20090721       135.000000        NaN      NaN      NaN      NaN
S02000010_20110723        15.075377        NaN      NaN      NaN      NaN
...                             ...        ...      ...      ...      ...
S06940940_20100708         9.132420        NaN      NaN      NaN      NaN
S06940940_20230623       375.000000  14.705882      NaN      NaN      NaN
S06960950_20160629        87.281796        NaN      NaN      NaN      NaN
S06960950_20180719       298.076923        NaN      NaN      NaN      NaN
S06970900_20150601       173.611111        NaN      NaN      NaN      NaN

                         Achna02  Achne01  Achni01  Achno01  Achob01  Achpa01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpe01  Achpe02  Achpf01  Achpl01  Achpo01  Achpr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpr02  Achps01  Achps02  Achps03  Achps04  Achpu01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN

In [20]:
final.to_parquet(os.path.join(path, "biggest.parquet"), index=False)