In [17]:
# Data manipulation and numerical computation
import numpy as np
import pandas as pd
import os

# pandas all columns display
pd.set_option('display.max_columns', None)

# Load data

In [18]:
# before: path = "../../data/processed/"
path = "data/processed"
dfs = {}

# read 03_CLEAN_COMPLETE_DF.parquet
df1 = pd.read_parquet(os.path.join(path, "taxones_pressure_epm_train.parquet"))
df2 = pd.read_parquet(os.path.join(path, "taxones_pressure_epm_predict.parquet"))
df = pd.concat([df1, df2], ignore_index=True)
# keep the odds from the dataframe

# change unassessed values to NaN
df = df.replace("Unassessed", np.nan)
df = df.replace("None", np.nan)

# index SamplingOperations_code
# df = df.set_index('SamplingOperations_code')


# sort by Date_SamplingOperation
df = df.sort_values(by='Date_SamplingOperation')

# df = df[['CodeSite_SamplingOperations_x', 'Date_SamplingOperation', 'IBD', 'Longitude_Lambert93', 'Latitude_Lambert93']]
# DROP HERlvl2Code	Altitude Longitude_Lambert93	Latitude_Lambert93	Watershed	CodeDepartement	HERlvl1Code
# df = df.drop(columns=['HERlvl2Code', 'HERlvl2Name', 'HERlvl1Name', 'Altitude','Longitude_Lambert93','Latitude_Lambert93','Watershed','CodeDepartement', 'Date_SamplingOperation'])

In [20]:

end_idx = df.columns.get_loc("Watershed")
new_cols = df.columns[: end_idx + 1]

df = df.loc[:, new_cols].copy()

df

      SamplingOperations_code CodeSite_SamplingOperations_x  \
2703       S02115200_20070702                     S02115200
33984      S05218450_20070709                     S05218450
33929      S05217350_20070709                     S05217350
48228      S05235850_20070709                     S05235850
35408      S05234290_20070709                     S05234290
...                       ...                           ...
42720      S06580577_20230907                     S06580577
35760      S06001284_20230907                     S06001284
35783      S06001533_20230907                     S06001533
38878      S06137040_20231011                     S06137040
38873      S06137014_20231011                     S06137014

      Date_SamplingOperation  TotalAbundance_SamplingOperation  Achaa01  \
2703              2007-07-02                               400      NaN
33984             2007-07-09                               400      NaN
33929             2007-07-09                               400      NaN
48228             2007-07-09                               400      NaN
35408             2007-07-09                               400      NaN
...                      ...                               ...      ...
42720             2023-09-07                               426      NaN
35760             2023-09-07                               421      NaN
35783             2023-09-07                               401      NaN
38878             2023-10-11                               400      NaN
38873             2023-10-11                               405      NaN

       Achac01  Achaf01  Achaf02  Achal01  Acham01  Achan01  Achat01  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN     12.5      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      2.5      NaN      NaN      NaN      NaN      NaN
35408      NaN      7.5      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN

         Achat02  Achat03  Achba01  Achbi01  Achbi02  Achbr01  Achca01  \
2703         NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984        NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929   5.000000      NaN      NaN      NaN      NaN      NaN      NaN
48228  42.500000      NaN      NaN      NaN      NaN      NaN      NaN
35408  20.000000      NaN      NaN      NaN      NaN      NaN      NaN
...          ...      ...      ...      ...      ...      ...      ...
42720   4.694836      NaN      NaN      NaN      NaN      NaN      NaN
35760        NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783  14.962594      NaN      NaN      NaN      NaN      NaN      NaN
38878  42.500000      NaN      NaN      NaN      NaN      NaN      NaN
38873  69.135802      NaN      NaN      NaN      NaN      NaN      NaN

       Achca02  Achca03  Achca04  Achch01  Achcl01  Achco01  Achco02  Achco03  \
2703       NaN      NaN      NaN      NaN      NaN      NaN     12.5      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achco04  Achcr01  Achcy01  Achda01  Achda02  Achde01  Achde02  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      2.5      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN

         Achde03  Achdi01  Achdi02  Achdr01  Achel01  Achen01    Acheu01  \
2703         NaN      NaN      NaN      NaN      NaN      NaN   2.500000
33984        NaN      NaN      NaN      NaN      NaN      NaN        NaN
33929        NaN      NaN      NaN      NaN      NaN      NaN        NaN
48228        NaN      NaN      NaN      NaN      NaN      NaN        NaN
35408        NaN      NaN      NaN      NaN      NaN      NaN  42.500000
...          ...      ...      ...      ...      ...      ...        ...
42720        NaN      NaN      NaN      NaN      NaN      NaN   7.042254
35760        NaN      NaN      NaN      NaN      NaN      NaN        NaN
35783        NaN      NaN      NaN      NaN      NaN      NaN   2.493766
38878  40.000000      NaN      NaN      NaN      NaN      NaN        NaN
38873   9.876543      NaN      NaN      NaN      NaN      NaN        NaN

       Achex01  Achex02  Achex03  Achfl01  Achfr01  Achfu01  Achge01  Achgr01  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achgr02  Achgr03  Achha01  Achhe01  Achhi01  Achho01  Achho02  Achho03  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achhu01  Achim01  Achim02  Achim03  Achin01  Achin02  Achja01  Achja02  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achjo01  Achko01  Achkr01  Achkr02  Achkr03  Achkr04  Achku01  Achla01  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

         Achla02  Achla03    Achla04  Achla05  Achla06  Achle01  Achle02  \
2703   37.500000      NaN   5.000000      NaN      NaN      NaN      NaN
33984        NaN      NaN        NaN      NaN      NaN      NaN      NaN
33929        NaN      NaN        NaN      NaN      NaN      NaN      NaN
48228        NaN      NaN        NaN      NaN      NaN      NaN      NaN
35408  22.500000      NaN   5.000000      NaN      NaN      NaN      NaN
...          ...      ...        ...      ...      ...      ...      ...
42720  18.779343      NaN  21.126761      NaN      NaN      NaN      NaN
35760   4.750594      NaN        NaN      NaN      NaN      NaN      NaN
35783   2.493766      NaN   2.493766      NaN      NaN      NaN      NaN
38878        NaN      NaN        NaN      NaN      NaN      NaN      NaN
38873        NaN      NaN        NaN      NaN      NaN      NaN      NaN

       Achli01  Achli02     Achli03  Achli04  Achlo01  Achlu01  Achlu02  \
2703       NaN      NaN    2.500000      NaN      NaN      NaN      NaN
33984      NaN      NaN   15.000000      NaN      NaN      NaN      NaN
33929      NaN      NaN    7.500000      NaN      NaN      NaN      NaN
48228      NaN      NaN  215.000000      NaN      NaN      NaN      NaN
35408      NaN      NaN         NaN      NaN      NaN      NaN      NaN
...        ...      ...         ...      ...      ...      ...      ...
42720      NaN      NaN         NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN         NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN         NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN         NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN    7.407407      NaN      NaN      NaN      NaN

       Achma01  Achmi01     Achmi02    Achmi03  Achmo01  Achmo02  Achna01  \
2703       NaN      NaN   55.000000        NaN      NaN      NaN      NaN
33984      NaN      NaN  612.500000        NaN      NaN      NaN      NaN
33929      NaN      NaN  162.500000        NaN      NaN      NaN      NaN
48228      NaN      NaN  237.500000        NaN      NaN      NaN      NaN
35408      NaN      NaN  365.000000        NaN      NaN      NaN      NaN
...        ...      ...         ...        ...      ...      ...      ...
42720      NaN      NaN         NaN  32.863850      NaN      NaN      NaN
35760      NaN      NaN         NaN   4.750594      NaN      NaN      NaN
35783      NaN      NaN         NaN  24.937656      NaN      NaN      NaN
38878      NaN      NaN  240.000000  20.000000      NaN      NaN      NaN
38873      NaN      NaN  308.641975        NaN      NaN      NaN      NaN

       Achna02  Achne01  Achni01  Achno01  Achob01  Achpa01  Achpe01  Achpe02  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achpf01  Achpl01  Achpo01  Achpr01  Achpr02  Achps01  Achps02  Achps03  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achps04  Achpu01     Achpy01  Achre01  Achri01  Achro01  Achro02  \
2703       NaN      NaN         NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN  287.500000      NaN      NaN      NaN      NaN
33929      NaN      NaN  775.000000      NaN      NaN      NaN      NaN
48228      NaN      NaN   40.000000      NaN      NaN      NaN      NaN
35408      NaN      NaN   10.000000      NaN      NaN      NaN      NaN
...        ...      ...         ...      ...      ...      ...      ...
42720      NaN      NaN         NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN   40.380048      NaN      NaN      NaN      NaN
35783      NaN      NaN   19.950125      NaN      NaN      NaN      NaN
38878      NaN      NaN  307.500000      NaN      NaN      NaN      NaN
38873      NaN      NaN  444.444444      NaN      NaN      NaN      NaN

       Achro03  Achro04  Achru01  Achru02  Achsa01  Achsc01  Achse01  Achse02  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achsi01  Achst01  Achst02  Achst03  Achst04    Achsu01  Achsu02  \
2703       NaN      NaN      NaN      NaN      NaN        NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN        NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN        NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN  10.000000      NaN
35408      NaN      NaN      NaN      NaN      NaN        NaN      NaN
...        ...      ...      ...      ...      ...        ...      ...
42720      NaN      NaN      NaN      NaN      NaN        NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN        NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN   4.987531      NaN
38878      NaN      NaN      NaN      NaN      NaN        NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN        NaN      NaN

       Achsu03  Achsu04  Achsu05  Achsu06  Achsu07  Achte01  Achth01  Achtr01  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achtr02  Achtr03  Achtu01  Achzh01  Achzi01  Actde01  Actno01  Actro01  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Actse01  Actsp01  Actsu01  Actvu01  Adlaq01  Adlba01  Adlbr01  Adlbr02  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33929      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
48228      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35408      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
42720      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35760      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
35783      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38878      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38873      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Adlmi01  Adlmu01  Adlmu02  Adlpa01  Adlsu01  Afrre01  Ampae01  Ampaf01  \
2703       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
33984      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

In [4]:
df = df.drop(columns=['CodeSite_SamplingOperations_x', 'Watershed'])

In [5]:
# know the NaN values of each column in percentage and sort descending
vals = df.isna().sum() / len(df) * 100
vals = vals.sort_values(ascending=True)

for val in vals.index:
    print(f"{val}: {vals[val]:.2f}%")

SamplingOperations_code: 0.00%
Date_SamplingOperation: 0.00%
TotalAbundance_SamplingOperation: 0.00%
Latitude_Lambert93: 0.00%
Longitude_Lambert93: 0.00%
Achmi02: 11.25%
Amppe02: 20.36%
Coceu01: 21.66%
Selni01: 22.73%
Navcr09: 23.38%
Nitdi04: 30.00%
Vibtr01: 37.24%
Rhoab01: 37.93%
Navpe05: 39.49%
Achla02: 44.67%
Navgr01: 46.39%
Gompa06: 48.02%
Nitpa01: 49.06%
Melva01: 53.73%
Reisi01: 54.46%
Gommi05: 57.06%
Nitso01: 58.20%
Navan05: 58.69%
Cocpl01: 59.06%
Navsa03: 61.60%
Plala02: 61.61%
Navre04: 63.47%
Gompu02: 63.57%
Navla04: 63.61%
Nitfo01: 64.52%
Cocli01: 69.60%
Ampin02: 71.29%
Nitam01: 71.50%
Cycps01: 72.45%
Cocpe01: 73.08%
Achpy01: 73.90%
Navcr05: 74.10%
Navsu07: 74.24%
Nitpa02: 75.55%
Navca07: 75.82%
Cymsi01: 76.55%
Nitin02: 76.61%
Calae01: 76.95%
Nitde03: 77.26%
Navsu09: 77.86%
Plesc01: 78.62%
Cymve01: 79.30%
Cycme02: 80.31%
Exiva01: 80.42%
Acheu01: 80.57%
Gomol04: 81.69%
Achri01: 81.70%
Nitre01: 81.71%
Selsa02: 82.35%
Cymmi01: 82.95%
Navve03: 82.98%
Frave01: 83.07%
Nitso04: 83.77%
Diavu01: 84.11%
Navge02: 84.40%
Achla04: 84.47%
Fruco01: 85.12%
Synde01: 85.22%
Ampin01: 85.33%
Fragr01: 85.48%
Reiun01: 85.84%
Navmo05: 86.10%
Surla01: 86.12%
Synul01: 86.60%
Nitli03: 86.62%
Navoc01: 87.09%
Achge01: 87.11%
Selat01: 87.17%
Selpu01: 87.42%
Achsu03: 87.44%
Nitco07: 87.90%
Geiac01: 88.15%
Achde03: 88.20%
Karcl01: 88.63%
Achco02: 89.16%
Surbr01: 89.17%
Hipca02: 89.21%
Crasu01: 89.43%
Gomin06: 89.59%
Achst03: 89.80%
Achat02: 90.02%
Aulam01: 90.08%
Achsu01: 90.23%
Navtr05: 90.28%
Calba01: 90.37%
Navsu03: 90.69%
Suran01: 91.01%
Navsu08: 91.01%
Achli03: 91.18%
Gomte02: 91.25%
Ampov01: 91.40%
Nitsu09: 91.61%
Cymex01: 91.62%
Gomel01: 91.73%
Gomex01: 92.15%
Stein01: 92.26%
Cycdu01: 92.28%
Nitme01: 92.29%
Nitsu01: 92.31%
Navcr10: 92.35%
Navle02: 92.37%
Stapi02: 92.39%
Dipse01: 92.50%
Psebr01: 92.51%
Navrh02: 92.67%
Gyrat01: 92.79%
Nitar01: 92.94%
Navcr04: 93.04%
Nitca03: 93.22%
Navca08: 93.32%
Frape01: 93.35%
Cycat01: 93.59%
Lutgo01: 93.60%
Achob01: 93.88%
Navca11: 93.89%
Navsi04: 93.90%
Achdr01: 93.97%
Achca02: 93.99%
Navmi09: 94.00%
Achth01: 94.00%
Merci01: 94.07%
Dente01: 94.12%
Navat02: 94.17%
Ampat01: 94.30%
Navco05: 94.49%
Gombo02: 94.52%
Plaro04: 94.58%
Navvi01: 94.64%
Melpu01: 94.68%
Nitac04: 94.70%
Nitpu04: 94.78%
Fruvu01: 94.85%
Gomcu02: 94.88%
Steha01: 94.97%
Plaro03: 95.15%
Nitac05: 95.19%
Frapa01: 95.26%
Achmi03: 95.26%
Gommi03: 95.28%
Encmi04: 95.28%
Navsc04: 95.31%
Achaf02: 95.54%
Nitgr02: 95.56%
Tryap01: 95.59%
Nitan02: 95.67%
Adlmi01: 95.69%
Frabr01: 95.71%
Cymaf02: 95.76%
Cymco01: 95.96%
Fraco01: 96.00%
Panoc01: 96.07%
Himmi01: 96.08%
Aulgr01: 96.20%
Stete01: 96.23%
Gomrh01: 96.24%
Tryde01: 96.24%
Fraru01: 96.37%
Navme04: 96.44%
Cymtu01: 96.44%
Pleno01: 96.52%
Plaap01: 96.56%
Navdi04: 96.60%
Nithe01: 96.63%
Tabfl01: 96.68%
Achda02: 96.73%
Navde03: 96.75%
Achho03: 96.76%
Diame01: 96.87%
Psepa01: 96.93%
Humco01: 96.95%
Frala02: 96.96%
Gyrac01: 96.97%
Navte01: 96.99%
Navra01: 97.01%
Staov01: 97.04%
Goman02: 97.13%
Navvi02: 97.19%
Achla06: 97.19%
Encsu03: 97.19%
Nitso02: 97.19%
Navex02: 97.22%
Sursu02: 97.23%
Fraca04: 97.24%
Nitte02: 97.30%
Gommi01: 97.30%
Plaob01: 97.31%
Cocne03: 97.37%
Cycme01: 97.38%
Achde02: 97.41%
Navac02: 97.43%
Eolrh01: 97.46%
Nitlo01: 97.50%
Navmo08: 97.50%
Nitfr02: 97.52%
Navci01: 97.55%
Gomli05: 97.55%
Stath01: 97.61%
Monpr01: 97.62%
Eolco01: 97.63%
Halmo01: 97.63%
Bacpa01: 97.64%
Navob06: 97.65%
Parpr01: 97.67%
Diamo01: 97.68%
Eunim01: 97.69%
Falpy01: 97.70%
Fraex01: 97.71%
Achla03: 97.73%
Navob04: 97.75%
Achkr02: 97.79%
Plami02: 97.79%
Prepr01: 97.80%
Pladu01: 97.84%
Ampma01: 97.87%
Navev01: 97.87%
Ampve01: 97.87%
Naver01: 97.91%
Psahe01: 97.99%
Astfo01: 97.99%
Nitpe03: 98.00%
Diaeh01: 98.02%
Achgr02: 98.03%
Stasm01: 98.03%
Encmi03: 98.03%
Nitmi01: 98.04%
Cocps02: 98.05%
Cycdi01: 98.08%
Nitla03: 98.09%
Nitin04: 98.09%
Achda01: 98.10%
Hombu01: 98.10%
Navar02: 98.14%
Psabi01: 98.15%
Fravi02: 98.15%
Navsy01: 98.15%
Merco01: 98.15%
Navpr03: 98.17%
Pratr01: 98.17%
Nupla01: 98.17%
Navca10: 98.18%
Navam05: 98.19%
Micpo01: 98.23%
Himex01: 98.23%
Pleob01: 98.24%
Navhe04: 98.25%
Panco02: 98.26%
Cycst01: 98.26%
Punra01: 98.27%
Eunin01: 98.28%
Gomca02: 98.28%
Mayin01: 98.28%
Navps02: 98.29%
Cymaf01: 98.30%
Navps01: 98.30%
Frare01: 98.31%
Cymtu03: 98.31%
Frapa02: 98.34%
Navmu06: 98.34%
Melgr01: 98.35%
Navno02: 98.38%
Karpl01: 98.39%
Nitag02: 98.42%
Plaba01: 98.42%
Cycwo01: 98.44%
Cochu01: 98.45%
Achex01: 98.46%
Nitdr01: 98.46%
Goman05: 98.52%
Frami03: 98.52%
Surmi01: 98.52%
Nitfi02: 98.53%
Ampmo01: 98.54%
Tryku01: 98.54%
Pleku01: 98.55%
Navtr07: 98.57%
Melte01: 98.59%
Cymne03: 98.59%
Navco06: 98.60%
Cymso01: 98.62%
Navva03: 98.62%
Gomla05: 98.63%
Adlbr02: 98.64%
Navar04: 98.64%
Encsi02: 98.65%
Achhu01: 98.66%
Calfo01: 98.66%
Denta01: 98.68%
Cocdi01: 98.68%
Nithu01: 98.69%
Eunte01: 98.69%
Amppe01: 98.69%
Selrh01: 98.69%
Nitfr01: 98.69%
Synac02: 98.69%
Fraca02: 98.69%
Nitsu05: 98.69%
Navrh01: 98.70%
Navag03: 98.70%
Synac01: 98.71%
Stakr01: 98.72%
Nitbe01: 98.72%
Tryco02: 98.73%
Gomtr02: 98.73%
Fruve01: 98.73%
Tryle01: 98.77%
Nitha02: 98.77%
Placl01: 98.77%
Stetr01: 98.78%
Nitre02: 98.78%
Ulnul01: 98.78%
Gomac03: 98.78%
Tabfa01: 98.79%
Psaob01: 98.79%
Cymex02: 98.81%
Pseso01: 98.82%
Navan02: 98.82%
Encca01: 98.82%
Navpe06: 98.84%
Encne01: 98.85%
Achko01: 98.85%
Dippa02: 98.86%
Pulob01: 98.86%
Dipma01: 98.86%
Conwe01: 98.87%
Gomit01: 98.88%
Pseal01: 98.88%
Diaco01: 98.90%
Cocpa01: 98.91%
Navjo01: 98.91%
Nantr01: 98.91%
Navut01: 98.93%
Achfu01: 98.93%
Nitsi02: 98.93%
Tryan02: 98.94%
Synbi02: 98.95%
Stepa01: 98.95%
Hanar01: 98.95%
Eunbo03: 98.96%
Frane04: 98.96%
Gommi02: 98.96%
Cycmi01: 98.96%
Hanam01: 98.97%
Surro01: 98.98%
Selja01: 98.98%
Navmu02: 98.99%
Eunbi05: 98.99%
Nitad01: 98.99%
Stapa01: 99.00%
Steve01: 99.00%
Navba03: 99.00%
Frapi01: 99.00%
Pseme01: 99.01%
Navas01: 99.01%
Achja02: 99.01%
Nitco02: 99.02%
Ctepu01: 99.02%
Achca04: 99.03%
Frael01: 99.04%
Surhe01: 99.04%
Pinma04: 99.04%
Achcr01: 99.06%
Nitso03: 99.06%
Fracr01: 99.07%
Achre01: 99.08%
Navha02: 99.09%
Frabi01: 99.09%
Navsu15: 99.09%
Dipel01: 99.10%
Aulsu01: 99.10%
Cymel01: 99.11%
Frabi03: 99.12%
Pse(a01: 99.12%
Cymre01: 99.12%
Gomho02: 99.13%
Gomca01: 99.14%
Gomva02: 99.15%
Nittr02: 99.16%
Frara01: 99.16%
Tryca01: 99.17%
Navst05: 99.17%
Cocne02: 99.17%
Frate01: 99.17%
Nitdu01: 99.18%
Homco01: 99.18%
Navmu03: 99.19%
Nittu01: 99.19%
Achex02: 99.20%
Gomgr01: 99.20%
Selut01: 99.22%
Navme06: 99.22%
Gomcl02: 99.22%
Prepr02: 99.22%
Navtr06: 99.23%
Eunsu02: 99.23%
Navde08: 99.24%
Frape04: 99.25%
Nitli01: 99.25%
Achzh01: 99.25%
Melar01: 99.26%
Gomac02: 99.26%
Navsl01: 99.26%
Glotr01: 99.27%
Bible01: 99.27%
Panco01: 99.27%
Dorko01: 99.27%
Dipkr01: 99.27%
Navin05: 99.27%
Pinsu04: 99.28%
Linra01: 99.28%
Navhi01: 99.28%
Nitpa08: 99.28%
Calsi01: 99.29%
Dippe01: 99.29%
Selcr01: 99.29%
Nitva02: 99.29%
Nitag01: 99.29%
Fraau01: 99.30%
Brane01: 99.30%
Selps01: 99.31%
Gompr03: 99.31%
Gomcy01: 99.32%
Cymsu06: 99.32%
Cymna01: 99.32%
Nitdi03: 99.33%
Nitpa03: 99.33%
Achru01: 99.34%
Frame02: 99.34%
Ampve02: 99.35%
Navra02: 99.36%
Tryan01: 99.36%
Nitan01: 99.37%
Fraca01: 99.37%
Pinsi04: 99.37%
Cycth01: 99.38%
Odomu01: 99.38%
Plape03: 99.40%
Navco01: 99.41%
Nitwu01: 99.41%
Achco04: 99.42%
Nitge01: 99.42%
Navro02: 99.42%
Cymap01: 99.43%
Navfo02: 99.43%
Pinob01: 99.44%
Nitpu01: 99.44%
Micgr01: 99.45%
Nitpu03: 99.45%
Psave01: 99.46%
Gomer01: 99.46%
Fruer01: 99.46%
Navno03: 99.47%
Dipfo01: 99.47%
Lutfr01: 99.48%
Gomme01: 99.48%
Denku01: 99.48%
Navhu02: 99.48%
Dippr01: 99.49%
Achsu06: 99.49%
Eunar03: 99.49%
Navse05: 99.49%
Gomin03: 99.50%
Staco02: 99.50%
Synmi01: 99.50%
Navdi03: 99.51%
Stapi01: 99.51%
Surte02: 99.51%
Gomps01: 99.51%
Punov01: 99.51%
Cyccy01: 99.51%
Brane02: 99.51%
Navmi07: 99.52%
Fraca03: 99.52%
Selsc01: 99.52%
Synbi01: 99.52%
Perfi01: 99.52%
Eunpe01: 99.53%
Nitde06: 99.53%
Navsc07: 99.54%
Adlsu01: 99.55%
Rosan01: 99.55%
Fraae01: 99.56%
Navcr01: 99.56%
Cosla02: 99.56%
Navmo09: 99.56%
Delde02: 99.57%
Navco03: 99.57%
Humpe01: 99.58%
Dipca02: 99.58%
Navol01: 99.58%
Stave01: 99.58%
Pinmi01: 99.58%
Gomau01: 99.58%
Navlu02: 99.58%
Gomol03: 99.59%
Navbu01: 99.59%
Frane02: 99.59%
Gyrsc01: 99.60%
Nitbr02: 99.60%
Nitau01: 99.60%
Skape01: 99.60%
Hipne01: 99.60%
Fraam01: 99.60%
Navra04: 99.61%
Pinpe03: 99.61%
Plasa01: 99.61%
Frurh01: 99.61%
Navin06: 99.61%
Neial01: 99.61%
Plela01: 99.61%
Navro01: 99.62%
Achro02: 99.62%
Gomsu03: 99.62%
Navin04: 99.62%
Tabve01: 99.63%
Brabr01: 99.63%
Eunpa02: 99.63%
Neidu01: 99.64%
Eucla01: 99.64%
Navme03: 99.64%
Achaf01: 99.64%
Nitcl01: 99.64%
Stede01: 99.64%
Navsu12: 99.64%
Navmi02: 99.65%
Cycco01: 99.65%
Nitla01: 99.65%
Hanab01: 99.65%
Halno01: 99.65%
Navex01: 99.65%
Psaco01: 99.65%
Synru01: 99.65%
Navhu01: 99.66%
Thaps01: 99.66%
Frusa01: 99.66%
Plain01: 99.66%
Surcr01: 99.66%
Encce01: 99.66%
Scemu01: 99.66%
Cymam01: 99.67%
Pundi01: 99.67%
Diate01: 99.67%
Densu01: 99.67%
Achpf01: 99.67%
Panwu01: 99.67%
Navum01: 99.68%
Steme01: 99.68%
Frucu01: 99.68%
Achro04: 99.68%
Surbi02: 99.68%
Melmu01: 99.69%
Eunrh01: 99.69%
Encau01: 99.69%
Nitfr03: 99.69%
Selsa01: 99.69%
Ampme01: 99.69%
Goman04: 99.69%
Pinbo01: 99.69%
Cympe02: 99.70%
Navps09: 99.70%
Surli02: 99.70%
Auldi01: 99.70%
Cymku01: 99.70%
Aulte01: 99.71%
Navsu05: 99.71%
Pinsc01: 99.71%
Plael01: 99.71%
Eunsu03: 99.71%
Navdi10: 99.71%
Navop03: 99.71%
Plabi01: 99.71%
Selra01: 99.71%
Surli01: 99.71%
Navam07: 99.71%
Eunfo01: 99.72%
Gomau02: 99.72%
Nitsi01: 99.72%
Panpo01: 99.72%
Gomsa01: 99.72%
Aulsu02: 99.73%
Gommi04: 99.73%
Nitpu02: 99.73%
Goman06: 99.73%
Nupwe01: 99.73%
Navig01: 99.73%
Navsp02: 99.73%
Nitgr01: 99.73%
Humsc01: 99.73%
Achho01: 99.73%
Staco01: 99.74%
Encvu01: 99.74%
Psaac01: 99.74%
Surte01: 99.74%
Lutve01: 99.74%
Calsc01: 99.74%
Achma01: 99.74%
Frade01: 99.74%
Cymne02: 99.74%
Gomca04: 99.74%
Navva05: 99.74%
Navps06: 99.74%
Gomla04: 99.75%
Neibi01: 99.75%
Navco07: 99.75%
Staan01: 99.75%
Neibi02: 99.75%
Niteu01: 99.76%
Stase01: 99.76%
Plaha01: 99.76%
Gomaf01: 99.76%
Diabi01: 99.76%
Hipru01: 99.76%
Frade02: 99.76%
Navve06: 99.76%
Berru01: 99.76%
Frana01: 99.76%
Luthl01: 99.77%
Ampmi02: 99.77%
Navam02: 99.77%
Navcr07: 99.77%
Achtr03: 99.78%
Pinov01: 99.78%
Eunfo02: 99.78%
Cymhu01: 99.78%
Gomut01: 99.78%
Didge01: 99.78%
Selsu02: 99.78%
Navvi04: 99.78%
Trybr01: 99.78%
Navta02: 99.78%
Navcr02: 99.79%
Pinsu07: 99.79%
Lemex01: 99.79%
Navvi03: 99.79%
Plawe01: 99.79%
Cocle01: 99.79%
Frale01: 99.79%
Navig02: 99.79%
Cymtu02: 99.79%
Hiplu01: 99.80%
Nittr01: 99.80%
Navba02: 99.80%
Capcr01: 99.80%
Neibi03: 99.80%
Achca03: 99.80%
Plapl01: 99.80%
Navtr03: 99.80%
Gomcl01: 99.80%
Navpr01: 99.80%
Pande01: 99.80%
Fruad01: 99.81%
Plare01: 99.81%
Navsa01: 99.81%
Achsa01: 99.81%
Navmo01: 99.81%
Navlu01: 99.81%
Navni01: 99.82%
Gomte01: 99.82%
Gomol02: 99.82%
Surbi01: 99.83%
Navle05: 99.83%
Pendi01: 99.83%
Gomli02: 99.83%
Ampno01: 99.83%
Enckr01: 99.83%
Plaps01: 99.83%
Achpu01: 99.84%
Episo01: 99.84%
Eunar01: 99.84%
Actno01: 99.84%
Cymsu07: 99.84%
Achli01: 99.84%
Gomdr01: 99.84%
Navmo04: 99.84%
Stebr01: 99.84%
Brapr01: 99.84%
Navhe02: 99.84%
Surun01: 99.84%
Navtr02: 99.84%
Gomva03: 99.85%
Selab01: 99.85%
Selco01: 99.85%
Nitvi02: 99.85%
Gomac01: 99.85%
Tabta01: 99.85%
Achgr03: 99.85%
Gomhe01: 99.85%
Frari01: 99.85%
Witsy01: 99.85%
Exipu01: 99.85%
Synso01: 99.85%
Selau01: 99.85%
Navte02: 99.85%
Achco01: 99.85%
Navci02: 99.85%
Nanso01: 99.86%
Gomoc01: 99.86%
Selve01: 99.86%
Bacul01: 99.86%
Navre02: 99.86%
Gomgr02: 99.86%
Pinac03: 99.86%
Navmi05: 99.86%
Adlba01: 99.86%
Gompa01: 99.86%
Nupsi01: 99.86%
Neiaf01: 99.87%
Navbr02: 99.87%
Pinel01: 99.87%
Synda01: 99.87%
Thage01: 99.87%
Humbr01: 99.87%
Navwi03: 99.87%
Breke01: 99.87%
Gomco05: 99.87%
Opema01: 99.87%
Nupru01: 99.87%
Navre05: 99.87%
Lutac01: 99.87%
Encbo01: 99.87%
Navcu01: 99.87%
Nitob01: 99.87%
Navca09: 99.87%
Navpe04: 99.87%
Navop01: 99.87%
Gomco04: 99.87%
Frasa02: 99.87%
Eunsi01: 99.87%
Surde01: 99.87%
Pinlu01: 99.87%
Cymtr02: 99.87%
Stamu01: 99.87%
Hippu01: 99.88%
Synfa01: 99.88%
Navaq01: 99.88%
Chamu01: 99.88%
Tabfe01: 99.88%
Frane01: 99.88%
Navph02: 99.88%
Achan01: 99.88%
Cymhe01: 99.88%
Selar02: 99.88%
Navja01: 99.88%
Eunin02: 99.88%
Navsi01: 99.88%
Delal01: 99.88%
Mickr01: 99.88%
Placl02: 99.88%
Selca01: 99.88%
Punpr01: 99.88%
Navph01: 99.88%
Navcl03: 99.88%
Sella01: 99.88%
Stene01: 99.88%
Navse01: 99.88%
Navan01: 99.88%
Frala03: 99.89%
Achba01: 99.89%
Aulni01: 99.89%
Fraam02: 99.89%
Nitam04: 99.89%
Cymvu01: 99.89%
Nitho02: 99.89%
Euncu01: 99.89%
Cymas01: 99.89%
Fraac01: 99.89%
Gomps02: 99.89%
Achne01: 99.89%
Achpe02: 99.89%
Fruwe01: 99.89%
Nitth02: 99.89%
Cymcy01: 99.90%
Aulbr01: 99.90%
Diapr01: 99.90%
Cycde02: 99.90%
Cymne01: 99.90%
Fraol01: 99.90%
Navla02: 99.90%
Hipar01: 99.90%
Gombr02: 99.90%
Selro01: 99.90%
Stagr01: 99.90%
Cymtr01: 99.90%
Pinmo03: 99.90%
Gomvi03: 99.90%
Cymbe01: 99.90%
Navsu02: 99.90%
Navps10: 99.90%
Cymsu03: 99.90%
Cymsu05: 99.90%
Navso01: 99.90%
Eunbo01: 99.90%
Encal02: 99.90%
Navdi01: 99.90%
Navwe01: 99.90%
Pinap01: 99.90%
Navst04: 99.91%
Selmu01: 99.91%
Cymcu01: 99.91%
Psepa02: 99.91%
Plaab01: 99.91%
Navri04: 99.91%
Ampco01: 99.91%
Plava02: 99.91%
Cymko01: 99.91%
Gomun01: 99.91%
Psaal01: 99.91%
Calal01: 99.91%
Entpa01: 99.91%
Nitde05: 99.91%
Melpf01: 99.91%
Achbr01: 99.91%
Frape03: 99.91%
Cymma01: 99.91%
Pinac04: 99.91%
Chafa01: 99.91%
Navad01: 99.91%
Kolsu01: 99.91%
Navla03: 99.91%
Plana01: 99.92%
Navsa02: 99.92%
Acham01: 99.92%
Navla05: 99.92%
Pingi01: 99.92%
Navru01: 99.92%
Achen01: 99.92%
Nupim02: 99.92%
Rhami01: 99.92%
Nital02: 99.92%
Nitps02: 99.92%
Himfa01: 99.92%
Hipsu01: 99.92%
Nitre03: 99.92%
Encta01: 99.92%
Navpa01: 99.92%
Synde02: 99.92%
Nitli04: 99.92%
Surov01: 99.92%
Aulit01: 99.92%
Navcu02: 99.92%
Gomro01: 99.92%
Plapa01: 99.92%
Achsi01: 99.92%
Surst01: 99.92%
Halol01: 99.92%
Stagr02: 99.92%
Psesm01: 99.93%
Neiam01: 99.93%
Navmi01: 99.93%
Nitvi01: 99.93%
Dipti01: 99.93%
Himso01: 99.93%
Panro01: 99.93%
Eolcr01: 99.93%
Navat01: 99.93%
Diaga01: 99.93%
Navde01: 99.93%
Hipco02: 99.93%
Navva04: 99.93%
Camhi01: 99.93%
Surbr02: 99.93%
Stare01: 99.94%
Pinsa01: 99.94%
Navpa02: 99.94%
Pinsi01: 99.94%
Nitna01: 99.94%
Navpr02: 99.94%
Dipob01: 99.94%
Navsu20: 99.94%
Ampmi01: 99.94%
Gruta01: 99.94%
Nitve02: 99.94%
Pingr02: 99.94%
Cymfl01: 99.94%
Navli01: 99.94%
Anosp01: 99.94%
Navac01: 99.94%
Achla05: 99.94%
Frasa01: 99.94%
Stadu02: 99.94%
Pinsu09: 99.94%
Plalu01: 99.94%
Navtu02: 99.94%
Euntr02: 99.94%
Achjo01: 99.94%
Navrh03: 99.94%
Nitbr01: 99.94%
Pinin02: 99.94%
Rhogi01: 99.94%
Achbi02: 99.94%
Stasi01: 99.95%
Navel04: 99.95%
Ampsu03: 99.95%
Gomoa01: 99.95%
Nitab01: 99.95%
Pinis01: 99.95%
Pinpa02: 99.95%
Frani01: 99.95%
Cycir01: 99.95%
Achbi01: 99.95%
Eunpr01: 99.95%
Navau01: 99.95%
Parmi01: 99.95%
Bacci01: 99.95%
Achsu07: 99.95%
Navlo02: 99.95%
Frage01: 99.95%
Neilo01: 99.95%
Cympe01: 99.95%
Navwi01: 99.95%
Falom01: 99.95%
Suram01: 99.95%
Linba01: 99.95%
Gomcl03: 99.95%
Navsu13: 99.95%
Fraan01: 99.95%
Neide01: 99.95%
Staac02: 99.95%
Navsu10: 99.95%
Selbo01: 99.95%
Eunna01: 99.95%
Gomvi01: 99.95%
Pinvi02: 99.95%
Eunps01: 99.95%
Gomag01: 99.95%
Achlu01: 99.95%
Aulva01: 99.95%
Gomlo01: 99.95%
Staol02: 99.95%
Navam06: 99.95%
Neibi04: 99.95%
Staph01: 99.95%
Nupne01: 99.96%
Psecl01: 99.96%
Anoin01: 99.96%
Eunte02: 99.96%
Nitra01: 99.96%
Ampli01: 99.96%
Achhi01: 99.96%
Dipca01: 99.96%
Surro02: 99.96%
Stabe01: 99.96%
Pinmu01: 99.96%
Gompl01: 99.96%
Encgr01: 99.96%
Gomba01: 99.96%
Nital03: 99.96%
Fraha01: 99.96%
Trysu01: 99.96%
Gomde02: 99.96%
Fraro01: 99.96%
Reifo01: 99.96%
Achli02: 99.96%
Staol01: 99.96%
Cravi01: 99.96%
Stale02: 99.96%
Nitsu03: 99.96%
Nitro02: 99.96%
Navja02: 99.96%
Falcr01: 99.96%
Eunva01: 99.96%
Cymme01: 99.96%
Eunsu04: 99.96%
Gomli04: 99.96%
Ampol01: 99.96%
Navmu07: 99.96%
Cocme01: 99.96%
Navny01: 99.96%
Nitel01: 99.96%
Navla06: 99.96%
Psabr01: 99.96%
Pinsu05: 99.96%
Plewo01: 99.96%
Navve05: 99.96%
Halco01: 99.96%
Eunar02: 99.96%
Navho01: 99.96%
Epigo01: 99.96%
Surbi03: 99.96%
Fraaq01: 99.96%
Plaga01: 99.96%
Tryco01: 99.96%
Psepo01: 99.96%
Navmi04: 99.96%
Aulal01: 99.96%
Ampne02: 99.96%
Navli03: 99.96%
Pinan01: 99.96%
Diahy01: 99.96%
Gomko01: 99.96%
Achat03: 99.96%
Navgo01: 99.96%
Encfa01: 99.96%
Gomfo01: 99.96%
Ampps01: 99.96%
Halho01: 99.96%
Selch01: 99.96%
Navde05: 99.96%
Pinvi01: 99.96%
Selbl01: 99.96%
Navmi03: 99.96%
Plaro01: 99.96%
Gompr02: 99.96%
Nitfl01: 99.96%
Cymsi03: 99.96%
Mayas01: 99.96%
Nitpe04: 99.96%
Synbe01: 99.96%
Selps03: 99.97%
Gomin04: 99.97%
Pinno02: 99.97%
Stapr01: 99.97%
Encsi01: 99.97%
Nitps01: 99.97%
Navsa07: 99.97%
Plapu01: 99.97%
Fruap01: 99.97%
Pinma03: 99.97%
Eolbe01: 99.97%
Plaoe01: 99.97%
Euntr01: 99.97%
Linpr01: 99.97%
Nitva01: 99.97%
Hydtr01: 99.97%
Pinte01: 99.97%
Frabo01: 99.97%
Stane02: 99.97%
Cycsc01: 99.97%
Plapo01: 99.97%
Nitma01: 99.97%
Nitco01: 99.97%
Navsu01: 99.97%
Surca01: 99.97%
Anoga01: 99.97%
Rhova01: 99.97%
Nitca02: 99.97%
Navta01: 99.97%
Fruma01: 99.97%
Achna02: 99.97%
Seltr01: 99.97%
Achac01: 99.97%
Dipmo01: 99.97%
Halbu01: 99.97%
Cymhe02: 99.97%
Nitba04: 99.97%
Navsu11: 99.97%
Achja01: 99.97%
Navab02: 99.97%
Achmo01: 99.97%
Rhaam01: 99.97%
Navin01: 99.97%
Navme05: 99.97%
Navfr01: 99.97%
Placu01: 99.97%
Karob01: 99.97%
Adlmu02: 99.97%
Psami01: 99.97%
Pladi01: 99.97%
Achle02: 99.97%
Encge01: 99.97%
Eunbi01: 99.97%
Gomsu05: 99.97%
Gomsp02: 99.97%
Frane03: 99.97%
Dipmi01: 99.97%
Pinsu03: 99.97%
Achde01: 99.97%
Eunny01: 99.97%
Navri03: 99.97%
Navsc03: 99.97%
Navna01: 99.97%
Navla01: 99.97%
Pinsa02: 99.97%
Calae02: 99.97%
Epiop01: 99.97%
Eucdi01: 99.97%
Fralo01: 99.97%
Achro01: 99.97%
Frafr01: 99.97%
Cymfr01: 99.97%
Seldi01: 99.97%
Navob03: 99.97%
Encho01: 99.97%
Dipps01: 99.97%
Encel01: 99.97%
Neipr01: 99.97%
Pinac02: 99.97%
Achpo01: 99.97%
Frate02: 99.97%
Ulngr01: 99.97%
Opeol01: 99.97%
Aulis01: 99.98%
Steal01: 99.98%
Navsa06: 99.98%
Plape02: 99.98%
Gomvi02: 99.98%
Psero01: 99.98%
Mayca02: 99.98%
Navca05: 99.98%
Diphi01: 99.98%
Humga01: 99.98%
Triex01: 99.98%
Pinbi01: 99.98%
Chabe01: 99.98%
Pinna01: 99.98%
Navmi08: 99.98%
Eunis01: 99.98%
Frahe01: 99.98%
Pinsc02: 99.98%
Schla01: 99.98%
Nitfi01: 99.98%
Encbr01: 99.98%
Synla01: 99.98%
Navbi03: 99.98%
Navve04: 99.98%
Cycst03: 99.98%
Frukr01: 99.98%
Gomze01: 99.98%
Cymla01: 99.98%
Fradi01: 99.98%
Eolar01: 99.98%
Achps03: 99.98%
Synmo01: 99.98%
Pungl01: 99.98%
Amppa01: 99.98%
Cymsu01: 99.98%
Nitpe01: 99.98%
Synca01: 99.98%
Fruam01: 99.98%
Plahi01: 99.98%
Gompa04: 99.98%
Thadu01: 99.98%
Stale03: 99.98%
Frain01: 99.98%
Nupde01: 99.98%
Eunbi02: 99.98%
Eunci02: 99.98%
Ampei01: 99.98%
Achte01: 99.98%
Eungl01: 99.98%
Navja03: 99.98%
Navsc01: 99.98%
Kobpa01: 99.98%
Karam01: 99.98%
Eunsu01: 99.98%
Nitve01: 99.98%
Nitcu03: 99.98%
Staex01: 99.98%
Plavi01: 99.98%
Synpl01: 99.98%
Achru02: 99.98%
Frapa03: 99.98%
Cycop01: 99.98%
Navha07: 99.98%
Geita01: 99.98%
Stale04: 99.98%
Chaal01: 99.98%
Navps11: 99.98%
Nitac03: 99.98%
Goman03: 99.98%
Gomam01: 99.98%
Synfl01: 99.98%
Navbr05: 99.98%
Achal01: 99.98%
Sursu01: 99.98%
Achzi01: 99.98%
Surst02: 99.98%
Stasp01: 99.98%
Navsc02: 99.98%
Nupca01: 99.98%
Hanco01: 99.98%
Gomva01: 99.98%
Navps12: 99.98%
Staag01: 99.98%
Sella02: 99.98%
Navha06: 99.98%
Navhe01: 99.98%
Parsu01: 99.98%
Navgi01: 99.98%
Navve07: 99.98%
Navmo06: 99.98%
Eunur01: 99.98%
Neicu01: 99.98%
Plaro02: 99.98%
Epire01: 99.98%
Eundi01: 99.98%
Eunbi03: 99.98%
Pinst01: 99.98%
Encne02: 99.98%
Nitae01: 99.98%
Achla01: 99.98%
Achps04: 99.98%
Nitgi01: 99.98%
Eunme01: 99.98%
Eunmi01: 99.98%
Achin02: 99.98%
Achpa01: 99.98%
Navmi06: 99.98%
Gomna01: 99.98%
Selpa01: 99.98%
Odone01: 99.98%
Nitae02: 99.98%
Pinst02: 99.98%
Navdi06: 99.98%
Stain01: 99.98%
Anetu01: 99.98%
Navme01: 99.98%
Eunpa05: 99.98%
Eolch01: 99.98%
Navma03: 99.98%
Disin01: 99.98%
Masla01: 99.98%
Ampex01: 99.98%
Calpu01: 99.98%
Navob05: 99.98%
Eunen01: 99.98%
Plaga03: 99.98%
Navar01: 99.98%
Achmi01: 99.98%
Synfa02: 99.98%
Eolin01: 99.98%
Eunpa04: 99.98%
Grusi01: 99.98%
Actse01: 99.98%
Stero01: 99.98%
Navsi02: 99.98%
Thavi01: 99.98%
Navir02: 99.99%
Frame01: 99.99%
Navku01: 99.99%
Epitu01: 99.99%
Navze01: 99.99%
Navma02: 99.99%
Fraat01: 99.99%
Plede01: 99.99%
Hipol01: 99.99%
Psaab01: 99.99%
Densu02: 99.99%
Navne02: 99.99%
Pinla01: 99.99%
Pinla02: 99.99%

In [6]:
# keep the columns with less than 99% NaN 
df = df.loc[:, df.isnull().mean() < 0.99]

In [7]:
# know the NaN values of each column in percentage and sort descending
vals = df.isna().sum() / len(df) * 100
vals = vals.sort_values(ascending=True)

for val in vals.index:
    print(f"{val}: {vals[val]:.2f}%")

SamplingOperations_code: 0.00%
TotalAbundance_SamplingOperation: 0.00%
Longitude_Lambert93: 0.00%
Latitude_Lambert93: 0.00%
Date_SamplingOperation: 0.00%
Achmi02: 11.25%
Amppe02: 20.36%
Coceu01: 21.66%
Selni01: 22.73%
Navcr09: 23.38%
Nitdi04: 30.00%
Vibtr01: 37.24%
Rhoab01: 37.93%
Navpe05: 39.49%
Achla02: 44.67%
Navgr01: 46.39%
Gompa06: 48.02%
Nitpa01: 49.06%
Melva01: 53.73%
Reisi01: 54.46%
Gommi05: 57.06%
Nitso01: 58.20%
Navan05: 58.69%
Cocpl01: 59.06%
Navsa03: 61.60%
Plala02: 61.61%
Navre04: 63.47%
Gompu02: 63.57%
Navla04: 63.61%
Nitfo01: 64.52%
Cocli01: 69.60%
Ampin02: 71.29%
Nitam01: 71.50%
Cycps01: 72.45%
Cocpe01: 73.08%
Achpy01: 73.90%
Navcr05: 74.10%
Navsu07: 74.24%
Nitpa02: 75.55%
Navca07: 75.82%
Cymsi01: 76.55%
Nitin02: 76.61%
Calae01: 76.95%
Nitde03: 77.26%
Navsu09: 77.86%
Plesc01: 78.62%
Cymve01: 79.30%
Cycme02: 80.31%
Exiva01: 80.42%
Acheu01: 80.57%
Gomol04: 81.69%
Achri01: 81.70%
Nitre01: 81.71%
Selsa02: 82.35%
Cymmi01: 82.95%
Navve03: 82.98%
Frave01: 83.07%
Nitso04: 83.77%
Diavu01: 84.11%
Navge02: 84.40%
Achla04: 84.47%
Fruco01: 85.12%
Synde01: 85.22%
Ampin01: 85.33%
Fragr01: 85.48%
Reiun01: 85.84%
Navmo05: 86.10%
Surla01: 86.12%
Synul01: 86.60%
Nitli03: 86.62%
Navoc01: 87.09%
Achge01: 87.11%
Selat01: 87.17%
Selpu01: 87.42%
Achsu03: 87.44%
Nitco07: 87.90%
Geiac01: 88.15%
Achde03: 88.20%
Karcl01: 88.63%
Achco02: 89.16%
Surbr01: 89.17%
Hipca02: 89.21%
Crasu01: 89.43%
Gomin06: 89.59%
Achst03: 89.80%
Achat02: 90.02%
Aulam01: 90.08%
Achsu01: 90.23%
Navtr05: 90.28%
Calba01: 90.37%
Navsu03: 90.69%
Suran01: 91.01%
Navsu08: 91.01%
Achli03: 91.18%
Gomte02: 91.25%
Ampov01: 91.40%
Nitsu09: 91.61%
Cymex01: 91.62%
Gomel01: 91.73%
Gomex01: 92.15%
Stein01: 92.26%
Cycdu01: 92.28%
Nitme01: 92.29%
Nitsu01: 92.31%
Navcr10: 92.35%
Navle02: 92.37%
Stapi02: 92.39%
Dipse01: 92.50%
Psebr01: 92.51%
Navrh02: 92.67%
Gyrat01: 92.79%
Nitar01: 92.94%
Navcr04: 93.04%
Nitca03: 93.22%
Navca08: 93.32%
Frape01: 93.35%
Cycat01: 93.59%
Lutgo01: 93.60%
Achob01: 93.88%
Navca11: 93.89%
Navsi04: 93.90%
Achdr01: 93.97%
Achca02: 93.99%
Navmi09: 94.00%
Achth01: 94.00%
Merci01: 94.07%
Dente01: 94.12%
Navat02: 94.17%
Ampat01: 94.30%
Navco05: 94.49%
Gombo02: 94.52%
Plaro04: 94.58%
Navvi01: 94.64%
Melpu01: 94.68%
Nitac04: 94.70%
Nitpu04: 94.78%
Fruvu01: 94.85%
Gomcu02: 94.88%
Steha01: 94.97%
Plaro03: 95.15%
Nitac05: 95.19%
Frapa01: 95.26%
Achmi03: 95.26%
Gommi03: 95.28%
Encmi04: 95.28%
Navsc04: 95.31%
Achaf02: 95.54%
Nitgr02: 95.56%
Tryap01: 95.59%
Nitan02: 95.67%
Adlmi01: 95.69%
Frabr01: 95.71%
Cymaf02: 95.76%
Cymco01: 95.96%
Fraco01: 96.00%
Panoc01: 96.07%
Himmi01: 96.08%
Aulgr01: 96.20%
Stete01: 96.23%
Gomrh01: 96.24%
Tryde01: 96.24%
Fraru01: 96.37%
Navme04: 96.44%
Cymtu01: 96.44%
Pleno01: 96.52%
Plaap01: 96.56%
Navdi04: 96.60%
Nithe01: 96.63%
Tabfl01: 96.68%
Achda02: 96.73%
Navde03: 96.75%
Achho03: 96.76%
Diame01: 96.87%
Psepa01: 96.93%
Humco01: 96.95%
Frala02: 96.96%
Gyrac01: 96.97%
Navte01: 96.99%
Navra01: 97.01%
Staov01: 97.04%
Goman02: 97.13%
Achla06: 97.19%
Navvi02: 97.19%
Encsu03: 97.19%
Nitso02: 97.19%
Navex02: 97.22%
Sursu02: 97.23%
Fraca04: 97.24%
Nitte02: 97.30%
Gommi01: 97.30%
Plaob01: 97.31%
Cocne03: 97.37%
Cycme01: 97.38%
Achde02: 97.41%
Navac02: 97.43%
Eolrh01: 97.46%
Nitlo01: 97.50%
Navmo08: 97.50%
Nitfr02: 97.52%
Navci01: 97.55%
Gomli05: 97.55%
Stath01: 97.61%
Monpr01: 97.62%
Eolco01: 97.63%
Halmo01: 97.63%
Bacpa01: 97.64%
Navob06: 97.65%
Parpr01: 97.67%
Diamo01: 97.68%
Eunim01: 97.69%
Falpy01: 97.70%
Fraex01: 97.71%
Achla03: 97.73%
Navob04: 97.75%
Achkr02: 97.79%
Plami02: 97.79%
Prepr01: 97.80%
Pladu01: 97.84%
Ampma01: 97.87%
Navev01: 97.87%
Ampve01: 97.87%
Naver01: 97.91%
Psahe01: 97.99%
Astfo01: 97.99%
Nitpe03: 98.00%
Diaeh01: 98.02%
Achgr02: 98.03%
Stasm01: 98.03%
Encmi03: 98.03%
Nitmi01: 98.04%
Cocps02: 98.05%
Cycdi01: 98.08%
Nitla03: 98.09%
Nitin04: 98.09%
Achda01: 98.10%
Hombu01: 98.10%
Navar02: 98.14%
Psabi01: 98.15%
Fravi02: 98.15%
Merco01: 98.15%
Navsy01: 98.15%
Navpr03: 98.17%
Pratr01: 98.17%
Nupla01: 98.17%
Navca10: 98.18%
Navam05: 98.19%
Micpo01: 98.23%
Himex01: 98.23%
Pleob01: 98.24%
Navhe04: 98.25%
Panco02: 98.26%
Cycst01: 98.26%
Punra01: 98.27%
Eunin01: 98.28%
Gomca02: 98.28%
Mayin01: 98.28%
Navps02: 98.29%
Cymaf01: 98.30%
Navps01: 98.30%
Frare01: 98.31%
Cymtu03: 98.31%
Frapa02: 98.34%
Navmu06: 98.34%
Melgr01: 98.35%
Navno02: 98.38%
Karpl01: 98.39%
Nitag02: 98.42%
Plaba01: 98.42%
Cycwo01: 98.44%
Cochu01: 98.45%
Achex01: 98.46%
Nitdr01: 98.46%
Goman05: 98.52%
Surmi01: 98.52%
Frami03: 98.52%
Nitfi02: 98.53%
Ampmo01: 98.54%
Tryku01: 98.54%
Pleku01: 98.55%
Navtr07: 98.57%
Melte01: 98.59%
Cymne03: 98.59%
Navco06: 98.60%
Cymso01: 98.62%
Navva03: 98.62%
Gomla05: 98.63%
Adlbr02: 98.64%
Navar04: 98.64%
Encsi02: 98.65%
Achhu01: 98.66%
Calfo01: 98.66%
Denta01: 98.68%
Cocdi01: 98.68%
Amppe01: 98.69%
Eunte01: 98.69%
Nithu01: 98.69%
Selrh01: 98.69%
Synac02: 98.69%
Nitfr01: 98.69%
Fraca02: 98.69%
Nitsu05: 98.69%
Navrh01: 98.70%
Navag03: 98.70%
Synac01: 98.71%
Stakr01: 98.72%
Nitbe01: 98.72%
Gomtr02: 98.73%
Tryco02: 98.73%
Fruve01: 98.73%
Nitha02: 98.77%
Tryle01: 98.77%
Placl01: 98.77%
Stetr01: 98.78%
Nitre02: 98.78%
Ulnul01: 98.78%
Gomac03: 98.78%
Tabfa01: 98.79%
Psaob01: 98.79%
Cymex02: 98.81%
Pseso01: 98.82%
Navan02: 98.82%
Encca01: 98.82%
Navpe06: 98.84%
Encne01: 98.85%
Achko01: 98.85%
Pulob01: 98.86%
Dippa02: 98.86%
Dipma01: 98.86%
Conwe01: 98.87%
Gomit01: 98.88%
Pseal01: 98.88%
Diaco01: 98.90%
Cocpa01: 98.91%
Navjo01: 98.91%
Nantr01: 98.91%
Achfu01: 98.93%
Navut01: 98.93%
Nitsi02: 98.93%
Tryan02: 98.94%
Synbi02: 98.95%
Stepa01: 98.95%
Hanar01: 98.95%
Frane04: 98.96%
Eunbo03: 98.96%
Gommi02: 98.96%
Cycmi01: 98.96%
Hanam01: 98.97%
Surro01: 98.98%
Selja01: 98.98%
Navmu02: 98.99%
Eunbi05: 98.99%
Nitad01: 98.99%
Stapa01: 99.00%

In [8]:
# display some rows
pd.set_option("display.max_columns", 8)

df

,SamplingOperations_code,Date_SamplingOperation,TotalAbundance_SamplingOperation,Achaf02,...,Ulnul01,Vibtr01,Longitude_Lambert93,Latitude_Lambert93
2703,S02115200_20070702,2007-07-02,400,NaN,...,NaN,NaN,902925.0,6941112.0
33984,S05218450_20070709,2007-07-09,400,NaN,...,NaN,NaN,442885.0,6199880.0
33929,S05217350_20070709,2007-07-09,400,NaN,...,NaN,NaN,442250.0,6218040.0
48228,S05235850_20070709,2007-07-09,400,NaN,...,NaN,2.500000,463192.0,6225280.0
35408,S05234290_20070709,2007-07-09,400,NaN,...,NaN,10.000000,456573.0,6224410.0
...,...,...,...,...,...,...,...,...,...
42720,S06580577_20230907,2023-09-07,426,NaN,...,NaN,4.694836,908596.0,6499943.0
35760,S06001284_20230907,2023-09-07,421,NaN,...,NaN,87.885986,910629.0,6500149.0
35783,S06001533_20230907,2023-09-07,401,NaN,...,NaN,62.344140,909322.0,6499820.0
38878,S06137040_20231011,2023-10-11,400,NaN,...,NaN,10.000000,967828.0,6518569.0
38873,S06137014_20231011,2023-10-11,405,NaN,...,NaN,NaN,975894.0,6519648.0

In [ ]:
# Laplacian smoothing for wide taxa table (harmonic extension).
# Keeps observed values; fills only NaNs.
# Requires: numpy, pandas, scipy, scikit-learn

import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import scipy.sparse as sp
import scipy.sparse.linalg as spla

# ----------------------------
# Build kNN graph and Laplacian
# ----------------------------
def build_st_graph(meta: pd.DataFrame,
                   x_col="Longitude_Lambert93",
                   y_col="Latitude_Lambert93",
                   date_col="Date_SamplingOperation",
                   k=12, hs_km=80.0, ht_days=120.0,
                   symmetrize=True):
    """Returns (W, L, meta_out, Z) where L=D-W (unnormalized)."""
    m = meta.copy()
    m[date_col] = pd.to_datetime(m[date_col], errors="coerce")
    if m[date_col].isna().any():
        raise ValueError("Unparseable dates.")
    # Scale: meters→km; days unchanged
    hs_m = max(hs_km, 1e-6) * 1000.0
    t0 = m[date_col].min()
    Z = np.column_stack([
        m[x_col].to_numpy(float) / hs_m,
        m[y_col].to_numpy(float) / hs_m,
        (m[date_col] - t0).dt.days.to_numpy(float) / max(ht_days, 1e-6),
    ])
    n = len(m)
    k_eff = min(k, n-1) if n > 1 else 0
    if k_eff <= 0:
        W = sp.csr_matrix((n, n))
        D = sp.csr_matrix((n, n))
        L = D - W
        return W, L, m, Z

    nn = NearestNeighbors(n_neighbors=k_eff, metric="euclidean").fit(Z)
    d, idx = nn.kneighbors(Z, return_distance=True)  # (n, k)
    rows = np.repeat(np.arange(n), k_eff)
    cols = idx.ravel()
    w = np.exp(-0.5 * (d.ravel() ** 2))  # Gaussian weight on scaled distances
    W = sp.csr_matrix((w, (rows, cols)), shape=(n, n))
    if symmetrize:
        W = W.maximum(W.T)
    D = sp.diags(np.asarray(W.sum(axis=1)).ravel())
    L = D - W
    return W, L, m, Z

# ---------------------------------
# Harmonic extension (per taxon col)
# ---------------------------------
def laplacian_impute_matrix(M: pd.DataFrame,
                            L: sp.spmatrix,
                            obs_exact=True,
                            ridge=1e-6,
                            solver="spsolve"):
    """
    For each column y:
      Partition indices into O (observed) and M (missing).
      Solve (L_MM + ridge*I) z_M = - L_MO y_O, set z_O = y_O.
    Returns DataFrame same shape as M.
    """
    A = L.tocsr()
    n, p = M.shape
    Y = M.to_numpy(float)
    out = np.empty_like(Y)
    for j in range(p):
        y = Y[:, j]
        obs = np.isfinite(y)
        if obs.all():
            out[:, j] = y
            continue
        if not obs.any():
            out[:, j] = np.zeros(n)  # fallback; change if needed
            continue
        miss = ~obs
        # Sub-blocks
        L_MM = A[miss][:, miss]
        L_MO = A[miss][:, obs]
        b = - L_MO @ y[obs]
        # Stabilize
        A_sys = L_MM + ridge * sp.eye(L_MM.shape[0], format="csr")
        if solver == "cg":
            zM, info = spla.cg(A_sys, b, atol=0, rtol=1e-6, maxiter=2000)
            if info != 0:
                zM = spla.spsolve(A_sys.tocsc(), b)
        else:
            zM = spla.spsolve(A_sys.tocsc(), b)
        z = np.empty(n, dtype=float)
        z[obs]  = y[obs] if obs_exact else y[obs]  # clamp observed
        z[miss] = zM
        out[:, j] = z
    return pd.DataFrame(out, index=M.index, columns=M.columns)

# -------------------------------------------
# Wrapper for your df_long (wide taxa columns)
# -------------------------------------------
def impute_taxa_laplacian(df_long: pd.DataFrame,
                          id_col="SamplingOperations_code",
                          date_col="Date_SamplingOperation",
                          total_col="TotalAbundance_SamplingOperation",
                          x_col="Longitude_Lambert93",
                          y_col="Latitude_Lambert93",
                          taxa_cols=None,
                          k=12, hs_km=80.0, ht_days=120.0,
                          ridge=1e-6,
                          renorm_to_total=True):
    # Meta
    meta = (df_long[[id_col, date_col, total_col, x_col, y_col]]
            .drop_duplicates(subset=[id_col])
            .set_index(id_col)
            .sort_index())
    # Taxa matrix
    if taxa_cols is None:
        exclude = {id_col, date_col, total_col, x_col, y_col}
        taxa_cols = [c for c in df_long.columns
                     if c not in exclude and pd.api.types.is_numeric_dtype(df_long[c])]
    M = (df_long[[id_col] + taxa_cols]
         .groupby(id_col, as_index=True)
         .mean(numeric_only=True)
         .reindex(meta.index))

    # Graph
    _, L, meta_aligned, _ = build_st_graph(
        meta.reset_index(),
        x_col=x_col, y_col=y_col, date_col=date_col,
        k=k, hs_km=hs_km, ht_days=ht_days, symmetrize=True
    )
    L = L.tocsr()

    # Impute
    M_filled = laplacian_impute_matrix(M, L, obs_exact=True, ridge=ridge, solver="spsolve")

    # Optional: preserve per-sample totals by scaling only imputed part
    if renorm_to_total and total_col in meta_aligned.columns:
        totals = meta_aligned.set_index(id_col)[total_col].reindex(M_filled.index).to_numpy(float)
        obs_mask = np.isfinite(M.to_numpy(float))
        X = M.to_numpy(float)
        Y = M_filled.to_numpy(float)
        for i in range(Y.shape[0]):
            tgt = totals[i]
            if not np.isfinite(tgt):
                continue
            known_sum = np.nansum(np.where(obs_mask[i], X[i], 0.0))
            imp_mask = ~obs_mask[i]
            imp_sum = np.nansum(np.where(imp_mask, Y[i], 0.0))
            room = max(tgt - known_sum, 0.0)
            if imp_mask.any() and imp_sum > 0:
                Y[i, imp_mask] *= (room / imp_sum)
        M_filled = pd.DataFrame(Y, index=M_filled.index, columns=M_filled.columns)

    return M_filled, M, meta_aligned

In [9]:
df_long = df.copy()

In [12]:
M_filled, M_obs, meta = impute_taxa_laplacian(
    df_long,
    id_col="SamplingOperations_code",
    date_col="Date_SamplingOperation",
    total_col="TotalAbundance_SamplingOperation",
    x_col="Longitude_Lambert93",
    y_col="Latitude_Lambert93",
    taxa_cols=None,   # auto-detect numeric taxa columns
    k=12, hs_km=80.0, ht_days=120.0,
    ridge=1e-6,
    renorm_to_total=True,
)

In [13]:
M_filled

,Achaf02,Achat02,Achca02,Achco02,...,Tryku01,Tryle01,Ulnul01,Vibtr01
SamplingOperations_code,,,,,,,,,
S02000008_20170703,0.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,17.283951
S02000008_20200708,0.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,22.500000
S02000010_20070906,0.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,155.000000
S02000010_20080811,0.00000,2.500000,0.0,0.0,...,0.0,0.0,0.0,7.500000
S02000010_20090721,0.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,17.500000
...,...,...,...,...,...,...,...,...,...
S06999141_20160928,0.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,49.627792
S06999179_20230628,0.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,7.334963
S06999180_20160928,0.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,91.584158
S06999189_20160928,2.48139,0.000000,0.0,0.0,...,0.0,0.0,0.0,32.258065
S06999189_20220920,0.00000,4.926108,0.0,0.0,...,0.0,0.0,0.0,133.004926

In [14]:
M_obs # this is a boolean mask where True = originally observed

,Achaf02,Achat02,Achca02,Achco02,...,Tryku01,Tryle01,Ulnul01,Vibtr01
SamplingOperations_code,,,,,,,,,
S02000008_20170703,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,17.283951
S02000008_20200708,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,22.500000
S02000010_20070906,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,155.000000
S02000010_20080811,NaN,2.500000,NaN,NaN,...,NaN,NaN,NaN,7.500000
S02000010_20090721,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,17.500000
...,...,...,...,...,...,...,...,...,...
S06999141_20160928,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,49.627792
S06999179_20230628,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,7.334963
S06999180_20160928,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,91.584158
S06999189_20160928,2.48139,NaN,NaN,NaN,...,NaN,NaN,NaN,32.258065
S06999189_20220920,NaN,4.926108,NaN,NaN,...,NaN,NaN,NaN,133.004926