In [1]:
# Data manipulation and numerical computation
import numpy as np
import pandas as pd
import os

# pandas all columns display
pd.set_option('display.max_columns', None)

# Load data

In [2]:
path = "../../data/processed/"
dfs = {}

# read 03_CLEAN_COMPLETE_DF.parquet
df1 = pd.read_parquet(os.path.join(path, "taxones_pressure_epm_train.parquet"))
df2 = pd.read_parquet(os.path.join(path, "taxones_pressure_epm_predict.parquet"))
df = pd.concat([df1, df2], ignore_index=True)

In [3]:
# change unassessed values to NaN
df = df.replace("Unassessed", np.nan)
df = df.replace("None", np.nan)

# index SamplingOperations_code
df = df.set_index('SamplingOperations_code')


# sort by Date_SamplingOperation
df = df.sort_values(by='Date_SamplingOperation')

df = df[['CodeSite_SamplingOperations_x', 'Date_SamplingOperation', 'IBD', 'IBD_EQR', 'IBD_EQR_Status', 'Longitude_Lambert93', 'Latitude_Lambert93', 'Watershed', 'HERlvl1Name', 'Streamsize']]
# DROP HERlvl2Code	Altitude Longitude_Lambert93	Latitude_Lambert93	Watershed	CodeDepartement	HERlvl1Code
# df = df.drop(columns=['HERlvl2Code', 'HERlvl2Name', 'HERlvl1Name', 'Altitude','Longitude_Lambert93','Latitude_Lambert93','Watershed','CodeDepartement', 'Date_SamplingOperation'])
df

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02115200_20070702,S02115200,2007-07-02,10.5,0.555556,Moderate,902925.0,6941112.0,Rhin-Meuse,COTES CALCAIRES EST,M
S05218450_20070709,S05218450,2007-07-09,20.0,1.000000,High,442885.0,6199880.0,Adour-Garonne,PYRENEES,TP
S05217350_20070709,S05217350,2007-07-09,20.0,1.000000,High,442250.0,6218040.0,Adour-Garonne,PYRENEES,TP
S05235850_20070709,S05235850,2007-07-09,NaN,NaN,NaN,463192.0,6225280.0,Adour-Garonne,COTEAUX AQUITAINS,TP
S05234290_20070709,S05234290,2007-07-09,16.6,0.773333,Moderate,456573.0,6224410.0,Adour-Garonne,PYRENEES,TP
...,...,...,...,...,...,...,...,...,...,...
S06580577_20230907,S06580577,2023-09-07,14.5,0.633333,Moderate,908596.0,6499943.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP
S06001284_20230907,S06001284,2023-09-07,16.3,0.753333,Moderate,910629.0,6500149.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP
S06001533_20230907,S06001533,2023-09-07,14.8,0.653333,Moderate,909322.0,6499820.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP
S06137040_20231011,S06137040,2023-10-11,20.0,1.000000,High,967828.0,6518569.0,Rhône-Méditerranée,ALPES INTERNES,P
S06137014_20231011,S06137014,2023-10-11,20.0,1.000000,High,975894.0,6519648.0,Rhône-Méditerranée,ALPES INTERNES,P

In [4]:
import numpy as np
from scipy.spatial import distance

def get_nans(df):
    nans_ibd = df['IBD'].isna().sum()
    nans_ibd_eqr = df['IBD_EQR'].isna().sum()
    nans_status = df['IBD_EQR_Status'].isna().sum()
    print(f"Total NaNs in IBD: {nans_ibd}")
    print(f"Total NaNs in IBD_EQR: {nans_ibd_eqr}")
    print(f"Total NaNs in IBD_EQR_Status: {nans_status}")

# CodeSite Sampling Operatiens

In [5]:
# how many different CodeSite_SamplingOperations_x are there?
df['CodeSite_SamplingOperations_x'].nunique()

8404

In [6]:
# create a dictionary of dataframes per site and later access them by 1, 2, ...
sites = {}
for site, group in df.groupby('CodeSite_SamplingOperations_x'):
    sites[site] = group

In [7]:
site = sites['S05151150']
site

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S05151150_20070809,S05151150,2007-08-09,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20080704,S05151150,2008-07-04,19.8,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20090707,S05151150,2009-07-07,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20100804,S05151150,2010-08-04,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20110614,S05151150,2011-06-14,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20110719,S05151150,2011-07-19,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20120717,S05151150,2012-07-17,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20120806,S05151150,2012-08-06,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20130708,S05151150,2013-07-08,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20130806,S05151150,2013-08-06,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20140805,S05151150,2014-08-05,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20140821,S05151150,2014-08-21,NaN,NaN,NaN,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20150721,S05151150,2015-07-21,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20150824,S05151150,2015-08-24,NaN,NaN,NaN,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20160804,S05151150,2016-08-04,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20160817,S05151150,2016-08-17,NaN,NaN,NaN,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20171003,S05151150,2017-10-03,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20180726,S05151150,2018-07-26,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20190820,S05151150,2019-08-20,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20200723,S05151150,2020-07-23,NaN,NaN,NaN,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20210722,S05151150,2021-07-22,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20220718,S05151150,2022-07-18,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP

In [8]:
def interpolate(site):
    # make interpolation of IBD and the IBD_EQR columns
    site['IBD'] = site['IBD'].interpolate(method='linear')
    site['IBD_EQR'] = site['IBD_EQR'].interpolate(method='linear')
    return site

def safe_fill(site, col="IBD_EQR_Status", date_col="Date_SamplingOperation"):
    site = site.sort_values(date_col).copy()
    prev, nxt = site[col].ffill(), site[col].bfill()
    mask = site[col].isna() & prev.eq(nxt) & prev.notna()
    site.loc[mask, col] = prev[mask]
    return site

## ejemplo

In [9]:
site = safe_fill(site)
site

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S05151150_20070809,S05151150,2007-08-09,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20080704,S05151150,2008-07-04,19.8,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20090707,S05151150,2009-07-07,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20100804,S05151150,2010-08-04,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20110614,S05151150,2011-06-14,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20110719,S05151150,2011-07-19,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20120717,S05151150,2012-07-17,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20120806,S05151150,2012-08-06,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20130708,S05151150,2013-07-08,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20130806,S05151150,2013-08-06,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20140805,S05151150,2014-08-05,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20140821,S05151150,2014-08-21,NaN,NaN,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20150721,S05151150,2015-07-21,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20150824,S05151150,2015-08-24,NaN,NaN,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20160804,S05151150,2016-08-04,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20160817,S05151150,2016-08-17,NaN,NaN,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20171003,S05151150,2017-10-03,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20180726,S05151150,2018-07-26,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20190820,S05151150,2019-08-20,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20200723,S05151150,2020-07-23,NaN,NaN,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20210722,S05151150,2021-07-22,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20220718,S05151150,2022-07-18,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP

In [10]:
site = interpolate(site)
site

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S05151150_20070809,S05151150,2007-08-09,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20080704,S05151150,2008-07-04,19.8,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20090707,S05151150,2009-07-07,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20100804,S05151150,2010-08-04,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20110614,S05151150,2011-06-14,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20110719,S05151150,2011-07-19,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20120717,S05151150,2012-07-17,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20120806,S05151150,2012-08-06,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20130708,S05151150,2013-07-08,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20130806,S05151150,2013-08-06,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20140805,S05151150,2014-08-05,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20140821,S05151150,2014-08-21,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20150721,S05151150,2015-07-21,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20150824,S05151150,2015-08-24,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20160804,S05151150,2016-08-04,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20160817,S05151150,2016-08-17,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20171003,S05151150,2017-10-03,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20180726,S05151150,2018-07-26,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20190820,S05151150,2019-08-20,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20200723,S05151150,2020-07-23,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20210722,S05151150,2021-07-22,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP
S05151150_20220718,S05151150,2022-07-18,20.0,1.0,High,760560.0,6352370.0,Adour-Garonne,CEVENNES,TP

## otro sitio

In [11]:
site = sites['S02061500']
site

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02061500_20070806,S02061500,2007-08-06,13.8,0.628571,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20080721,S02061500,2008-07-21,11.3,0.450000,Poor,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20090820,S02061500,2009-08-20,NaN,NaN,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20100721,S02061500,2010-07-21,16.1,0.792857,Good,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20110704,S02061500,2011-07-04,15.7,0.764286,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20120716,S02061500,2012-07-16,NaN,NaN,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20130718,S02061500,2013-07-18,16.6,0.828571,Good,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20140915,S02061500,2014-09-15,16.3,0.807143,Good,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20140923,S02061500,2014-09-23,12.8,0.557143,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20150706,S02061500,2015-07-06,19.5,1.000000,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20160721,S02061500,2016-07-21,NaN,NaN,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20170810,S02061500,2017-08-10,NaN,NaN,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20180726,S02061500,2018-07-26,18.9,0.992857,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20190716,S02061500,2019-07-16,NaN,NaN,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20200710,S02061500,2020-07-10,18.4,0.957143,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20210812,S02061500,2021-08-12,15.9,0.778571,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP

In [12]:
safe_fill(site)

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02061500_20070806,S02061500,2007-08-06,13.8,0.628571,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20080721,S02061500,2008-07-21,11.3,0.450000,Poor,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20090820,S02061500,2009-08-20,NaN,NaN,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20100721,S02061500,2010-07-21,16.1,0.792857,Good,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20110704,S02061500,2011-07-04,15.7,0.764286,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20120716,S02061500,2012-07-16,NaN,NaN,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20130718,S02061500,2013-07-18,16.6,0.828571,Good,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20140915,S02061500,2014-09-15,16.3,0.807143,Good,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20140923,S02061500,2014-09-23,12.8,0.557143,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20150706,S02061500,2015-07-06,19.5,1.000000,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20160721,S02061500,2016-07-21,NaN,NaN,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20170810,S02061500,2017-08-10,NaN,NaN,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20180726,S02061500,2018-07-26,18.9,0.992857,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20190716,S02061500,2019-07-16,NaN,NaN,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20200710,S02061500,2020-07-10,18.4,0.957143,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20210812,S02061500,2021-08-12,15.9,0.778571,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP

In [13]:
interpolate(site)

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02061500_20070806,S02061500,2007-08-06,13.80,0.628571,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20080721,S02061500,2008-07-21,11.30,0.450000,Poor,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20090820,S02061500,2009-08-20,13.70,0.621429,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20100721,S02061500,2010-07-21,16.10,0.792857,Good,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20110704,S02061500,2011-07-04,15.70,0.764286,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20120716,S02061500,2012-07-16,16.15,0.796429,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20130718,S02061500,2013-07-18,16.60,0.828571,Good,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20140915,S02061500,2014-09-15,16.30,0.807143,Good,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20140923,S02061500,2014-09-23,12.80,0.557143,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20150706,S02061500,2015-07-06,19.50,1.000000,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20160721,S02061500,2016-07-21,19.30,0.997619,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20170810,S02061500,2017-08-10,19.10,0.995238,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20180726,S02061500,2018-07-26,18.90,0.992857,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20190716,S02061500,2019-07-16,18.65,0.975000,NaN,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20200710,S02061500,2020-07-10,18.40,0.957143,High,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP
S02061500_20210812,S02061500,2021-08-12,15.90,0.778571,Moderate,995317.0,6794553.0,Rhin-Meuse,VOSGES,TP

# Interpolate missing values for a site

In [14]:
nans = 0

for site_key in sites:
    site = sites[site_key]
    site = interpolate(site)
    nan_status = site['IBD_EQR_Status'].isna().sum()
    site = safe_fill(site)
    filled_nan_status = site['IBD_EQR_Status'].isna().sum()
    nans += nan_status - filled_nan_status
    sites[site_key] = site

print(f"Total NaNs filled in IBD_EQR_Status: {nans}")

C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()
C:\Users\herie\AppData\Local\Temp\ipykernel_54448\4069221416.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prev, nxt = site[col].ffill(), site[col].bfill()

Total NaNs filled in IBD_EQR_Status: 2467

In [15]:
# concat all sites back to a single dataframe
df_filled = pd.concat(sites.values())
df_filled

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02000008_20170703,S02000008,2017-07-03,9.60,0.502924,Poor,1039055.0,6721258.0,Rhin-Meuse,ALSACE,TP
S02000008_20200708,S02000008,2020-07-08,8.00,0.409357,Poor,1039055.0,6721258.0,Rhin-Meuse,ALSACE,TP
S02000010_20070906,S02000010,2007-09-06,14.30,0.777778,Moderate,1039381.0,6737723.0,Rhin-Meuse,ALSACE,None
S02000010_20080811,S02000010,2008-08-11,14.65,0.798246,NaN,1039381.0,6737723.0,Rhin-Meuse,ALSACE,None
S02000010_20090721,S02000010,2009-07-21,15.00,0.818713,Good,1039381.0,6737723.0,Rhin-Meuse,ALSACE,None
...,...,...,...,...,...,...,...,...,...,...
S06999141_20160928,S06999141,2016-09-28,15.60,0.706667,Moderate,939726.0,6583451.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP
S06999179_20230628,S06999179,2023-06-28,20.00,1.000000,High,935630.0,6584385.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP
S06999180_20160928,S06999180,2016-09-28,19.50,0.966667,High,934863.0,6578148.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP
S06999189_20160928,S06999189,2016-09-28,16.10,0.740000,Moderate,939337.0,6583035.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP
S06999189_20220920,S06999189,2022-09-20,16.60,0.773333,Moderate,939337.0,6583035.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP

In [16]:
get_nans(df_filled)

Total NaNs in IBD: 1084
Total NaNs in IBD_EQR: 1084
Total NaNs in IBD_EQR_Status: 3196

In [ ]:
# view nans in df_filled
df_filled[df_filled['IBD_EQR_Status'].isna()]

# Get inside ranges

In [17]:
ranges = pd.read_csv("../../data/processed/IBD_EQR_Status_ranges_by_HERlvl1Name.csv")
ranges

               HERlvl1Name IBD_EQR_Status  IBD_min  IBD_max  IBD_mid
0               ARMORICAIN            Bad      4.5      5.8     5.15
1               ARMORICAIN           Poor      6.3     10.0     8.15
2               ARMORICAIN       Moderate     10.1     13.7    11.90
3               ARMORICAIN           Good     13.8     16.4    15.10
4               ARMORICAIN           High     16.5     20.0    18.25
..                     ...            ...      ...      ...      ...
101  DEPOTS ARGILO SABLEUX           High     17.1     20.0    18.55
102         GRANDS CAUSSES           Poor      9.6      9.6     9.60
103         GRANDS CAUSSES       Moderate     11.3     14.3    12.80
104         GRANDS CAUSSES           Good     14.4     17.0    15.70
105         GRANDS CAUSSES           High     17.1     20.0    18.55

[106 rows x 5 columns]

In [18]:
# if ibd in ranges, fill ibd_eqr_status accordingly
for site_key in sites:
    site = sites[site_key]
    herlvl1 = site['HERlvl1Name'].values[0]
    site_ranges = ranges[ranges['HERlvl1Name'] == herlvl1]
    for idx, row in site.iterrows():
        ibd_value = row['IBD']
        if pd.notna(ibd_value):
            matching_range = site_ranges[(site_ranges['IBD_min'] <= ibd_value) & (site_ranges['IBD_max'] >= ibd_value)]
            if not matching_range.empty:
                status = matching_range['IBD_EQR_Status'].values[0]
                df_filled.at[idx, 'IBD_EQR_Status'] = status

In [19]:
get_nans(df_filled)

Total NaNs in IBD: 1084
Total NaNs in IBD_EQR: 1084
Total NaNs in IBD_EQR_Status: 1151

In [20]:
# view nans in df_filled
df_filled[df_filled['IBD_EQR_Status'].isna()]

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02001016_20080811,S02001016,2008-08-11,NaN,NaN,NaN,1032286.0,6737746.0,Rhin-Meuse,ALSACE,TP
S02001046_20100726,S02001046,2010-07-26,NaN,NaN,NaN,1045006.0,6801458.0,Rhin-Meuse,ALSACE,TP
S02001500_20070907,S02001500,2007-09-07,NaN,NaN,NaN,1046252.0,6813302.0,Rhin-Meuse,ALSACE,TP
S02001500_20080805,S02001500,2008-08-05,NaN,NaN,NaN,1046252.0,6813302.0,Rhin-Meuse,ALSACE,TP
S02001895_20160721,S02001895,2016-07-21,NaN,NaN,NaN,1023024.0,6730009.0,Rhin-Meuse,ALSACE,TP
...,...,...,...,...,...,...,...,...,...,...
S06830193_20210729,S06830193,2021-07-29,NaN,NaN,NaN,934066.0,6547067.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP
S06830239_20190701,S06830239,2019-07-01,NaN,NaN,NaN,958226.0,6581199.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP
S06830246_20150604,S06830246,2015-06-04,NaN,NaN,NaN,958147.0,6587830.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP
S06830800_20080709,S06830800,2008-07-09,NaN,NaN,NaN,926467.0,6538028.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,P
S06840540_20170626,S06840540,2017-06-26,NaN,NaN,NaN,861191.0,6438895.0,Rhône-Méditerranée,JURA-PREALPES DU NORD,TP

# 1084 codesite sueltos

In [21]:
sites.keys()

dict_keys(['S02000008', 'S02000010', 'S02000011', 'S02000990', 'S02001000', 'S02001006', 'S02001016', 'S02001025', 'S02001030', 'S02001046', 'S02001050', 'S02001100', 'S02001150', 'S02001200', 'S02001250', 'S02001500', 'S02001700', 'S02001715', 'S02001717', 'S02001725', 'S02001738', 'S02001750', 'S02001895', 'S02001915', 'S02001955', 'S02001990', 'S02002000', 'S02002800', 'S02003100', 'S02003200', 'S02003350', 'S02003397', 'S02003400', 'S02003610', 'S02003617', 'S02003620', 'S02003670', 'S02003700', 'S02003800', 'S02003900', 'S02004000', 'S02004300', 'S02004800', 'S02005000', 'S02005688', 'S02005700', 'S02006450', 'S02006500', 'S02007000', 'S02007250', 'S02007300', 'S02007380', 'S02008000', 'S02009000', 'S02009500', 'S02010000', 'S02011000', 'S02013000', 'S02015000', 'S02016050', 'S02017000', 'S02017500', 'S02017850', 'S02018000', 'S02018500', 'S02018690', 'S02018780', 'S02019000', 'S02019200', 'S02019500', 'S02019950', 'S02020000', 'S02020300', 'S02020750', 'S02021000', 'S02021700', 'S02022000', 'S02022465', 'S02022650', 'S02022670', 'S02022675', 'S02022700', 'S02022730', 'S02022760', 'S02022800', 'S02023000', 'S02023500', 'S02023750', 'S02024000', 'S02024300', 'S02025100', 'S02025125', 'S02025150', 'S02025200', 'S02025500', 'S02025700', 'S02026125', 'S02026200', 'S02026250', 'S02026500', 'S02026750', 'S02027000', 'S02028000', 'S02028100', 'S02028300', 'S02028500', 'S02029000', 'S02029160', 'S02030200', 'S02030310', 'S02030350', 'S02030400', 'S02030450', 'S02030500', 'S02031400', 'S02031520', 'S02031650', 'S02032000', 'S02032050', 'S02032400', 'S02032800', 'S02035000', 'S02035600', 'S02035750', 'S02036000', 'S02036250', 'S02036265', 'S02037000', 'S02037400', 'S02037500', 'S02038000', 'S02040800', 'S02041000', 'S02041100', 'S02041230', 'S02041290', 'S02041500', 'S02041575', 'S02041650', 'S02041741', 'S02041750', 'S02041950', 'S02042000', 'S02042340', 'S02042348', 'S02042500', 'S02042520', 'S02042555', 'S02042650', 'S02042700', 'S02042900', 'S02043000', 'S02043050', 'S02043260', 'S02043280', 'S02043300', 'S02043450', 'S02043500', 'S02043600', 'S02043655', 'S02043680', 'S02043690', 'S02043700', 'S02043750', 'S02043775', 'S02043780', 'S02043785', 'S02043790', 'S02043800', 'S02043860', 'S02044000', 'S02044020', 'S02044100', 'S02044300', 'S02044400', 'S02045000', 'S02045050', 'S02045160', 'S02045170', 'S02045200', 'S02045250', 'S02045283', 'S02045350', 'S02045500', 'S02046000', 'S02046400', 'S02046860', 'S02047000', 'S02048960', 'S02048980', 'S02049000', 'S02049120', 'S02049500', 'S02049900', 'S02050000', 'S02050260', 'S02051000', 'S02051500', 'S02051600', 'S02051820', 'S02052000', 'S02052500', 'S02052600', 'S02052800', 'S02053800', 'S02054000', 'S02054100', 'S02054150', 'S02054300', 'S02054500', 'S02054550', 'S02054900', 'S02055000', 'S02055100', 'S02055200', 'S02055500', 'S02055580', 'S02056020', 'S02056200', 'S02057000', 'S02057065', 'S02057168', 'S02057210', 'S02057245', 'S02057250', 'S02057300', 'S02057350', 'S02057400', 'S02057453', 'S02057480', 'S02057490', 'S02057503', 'S02057520', 'S02057525', 'S02057557', 'S02057600', 'S02057650', 'S02057760', 'S02058000', 'S02058990', 'S02059070', 'S02059500', 'S02059760', 'S02059800', 'S02060100', 'S02060200', 'S02060500', 'S02060650', 'S02060700', 'S02060750', 'S02061250', 'S02061500', 'S02061970', 'S02063000', 'S02064000', 'S02064530', 'S02064770', 'S02065090', 'S02065280', 'S02065500', 'S02066000', 'S02067000', 'S02067150', 'S02067153', 'S02067400', 'S02067450', 'S02067505', 'S02067515', 'S02067585', 'S02067600', 'S02067800', 'S02067900', 'S02068500', 'S02068510', 'S02068600', 'S02068700', 'S02068790', 'S02068800', 'S02069100', 'S02070000', 'S02070250', 'S02070300', 'S02070350', 'S02070370', 'S02070500', 'S02070750', 'S02070775', 'S02070810', 'S02070900', 'S02071050', 'S02072050', 'S02072150', 'S02072400', 'S02072600', 'S02072670', 'S02072700', 'S02073200', 'S02073700', 'S02074000', 'S02074900', 'S02075300', 'S02076100', 'S02076180', 'S02076195', 'S02076580', 'S02076800', 'S02077150', 'S02077200', 'S02077300', 'S02077445', 'S02077450', 'S02077700', 'S02077775', 'S02078000', 'S02078500', 'S02078900', 'S02079000', 'S02079250', 'S02079500', 'S02080200', 'S02080500', 'S02081000', 'S02081030', 'S02081100', 'S02081135', 'S02081300', 'S02081600', 'S02081620', 'S02082000', 'S02082160', 'S02082330', 'S02082350', 'S02082710', 'S02082845', 'S02082878', 'S02082900', 'S02082920', 'S02082970', 'S02082985', 'S02082990', 'S02084000', 'S02084100', 'S02084200', 'S02084650', 'S02084800', 'S02084900', 'S02085325', 'S02085600', 'S02085615', 'S02085700', 'S02085850', 'S02085920', 'S02086030', 'S02086170', 'S02086220', 'S02086250', 'S02086300', 'S02086360', 'S02086400', 'S02086450', 'S02086480', 'S02086500', 'S02086550', 'S02086900', 'S02088000', 'S02088400', 'S02089000', 'S02089900', 'S02090000', 'S02091500', 'S02092000', 'S02092600', 'S02093100', 'S02093170', 'S02093200', 'S02093250', 'S02093600', 'S02094000', 'S02094500', 'S02094700', 'S02094800', 'S02094900', 'S02094920', 'S02094940', 'S02094950', 'S02094970', 'S02094973', 'S02094978', 'S02094979', 'S02095250', 'S02095500', 'S02095600', 'S02095900', 'S02096000', 'S02096015', 'S02096480', 'S02096500', 'S02096520', 'S02096575', 'S02096750', 'S02096900', 'S02096950', 'S02096975', 'S02096990', 'S02097000', 'S02098100', 'S02098200', 'S02098769', 'S02098800', 'S02098900', 'S02098980', 'S02099500', 'S02099550', 'S02100100', 'S02100190', 'S02100600', 'S02100603', 'S02100900', 'S02101050', 'S02102000', 'S02103950', 'S02104000', 'S02104400', 'S02104800', 'S02105000', 'S02106220', 'S02106222', 'S02106230', 'S02106320', 'S02106380', 'S02106405', 'S02106410', 'S02106430', 'S02106500', 'S02106600', 'S02106655', 'S02106665', 'S02106700', 'S02106750', 'S02106800', 'S02106815', 'S02106840', 'S02106850', 'S02106895', 'S02106900', 'S02106980', 'S02107000', 'S02107250', 'S02107400', 'S02107600', 'S02107800', 'S02107845', 'S02107870', 'S02107890', 'S02107900', 'S02108700', 'S02109000', 'S02109140', 'S02109245', 'S02110000', 'S02110050', 'S02110100', 'S02110450', 'S02110500', 'S02110600', 'S02110650', 'S02110670', 'S02110715', 'S02110915', 'S02111000', 'S02111500', 'S02112000', 'S02112050', 'S02112150', 'S02112170', 'S02112300', 'S02112405', 'S02113000', 'S02114000', 'S02114250', 'S02114500', 'S02115000', 'S02115200', 'S02115615', 'S02115625', 'S02115650', 'S02115653', 'S02115660', 'S02115670', 'S02115675', 'S02115685', 'S02115725', 'S02115750', 'S02115762', 'S02115772', 'S02115775', 'S02115790', 'S02115795', 'S02115800', 'S02115820', 'S02115840', 'S02115851', 'S02115855', 'S02115862', 'S02115900', 'S02115950', 'S02116000', 'S02116100', 'S02116500', 'S02116570', 'S02116600', 'S02117000', 'S02117350', 'S02117400', 'S02117575', 'S02117585', 'S02118000', 'S02118300', 'S02118500', 'S02118550', 'S02118750', 'S02119000', 'S02120000', 'S02120400', 'S02121050', 'S02121500', 'S02121750', 'S02122200', 'S02122750', 'S02123000', 'S02123300', 'S02123500', 'S02124000', 'S03000029', 'S03000033', 'S03000070', 'S03000100', 'S03000440', 'S03000456', 'S03000688', 'S03000890', 'S03001000', 'S03002021', 'S03002047', 'S03002100', 'S03002130', 'S03002309', 'S03002310', 'S03002315', 'S03002380', 'S03002405', 'S03002406', 'S03002407', 'S03002425', 'S03002440', 'S03002536', 'S03002564', 'S03002810', 'S03002900', 'S03003790', 'S03004095', 'S03004232', 'S03004280', 'S03004310', 'S03004349', 'S03004985', 'S03005200', 'S03005210', 'S03005284', 'S03005539', 'S03005747', 'S03005999', 'S03006000', 'S03006109', 'S03006120', 'S03006215', 'S03006241', 'S03006268', 'S03006271', 'S03006272', 'S03006275', 'S03006354', 'S03006390', 'S03006410', 'S03006475', 'S03006540', 'S03006590', 'S03006870', 'S03006900', 'S03007000', 'S03007023', 'S03007351', 'S03007383', 'S03007571', 'S03007800', 'S03008267', 'S03008306', 'S03008459', 'S03008483', 'S03008505', 'S03008671', 'S03008672', 'S03008714', 'S03008833', 'S03008848', 'S03008950', 'S03009000', 'S03009650', 'S03010070', 'S03010196', 'S03010670', 'S03010930', 'S03011080', 'S03011175', 'S03011300', 'S03011390', 'S03011620', 'S03011740', 'S03011760', 'S03011780', 'S03011840', 'S03012050', 'S03012100', 'S03012280', 'S03012310', 'S03012355', 'S03012380', 'S03012450', 'S03012660', 'S03012680', 'S03012710', 'S03013212', 'S03013290', 'S03013300', 'S03013345', 'S03013372', 'S03013550', 'S03013615', 'S03013660', 'S03013677', 'S03013705', 'S03013740', 'S03013930', 'S03014000', 'S03014030', 'S03014130', 'S03014140', 'S03014170', 'S03014245', 'S03014299', 'S03014320', 'S03014330', 'S03014470', 'S03014550', 'S03014695', 'S03014846', 'S03014907', 'S03014927', 'S03014940', 'S03014986', 'S03015000', 'S03015005', 'S03015514', 'S03016191', 'S03016240', 'S03016285', 'S03016310', 'S03016488', 'S03016498', 'S03016840', 'S03017000', 'S03017556', 'S03017900', 'S03018140', 'S03018150', 'S03018196', 'S03018242', 'S03018248', 'S03018342', 'S03018431', 'S03018531', 'S03018541', 'S03018652', 'S03018675', 'S03018791', 'S03018857', 'S03018860', 'S03018940', 'S03018947', 'S03018951', 'S03018997', 'S03019795', 'S03020000', 'S03020126', 'S03020145', 'S03020240', 'S03020477', 'S03020490', 'S03020591', 'S03020650', 'S03021000', 'S03021230', 'S03021531', 'S03021588', 'S03021700', 'S03021917', 'S03022000', 'S03022087', 'S03022104', 'S03022114', 'S03022140', 'S03022229', 'S03022330', 'S03022464', 'S03022505', 'S03022589', 'S03022667', 'S03022718', 'S03022790', 'S03022840', 'S03022859', 'S03022896', 'S03023000', 'S03023025', 'S03023700', 'S03024230', 'S03024245', 'S03024251', 'S03024255', 'S03024285', 'S03024294', 'S03024300', 'S03024330', 'S03024333', 'S03024343', 'S03024355', 'S03024392', 'S03024426', 'S03024468', 'S03024493', 'S03024510', 'S03024522', 'S03024523', 'S03024530', 'S03024545', 'S03024547', 'S03024550', 'S03024560', 'S03024581', 'S03024597', 'S03024725', 'S03024736', 'S03024840', 'S03024885', 'S03024922', 'S03025020', 'S03025045', 'S03025140', 'S03025163', 'S03025165', 'S03025238', 'S03025249', 'S03025331', 'S03025368', 'S03025440', 'S03025492', 'S03025524', 'S03025548', 'S03025549', 'S03025550', 'S03025551', 'S03025570', 'S03025902', 'S03025919', 'S03025938', 'S03026000', 'S03026179', 'S03026382', 'S03026529', 'S03026565', 'S03027000', 'S03027490', 'S03027491', 'S03027549', 'S03027697', 'S03027790', 'S03027807', 'S03027840', 'S03027844', 'S03027845', 'S03027847', 'S03027999', 'S03028000', 'S03028239', 'S03029000', 'S03029140', 'S03029225', 'S03029290', 'S03029470', 'S03029500', 'S03029530', 'S03029549', 'S03029630', 'S03029710', 'S03029798', 'S03029865', 'S03029890', 'S03029910', 'S03030000', 'S03030155', 'S03030163', 'S03030457', 'S03030550', 'S03030602', 'S03031040', 'S03031191', 'S03032000', 'S03032210', 'S03032224', 'S03032240', 'S03032375', 'S03032550', 'S03032610', 'S03032620', 'S03032660', 'S03032675', 'S03032695', 'S03032731', 'S03032780', 'S03032791', 'S03032826', 'S03032827', 'S03032862', 'S03032904', 'S03032942', 'S03032959', 'S03033000', 'S03033010', 'S03033028', 'S03033030', 'S03033038', 'S03033050', 'S03033090', 'S03033120', 'S03033150', 'S03033151', 'S03033200', 'S03033220', 'S03033240', 'S03033249', 'S03033273', 'S03033280', 'S03033305', 'S03033306', 'S03033395', 'S03033456', 'S03033470', 'S03033535', 'S03033544', 'S03033610', 'S03033660', 'S03033830', 'S03034112', 'S03034127', 'S03034254', 'S03034285', 'S03034370', 'S03034435', 'S03034440', 'S03034465', 'S03034480', 'S03034494', 'S03034690', 'S03034720', 'S03034790', 'S03034813', 'S03034961', 'S03035000', 'S03035105', 'S03035113', 'S03035394', 'S03035422', 'S03035455', 'S03035570', 'S03035667', 'S03035770', 'S03035840', 'S03036000', 'S03036030', 'S03036064', 'S03036070', 'S03036153', 'S03036214', 'S03036280', 'S03036325', 'S03036329', 'S03036332', 'S03036339', 'S03036361', 'S03036402', 'S03036445', 'S03036475', 'S03036490', 'S03036496', 'S03036510', 'S03036630', 'S03036638', 'S03036650', 'S03036697', 'S03036710', 'S03036800', 'S03036885', 'S03036900', 'S03036920', 'S03036970', 'S03037480', 'S03037550', 'S03037576', 'S03037650', 'S03037660', 'S03037890', 'S03038385', 'S03038425', 'S03038630', 'S03038700', 'S03038810', 'S03038997', 'S03039000', 'S03039110', 'S03039130', 'S03039240', 'S03039290', 'S03039390', 'S03039444', 'S03039673', 'S03039940', 'S03040250', 'S03040450', 'S03040485', 'S03040520', 'S03040639', 'S03040791', 'S03041000', 'S03041165', 'S03041180', 'S03041247', 'S03041285', 'S03041348', 'S03041530', 'S03041600', 'S03041669', 'S03041680', 'S03041975', 'S03042190', 'S03042450', 'S03042460', 'S03042518', 'S03042590', 'S03043280', 'S03043450', 'S03043850', 'S03044000', 'S03044170', 'S03044490', 'S03044580', 'S03044690', 'S03044880', 'S03044917', 'S03045000', 'S03046200', 'S03046684', 'S03047279', 'S03047445', 'S03047627', 'S03047680', 'S03047685', 'S03047740', 'S03048000', 'S03048290', 'S03048347', 'S03049198', 'S03049850', 'S03050000', 'S03050200', 'S03051240', 'S03051250', 'S03051395', 'S03051490', 'S03051500', 'S03051520', 'S03051580', 'S03051590', 'S03051747', 'S03051750', 'S03051765', 'S03051840', 'S03051947', 'S03052014', 'S03052030', 'S03052040', 'S03052094', 'S03052105', 'S03052134', 'S03052145', 'S03052215', 'S03052245', 'S03052325', 'S03052338', 'S03052450', 'S03052465', 'S03052656', 'S03052760', 'S03052785', 'S03052823', 'S03052825', 'S03052845', 'S03052895', 'S03053000', 'S03053220', 'S03053275', 'S03053605', 'S03053710', 'S03053750', 'S03053777', 'S03053999', 'S03054000', 'S03054220', 'S03054600', 'S03055000', 'S03055369', 'S03055380', 'S03055490', 'S03056010', 'S03056024', 'S03056030', 'S03056105', 'S03056115', 'S03056135', 'S03056160', 'S03056210', 'S03056260', 'S03056633', 'S03056740', 'S03056746', 'S03057000', 'S03057230', 'S03057340', 'S03057490', 'S03057640', 'S03057650', 'S03057720', 'S03058150', 'S03058280', 'S03059000', 'S03059880', 'S03061000', 'S03061660', 'S03063000', 'S03063650', 'S03064385', 'S03065050', 'S03065250', 'S03065380', 'S03065460', 'S03065960', 'S03066000', 'S03068100', 'S03068280', 'S03068303', 'S03068310', 'S03068560', 'S03068800', 'S03068950', 'S03069000', 'S03069325', 'S03070440', 'S03071017', 'S03071080', 'S03071394', 'S03071550', 'S03071770', 'S03072200', 'S03073000', 'S03073350', 'S03074214', 'S03074800', 'S03075000', 'S03075260', 'S03075379', 'S03075400', 'S03075860', 'S03075890', 'S03076000', 'S03076002', 'S03076047', 'S03076148', 'S03076220', 'S03076443', 'S03076493', 'S03076899', 'S03077000', 'S03077596', 'S03077645', 'S03077900', 'S03077910', 'S03078060', 'S03078110', 'S03078274', 'S03078385', 'S03078510', 'S03078600', 'S03078630', 'S03078832', 'S03079270', 'S03079430', 'S03079622', 'S03079850', 'S03079967', 'S03079994', 'S03080025', 'S03080660', 'S03081000', 'S03081001', 'S03081016', 'S03081250', 'S03082000', 'S03082560', 'S03082719', 'S03082758', 'S03082781', 'S03082805', 'S03083125', 'S03083450', 'S03084470', 'S03085000', 'S03085533', 'S03085558', 'S03085575', 'S03085584', 'S03085590', 'S03085607', 'S03085608', 'S03085630', 'S03085651', 'S03085669', 'S03085670', 'S03085688', 'S03085700', 'S03085730', 'S03085763', 'S03085769', 'S03085805', 'S03085825', 'S03085837', 'S03085855', 'S03085857', 'S03085908', 'S03085920', 'S03085922', 'S03085929', 'S03085945', 'S03085960', 'S03085977', 'S03085998', 'S03086100', 'S03086340', 'S03086440', 'S03086621', 'S03087000', 'S03087545', 'S03088029', 'S03088255', 'S03088283', 'S03088302', 'S03088345', 'S03088360', 'S03088395', 'S03088410', 'S03088460', 'S03088545', 'S03088630', 'S03088800', 'S03088882', 'S03088890', 'S03088895', 'S03089215', 'S03089225', 'S03089295', 'S03090000', 'S03090010', 'S03090050', 'S03090258', 'S03090260', 'S03090380', 'S03090405', 'S03090413', 'S03090452', 'S03090470', 'S03090500', 'S03090600', 'S03090652', 'S03090689', 'S03090745', 'S03090780', 'S03090904', 'S03090923', 'S03091000', 'S03092250', 'S03092356', 'S03092500', 'S03092811', 'S03093145', 'S03093190', 'S03093300', 'S03093395', 'S03093445', 'S03093540', 'S03093572', 'S03093900', 'S03094356', 'S03094390', 'S03094405', 'S03094660', 'S03094700', 'S03095000', 'S03095190', 'S03095249', 'S03095300', 'S03095400', 'S03095620', 'S03095825', 'S03095945', 'S03096000', 'S03096010', 'S03096025', 'S03096028', 'S03096100', 'S03096125', 'S03096156', 'S03096185', 'S03096255', 'S03096310', 'S03096332', 'S03096343', 'S03096351', 'S03096400', 'S03096583', 'S03096650', 'S03096690', 'S03096706', 'S03096867', 'S03096898', 'S03097000', 'S03097020', 'S03097150', 'S03097235', 'S03097552', 'S03097571', 'S03097611', 'S03097690', 'S03097700', 'S03097790', 'S03097795', 'S03098000', 'S03098045', 'S03098190', 'S03098291', 'S03098690', 'S03098695', 'S03098745', 'S03098845', 'S03098850', 'S03099205', 'S03099330', 'S03099445', 'S03099490', 'S03099545', 'S03099750', 'S03099799', 'S03099870', 'S03099875', 'S03099950', 'S03100440', 'S03101000', 'S03101140', 'S03101340', 'S03101600', 'S03101740', 'S03102000', 'S03102920', 'S03103115', 'S03103132', 'S03103140', 'S03103150', 'S03103160', 'S03103198', 'S03103370', 'S03103440', 'S03103490', 'S03103802', 'S03103816', 'S03103970', 'S03104000', 'S03104360', 'S03104415', 'S03104450', 'S03104505', 'S03104528', 'S03104543', 'S03104810', 'S03104840', 'S03104899', 'S03105000', 'S03105125', 'S03105142', 'S03105285', 'S03105305', 'S03105355', 'S03105371', 'S03105380', 'S03105382', 'S03105455', 'S03105462', 'S03105500', 'S03105585', 'S03105710', 'S03105760', 'S03105790', 'S03105834', 'S03105865', 'S03105902', 'S03105918', 'S03105932', 'S03105946', 'S03106204', 'S03106690', 'S03107000', 'S03107295', 'S03107455', 'S03107457', 'S03107889', 'S03108050', 'S03108098', 'S03108280', 'S03108380', 'S03108647', 'S03108660', 'S03108694', 'S03108850', 'S03108890', 'S03109000', 'S03109019', 'S03109340', 'S03109590', 'S03109660', 'S03109805', 'S03109840', 'S03109935', 'S03110155', 'S03110160', 'S03110855', 'S03110863', 'S03111000', 'S03111142', 'S03111203', 'S03112000', 'S03112295', 'S03112480', 'S03112535', 'S03112539', 'S03112565', 'S03112638', 'S03112665', 'S03112710', 'S03112740', 'S03112769', 'S03112779', 'S03112805', 'S03112870', 'S03112875', 'S03112885', 'S03112965', 'S03113000', 'S03113040', 'S03113140', 'S03113179', 'S03113210', 'S03113218', 'S03113248', 'S03113265', 'S03113280', 'S03113295', 'S03113310', 'S03113340', 'S03113490', 'S03113495', 'S03113546', 'S03113610', 'S03113653', 'S03113710', 'S03113816', 'S03113895', 'S03113980', 'S03114000', 'S03114145', 'S03114290', 'S03114350', 'S03114386', 'S03114395', 'S03114630', 'S03114690', 'S03114735', 'S03114825', 'S03114900', 'S03115000', 'S03115060', 'S03115095', 'S03115125', 'S03115460', 'S03115490', 'S03115616', 'S03115630', 'S03115700', 'S03115758', 'S03115770', 'S03115789', 'S03115798', 'S03115816', 'S03115840', 'S03115860', 'S03115915', 'S03115930', 'S03115950', 'S03115955', 'S03115986', 'S03115990', 'S03116187', 'S03116192', 'S03116260', 'S03116398', 'S03116600', 'S03116680', 'S03116720', 'S03116820', 'S03117138', 'S03117302', 'S03117310', 'S03117440', 'S03117565', 'S03117800', 'S03117905', 'S03118000', 'S03118270', 'S03118300', 'S03118545', 'S03118890', 'S03118962', 'S03119000', 'S03119560', 'S03119590', 'S03119670', 'S03120000', 'S03120685', 'S03120800', 'S03120900', 'S03122008', 'S03122999', 'S03125000', 'S03125500', 'S03125925', 'S03126000', 'S03126055', 'S03126088', 'S03126511', 'S03126704', 'S03127001', 'S03127235', 'S03127370', 'S03127550', 'S03128000', 'S03128190', 'S03128220', 'S03128270', 'S03128379', 'S03128500', 'S03128640', 'S03128732', 'S03128745', 'S03128760', 'S03128774', 'S03128837', 'S03128845', 'S03128880', 'S03128907', 'S03128935', 'S03128960', 'S03128987', 'S03129020', 'S03129053', 'S03129105', 'S03129170', 'S03129175', 'S03129180', 'S03129380', 'S03129440', 'S03129730', 'S03129817', 'S03130270', 'S03130490', 'S03131000', 'S03131800', 'S03132000', 'S03132054', 'S03132095', 'S03132260', 'S03132330', 'S03132555', 'S03132615', 'S03132620', 'S03132690', 'S03132733', 'S03132736', 'S03132775', 'S03132827', 'S03132909', 'S03132976', 'S03133000', 'S03133040', 'S03133140', 'S03133155', 'S03133415', 'S03133435', 'S03133474', 'S03133595', 'S03133670', 'S03133690', 'S03133797', 'S031338

In [22]:
# create a distance matrix between group of sites
def create_distance_matrix(sites):
    site_keys = list(sites.keys())
    coords = np.array([[sites[key]['Longitude_Lambert93'].values[0], sites[key]['Latitude_Lambert93'].values[0]] for key in site_keys])
    dist_matrix = distance.cdist(coords, coords, metric='euclidean')
    return pd.DataFrame(dist_matrix, index=site_keys, columns=site_keys)

distance_matrix = create_distance_matrix(sites)
distance_matrix

               S02000008      S02000010      S02000011      S02000990  \
S02000008       0.000000   16468.227014   17393.316533    6871.416812
S02000010   16468.227014       0.000000     933.741399    9769.882087
S02000011   17393.316533     933.741399       0.000000   10703.467335
S02000990    6871.416812    9769.882087   10703.467335       0.000000
S02001000   14921.335631    1654.755571    2518.772121    8324.545153
...                  ...            ...            ...            ...
S06999134  165927.648525  179683.457697  180400.739735  172179.136140
S06999141  169873.539699  183659.927608  184378.790673  176136.003091
S06999179  171554.506656  185139.980137  185845.991471  177752.550173
S06999180  177021.029722  190756.894892  191471.942697  183269.241939
S06999189  170438.485246  184220.463793  184938.997642  176699.694182

               S02001000      S02001006      S02001016      S02001025  \
S02000008   14921.335631   10447.784550   17823.397684   21622.793575
S02000010    1654.755571    7013.555518    7095.037280   10742.557656
S02000011    2518.772121    7821.873049    7041.271547   10440.507363
S02000990    8324.545153    5189.113315   12658.144019   16827.474707
S02001000       0.000000    5364.394188    6691.545860   10681.647298
...                  ...            ...            ...            ...
S06999134  178065.968388  172741.036853  175937.976935  176540.530488
S06999141  182041.493350  176714.739498  179928.598686  180538.399240
S06999179  183529.297893  178217.636950  181278.731949  181795.836971
S06999180  189140.672583  183818.045278  186983.321537  187558.986567
S06999189  182602.218716  177275.814665  180485.484519  181092.362271

               S02001030      S02001046      S02001050      S02001100  \
S02000008   22540.063221   80420.484959   91094.070789   62891.128031
S02000010   10144.211206   63982.738688   74711.424414   46444.943514
S02000011    9686.801846   63069.469896   73807.705160   45514.235410
S02000990   17295.655784   73601.340654   84246.411734   56199.972402
S02001000   10388.226846   65576.178495   76322.751903   47970.267646
...                  ...            ...            ...            ...
S06999134  178510.972842  238090.575202  249231.113579  219225.779625
S06999141  182508.469995  242096.944320  253237.439422  223232.162389
S06999179  183771.024223  243071.587614  254199.795336  224223.943639
S06999180  189531.144865  248995.655683  260130.428149  230138.565228
S06999189  183062.616973  242640.772522  253780.816742  223776.582586

               S02001150      S02001200      S02001250      S02001500  \
S02000008   33977.148571   20217.769264   45313.918447   92324.941078
S02000010   17663.115750    3991.210969   28846.273832   75890.683763
S02000011   16730.619385    3094.877380   27923.449017   74977.886026
S02000990   27417.848530   13659.344530   38553.159793   85501.769724
S02001000   19105.231168    5336.293189   30414.303642   77485.044660
...                  ...            ...            ...            ...
S06999134  193019.922837  182048.065974  204885.483351  249330.600970
S06999141  197018.902659  186032.507460  208886.863936  253336.280223
S06999179  198255.450218  187443.804112  210078.254746  254244.409522
S06999180  204032.207666  193108.203187  215882.511828  260201.677621
S06999189  197572.288629  186591.210160  209438.778649  253877.349352

               S02001700      S02001715      S02001717      S02001725  \
S02000008  134363.873288   75940.387127   66870.949784   85362.565900
S02000010  118110.478045   59485.423055   50552.380379   68918.253388
S02000011  117222.339548   58555.930400   49618.749813   68003.382335
S02000990  127494.023154   69231.370288   60317.416274   78548.409341
S02001000  119741.093130   61019.087538   52010.559947   70507.892565
...                  ...            ...            ...            ...
S06999134  292561.525991  231184.776562  220450.103289  242514.024832
S06999141  296566.344754  235190.158954  224455.083696  246520.118337
S06999179  297432.100589  236086.254951  225336.234132  247456.422234
S06999180  303410.627126  242048.647352  231305.282294  253399.761636
S06999189  297105.755205  235730.596852  224994.790949  247062.360828

               S02001738      S02001750      S02001895      S02001915  \
S02000008   97701.429601    8744.533207   18263.979906   20975.636176
S02000010   81285.310020   20714.863311   18084.724079   23285.252200
S02000011   80375.858677   21513.168177   18400.187662   23637.669280
S02000990   90866.749700   13301.301064   17458.627810   21579.119398
S02001000   82886.570571   19064.780775   16930.520163   22065.283366
...                  ...            ...            ...            ...
S06999134  254849.286570  159196.038167  164577.890803  159713.005206
S06999141  258854.793396  163163.231878  168575.811337  163713.915526
S06999179  259753.388929  164716.051401  169835.392695  164924.506636
S06999180  265715.402704  170279.680129  175596.484139  170714.843657
S06999189  259395.477033  163725.431678  169129.745004  164266.141520

               S02001955      S02001990      S02002000      S02002800  \
S02000008   23499.632614   27558.495623   24949.213695   25016.482666
S02000010   24047.495088   26663.612696   23290.448793   21651.901025
S02000011   24290.594579   26788.046905   23413.064131   21691.392878
S02000990   23477.596640   27129.955584   24051.047233   23396.009446
S02001000   22977.753850   25763.884994   22402.533272   20900.679845
...                  ...            ...            ...            ...
S06999134  160871.869169  161364.632816  163634.298095  166254.278237
S06999141  164875.791373  165370.829607  167639.444481  170259.407860
S06999179  166017.697566  166411.185985  168739.899212  171359.801648
S06999180  171848.028691  172297.274166  174593.646585  177213.768046
S06999189  165425.571288  165916.713595  168187.700041  170807.688568

               S02003100      S02003200      S02003350      S02003397  \
S02000008   21764.505278   24561.509115   25243.596931   26565.113758
S02000010   18935.120940   19293.207846   29022.915515   28940.138113
S02000011   19062.878114   19244.110632   29383.390853   29226.620828
S02000990   20131.790705   22122.342665   26768.925287   27521.403053
S02001000   18055.843182   18698.408729   27782.700031   27799.652696
...                  ...            ...            ...            ...
S06999134  166491.133172  169209.015555  154723.987943  156243.040536
S06999141  170493.543068  173213.558234  158728.010899  160248.454323
S06999179  171671.607670  174334.289731  159868.872893  161339.731849
S06999180  177481.546720  180177.146770  165699.328767  167197.974345
S06999189  171044.690759  173762.636551  159277.684517  160796.275734

               S02003400      S02003610      S02003617      S02003620  \
S02000008   27531.175420   33213.962425   34522.620121   31580.295201
S02000010   29476.798554   31041.117264   31441.039184   28525.110342
S02000011   29734.562381   31044.917136   31385.459054   28496.796750
S02000990   28339.839678   32466.062111   33435.207148   30405.356962
S02001000   28375.572470   30321.818498   30818.178872   27863.428791
...                  ...            ...            ...            ...
S06999134  156433.732925  161826.687740  163372.522197  164005.894266
S06999141  160439.647750  165831.809886  167376.723501  168011.820492
S06999179  161504.079410  166732.070202  168244.489532  168951.722018
S06999180  167376.929593  172688.755696  174216.629677  174889.337414
S06999189  160986.427717  166371.803960  167915.286692  168553.569170

               S02003670      S02003700      S02003800      S02003900  \
S02000008   31244.638340   27337.916837   27566.955019   26880.614018
S02000010   26871.004187   22657.236592   22554.567520   20754.872609
S02000011   26774.536877   22592.297116   22468.309527   20617.288134
S02000990   29509.026992   25302.612711   25407.187959   24232.885940
S02001000   26327.318170   22073.954652   22007.687112   20303.843109
...                  ...            ...            ...            ...
S06999134  166586.952910  167809.015491  168316.460520  170206.443183
S06999141  170593.050928  171815.096383  172322.583387  174212.193431
S06999179  171544.970806  172864.161887  173367.968475  175282.584303
S06999180  177476.828654  178746.087725  179251.888473  181153.222003
S06999189  171135.344503  172361.398399  172868.744671  174759.358551

               S02004000      S02004300      S02004800      S02005000  \
S02000008   28012.194559   56535.134315   41943.770098   37843.390876
S02000010   17777.250097   49926.227987   34464.002626   29952.583995
S02000011   17362.442455   49564.786371   34104.477389   29592.181349
S02000990   23816.003548   54371.255246   39222.407639   34870.570113
S02001000   17852.764968   49823.455571   34376.286609   29875.659658
...                  ...            ...            ...            ...
S06999134  176790.886521  172169.113121  173054.897547  173634.498398
S06999141  180796.028966  176126.770328  177052.109143  177637.322511
S06999179  181893.183869  176487.353910  177775.975171  178464.965371
S06999180  187749.629070  182650.786037  183812.137146  184456.238195
S06999189  181344.288769  176638.888767  177584.006794  178174.180150

               S02005688      S02005700      S02006450      S02006500  \
S02000008   34967.538375   33764.185537   34459.600883   30870.523173
S02000010   25961.228342   24136.455954   26958.977911   20169.134885
S02000011   25551.403875   23695.984997   26648.736649   19683.518410
S02000990   31476.198325   29994.332031   31557.694371   26598.103128
S02001000   25990.446033   24231.998721   26795.193636   20371.579467
...                  ...            ...            ...            ...
S06999134  175700.938418  176768.023862  172538.074697  178202.096912
S06999141  179706.468804  180774.174718  176543.317973  182208.236875
S06999179  180620.759300  181727.994071  177445.434838  183249.534791
S06999180  186571.675642  187659.594556  183401.997004  189136.270252
S06999189  180247.242423  181316.660950  177083.523079  182754.334586

               S02007000      S02007250      S02007300      S02007380  \
S02000008   36728.489119   35516.599218   36350.497383   65771.944475
S02000010   22303.522099   21622.801599   21574.905446   54857.018302
S02000011   21498.188784   20862.489401   20744.293480   54219.975101
S02000990   31094.918074   30090.295196   30563.945377   61853.604430
S02001000   23232.967482   22434.005639   22578.562687   55324.968007
...                  ...            ...            ...            ...
S06999134  188586.588961  186570.834712  189318.080555  191022.397904
S06999141  192592.667319  190576.953659  193323.762580  194974.118924
S06999179  193636.834846  191618.157245  194393.320076  195290.845382
S06999180  199522.654025  197505.437211  200265.564828  201467.500635
S06999189  193138.971898  191123.123407  193871.069366  195483.874222

               S02008000      S02009000      S02009500      S02010000  \
S02000008   58143.910584   49917.564895   41241.055758   40142.893630
S02000010   48314.328982   40086.835769   30256.428358   27412.408760
S02000011   47755.868016   39549.003186   29676.585046   26717.726045
S02000990   54641.639516   46340.213918   37078.098401   35250.890854
S02001000   48612.035927   40348.698442   30623.897286   28046.683405
...                  ...            ...            ...            ...
S06999134  183833.058031  181221.275407  181785.724140  185872.549119
S06999141  187799.972567  185208.537862  185788.387823  189877.929399
S06999179  188221.655130  185807.008245  186610.038020  190782.624243
S06999180  194367.542687  191892.840974  192604.526977  196738.782717
S06999189  188315.843096  185734.143102  186325.060260  190418.387689

               S02011000      S02013000      S02015000      S02016050  \
S02000008   42341.068444   52080.807031   58230.235943   52009.038638
S02000010   27739.936734   36253.362244   42666.401922   38793.787196
S02000011   26908.103259   35338.142976   41762.593334   38036.030182
S02000990   36673.988193   45843.920797   52146.912133   47012.451298
S02001000   28735.758525   37552.711886   43906.968297   39569.299122
...                  ...            ...            ...            ...
S06999134  192441.334791  204367.463682  207498.189701  193234.579527
S06999141  196447.562298  208373.403276  211500.748188  197230.862134
S06999179  197405.540847  209304.439095  212314.165896  197935.783551
S06999180  203335.986724  215248.811660  218313.710321  203980.923657
S06999189  196990.373496  208915.166654  212037.283601  197762.055099

               S02017000      S02017500      S02017850      S02018000  \
S02000008   48255.637349   52257.071110   46330.493468   58318.920369
S02000010   33858.326258   37749.284761   31700.380881   42886.556518
S02000011   33030.584191   36909.844933   30860.236243   41989.565192
S02000990   42712.697936   46680.737098   40672.142407   52305.509022
S02001000   34834.402033   38757.816708   32716.666395   44097.100154
...                  ...            ...            ...            ...
S06999134  195363.086147  198300.047327  195018.197125  206821.684985
S06999141  199366.825249  202301.412474  199023.381865  210823.381201
S06999179  200212.742517  203090.830529  199917.559501  211617.871941
S06999180  206196.986447  209100.533928  205879.248456  217625.767695
S06999189  199904.747480  202836.744255  199563.463039  211359.027595

               S02018500      S02018690      S02018780      S02019000  \
S02000008   72080.443013   63906.682538   69555.904250   65974.689094
S02000010   55895.643122   51226.667840   56437.060315   51069.996299
S02000011   54964.311012   50485.926920   55665.061394   50198.356318
S02000990   65631.564144   59205.917694   64678.163896   60243.953473
S02001000   57307.754310   51948.605852   57239.090672   52179.008902
...                  ...            ...            ...            ...
S06999134  223300.481580  197543.169166  202747.947790  209445.681512
S06999141  227301.728117  201515.438885  206711.919448  213435.902568
S06999179  228083.904985  201974.408787  207107.464747  214060.050923
S06999180  234097.902598  208109.255222  213262.176909  220137.716180
S06999189  227836.925629  202033.611070  207226.505334  213963.155824

               S02019200      S02019500      S02019950      S02020000  \
S02000008   67055.265065   66245.070224   71186.962606   70933.152813
S02000010   51638.970439   50742.275274   55860.390690   55289.849276
S02000011   50740.117077   49839.331827   54964.992723   54379.303158
S02000990   61062.698597   60205.013479   65247.030798   64820.083038
S02001000   52854.506601   51976.232761   57059.988153   56558.944164
...                  ...            ...            ...            ...
S06999134  213237.706576  213174.391844  215779.546394  217744.849007
S06999141  217232.367213  217170.741126  219768.821594  221738.817878
S06999179  217910.504862  217872.368925  220381.042427  222406.959176
S06999180  223967.386708  223919.808934  226463.469118  228467.989714
S06999189  217762.411715  217701.958328  220295.511856  222268.396802

               S02020300      S02020750      S02021000      S02021700  \
S02000008   72513.630002   75596.072047   76237.152944   74638.835629
S02000010   56670.725573   59538.999017   60107.629083   58449.007733
S02000011   55751.260183   58611.283086   59177.652750   57517.480230
S02000990   66286.040197   69235.924606   69828.279844   68186.883291
S02001000   57988.375085   60914.099681   61503.802240   59863.324640
...                  ...            ...            ...            ...
S06999134  220518.115512  224934.672352  226207.947243  225516.960633
S06999141  224513.701787  228931.652362  230205.909422  229516.996813
S06999179  225203.116022  229640.388070  230929.496282  230275.695691
S06999180  231255.798327  235685.421537  236968.473694  236299.894177
S06999189  225044.372125  229463.316327  230738.312575  230051.094205

               S02022000      S02022465      S02022650      S02022670  \
S02000008   75782.545649   82672.049956   73124.429625   79903.762565
S02000010   59549.185469   66391.848302   56851.883812   63599.633529
S02000011   58616.673950   65458.502030   55918.728491   62666.053362
S02000990   69298.469262   76151.908216   66609.484497   73363.532937
S02001000   60977.950392   67837.905901   58293.752950   65054.123843
...                  ...            ...            ...            ...
S06999134  226998.684366  233552.860177  225212.859138  231496.244646
S06999141  230998.975203  237550.645148  229215.111129  235496.129246
S06999179  231762.089119  238270.230658  230018.297607  236251.100759
S06999180  237784.459419  244311.138952  236023.153449  242277.116484
S06999189  231533.294560  238082.905831  229751.308029  236030.090948

               S02022675      S02022700      S02022730      S02022760  \
S02000008   79929.654835   84154.087536   54079.074705   64634.319684
S02000010   63628.806692   67756.648117   37771.754579   48298.035157
S02000011   62695.255147   66823.541997   36838.376579   47364.314552
S02000990   73392.195341   77525.223869   47533.174773   58065.222948
S02001000   65082.067615   69251.692976   39222.412215   49763.102154
...                  ...            ...            ...            ...
S06999134  231470.462463  236887.272233  209479.748716  218768.311439
S06999141  235470.248176  240888.204927  213486.102763  222773.939564
S06999179  236223.457133  241661.939107  214491.974034  223683.978830
S06999180  242250.220578  247680.113503  220398.920508  229639.194584
S06999189  236004.125102  241423.098025  214031.031928  223314.903130

               S02022800      S02023000      S02023500      S02023750  \
S02000008   83481.096285   91261.099456   84910.524418   86816.405736
S02000010   67064.770036   75214.248816   69906.205061   71138.983125
S02000011   66132.279871   74286.230770   69023.818012   70225.012674
S02000990   76830.212026   84911.997698   79154.251193   80694.073958
S02001000   68570.057518   76590.342975   71050.390921   72423.269631
...                  ...            ...            ...            ...
S06999134  236732.108735  238007.399954  223965.954573  230679.385975
S06999141  240734.043153  241991.446659  227929.979733  234657.163890
S06999179  241528.385199  242545.354019  228321.422046  235154.826855
S06999180  247537.577343  248649.824488  234478.176692  241278.358170
S06999189  241269.905832  242515.230831  228444.542264  235177.823529

               S02024000      S02024300      S02025100      S02025125  \
S02000008   86819.129793   86662.776519   86834.387393   84826.334885
S02000010   70820.668967   70474.333122   70422.985204   68395.155450
S02000011   69894.376498   69542.583861   69490.321930   67463.432124
S02000990   80500.768350   80213.925107   80189.359226   78155.928918
S02001000   72182.865647   71890.503858   71925.598899   69909.680796
...                  ...            ...            ...            ...
S06999134  233723.976564  235767.403644  239608.250803  238343.796699
S06999141  237710.604265  239759.869219  243608.700616  242345.918257
S06999179  238291.177394  240405.838007  244372.769097  243144.107303
S06999180  244385.954003  246476.207878  250395.197354  249151.664369
S06999189  238235.778423  240288.461656  244143.152116  242881.971173

               S02025150      S02025200      S02025500      S02025700  \
S02000008   88268.334028   87537.211613   94688.017156   94166.243978
S02000010   71875.178476   71096.705803   78223.462529   77698.562406
S02000011   70941.988610   70165.669419   77296.159445   76772.927553
S02000990   81644.092236   80852.884005   87951.954350   87414.118608
S02001000   73368.263745   72617.846181   79769.645869   79252.938267
...                  ...            ...            ...            ...
S06999134  240459.181594  241087.150869  248845.224226  248797.577950

In [24]:
# get nearest sites for a given site
def find_closest_sites(site, df, n=3):
    site_key = site['CodeSite_SamplingOperations_x'].values[0] # this is the site key
    distances = distance_matrix[site_key].sort_values()
    closest_sites_keys = distances.index[1:n+1]  # exclude self
    close = pd.DataFrame()
    for close_key in closest_sites_keys:
        close_site = df[df['CodeSite_SamplingOperations_x'] == close_key]
        close = pd.concat([close, close_site])
        # sort close by Date_SamplingOperation
        close = close.sort_values(by='Date_SamplingOperation')
    return close

In [28]:
site = sites['S02001016']
site

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02001016_20080811,S02001016,2008-08-11,NaN,NaN,NaN,1032286.0,6737746.0,Rhin-Meuse,ALSACE,TP
S02001016_20150718,S02001016,2015-07-18,15.1,0.824561,Good,1032286.0,6737746.0,Rhin-Meuse,ALSACE,TP
S02001016_20170703,S02001016,2017-07-03,14.8,0.807018,Good,1032286.0,6737746.0,Rhin-Meuse,ALSACE,TP
S02001016_20200707,S02001016,2020-07-07,14.8,0.807018,NaN,1032286.0,6737746.0,Rhin-Meuse,ALSACE,TP

In [29]:
# create a dictionary of dataframes per site and later access them by 1, 2, ...
sites = {}
for site, group in df_filled.groupby('CodeSite_SamplingOperations_x'):
    sites[site] = group

In [30]:
site = sites['S02001016']
site

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02001016_20080811,S02001016,2008-08-11,NaN,NaN,NaN,1032286.0,6737746.0,Rhin-Meuse,ALSACE,TP
S02001016_20150718,S02001016,2015-07-18,15.1,0.824561,Good,1032286.0,6737746.0,Rhin-Meuse,ALSACE,TP
S02001016_20170703,S02001016,2017-07-03,14.8,0.807018,Good,1032286.0,6737746.0,Rhin-Meuse,ALSACE,TP
S02001016_20200707,S02001016,2020-07-07,14.8,0.807018,Good,1032286.0,6737746.0,Rhin-Meuse,ALSACE,TP

In [26]:
closest = find_closest_sites(site, df_filled, n=3)
closest

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02001025_20070905,S02001025,2007-09-05,13.10,0.707602,Moderate,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20070906,S02001000,2007-09-06,14.40,0.783626,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001025_20080811,S02001025,2008-08-11,14.70,0.801170,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20080811,S02001000,2008-08-11,14.70,0.801170,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001025_20090721,S02001025,2009-07-21,13.50,0.730994,Moderate,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20090721,S02001000,2009-07-21,14.90,0.812865,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001000_20100719,S02001000,2010-07-19,15.20,0.830409,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001025_20100719,S02001025,2010-07-19,14.30,0.777778,Moderate,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20110723,S02001000,2011-07-23,15.70,0.859649,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001025_20110723,S02001025,2011-07-23,15.05,0.821637,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001025_20120801,S02001025,2012-08-01,15.80,0.865497,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20120801,S02001000,2012-08-01,15.10,0.824561,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001000_20130819,S02001000,2013-08-19,11.70,0.625731,Moderate,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001025_20130819,S02001025,2013-08-19,14.60,0.795322,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001025_20140930,S02001025,2014-09-30,15.60,0.853801,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20140930,S02001000,2014-09-30,15.50,0.847953,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001025_20150718,S02001025,2015-07-18,15.70,0.859649,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001030_20150718,S02001030,2015-07-18,15.40,0.842105,Good,1030170.0,6741973.0,Rhin-Meuse,ALSACE,TP
S02001000_20150718,S02001000,2015-07-18,15.80,0.865497,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001000_20160720,S02001000,2016-07-20,15.15,0.827485,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001025_20160720,S02001025,2016-07-20,15.70,0.859649,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20170703,S02001000,2017-07-03,14.50,0.789474,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001025_20170703,S02001025,2017-07-03,15.70,0.859649,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001025_20180716,S02001025,2018-07-16,15.80,0.865497,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20180716,S02001000,2018-07-16,14.50,0.789474,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001030_20180716,S02001030,2018-07-16,15.60,0.853801,Good,1030170.0,6741973.0,Rhin-Meuse,ALSACE,TP
S02001025_20190717,S02001025,2019-07-17,15.85,0.868421,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20190718,S02001000,2019-07-18,14.40,0.783626,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001025_20200707,S02001025,2020-07-07,15.90,0.871345,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20200707,S02001000,2020-07-07,15.20,0.830409,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP
S02001025_20210806,S02001025,2021-08-06,15.30,0.836257,Good,1028974.0,6740387.0,Rhin-Meuse,ALSACE,TP
S02001000_20210825,S02001000,2021-08-25,14.50,0.789474,Good,1038791.0,6736177.0,Rhin-Meuse,ALSACE,TP

In [31]:
site = sites['S02001046']
site

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02001046_20100726,S02001046,2010-07-26,NaN,NaN,NaN,1045006.0,6801458.0,Rhin-Meuse,ALSACE,TP

In [32]:
closest = find_closest_sites(site, df_filled, n=3)
closest

,CodeSite_SamplingOperations_x,Date_SamplingOperation,IBD,IBD_EQR,IBD_EQR_Status,Longitude_Lambert93,Latitude_Lambert93,Watershed,HERlvl1Name,Streamsize
SamplingOperations_code,,,,,,,,,,
S02001725_20070907,S02001725,2007-09-07,13.8,0.748538,Moderate,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02001715_20070907,S02001715,2007-09-07,14.3,0.777778,Moderate,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001715_20080806,S02001715,2008-08-06,16.0,0.877193,Good,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001725_20080912,S02001725,2008-09-12,14.5,0.789474,Good,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02001715_20090723,S02001715,2009-07-23,17.1,0.941520,High,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001725_20090804,S02001725,2009-08-04,14.7,0.801170,Good,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02001715_20100722,S02001715,2010-07-22,16.5,0.906433,Good,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001725_20100726,S02001725,2010-07-26,14.6,0.795322,Good,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02001725_20110721,S02001725,2011-07-21,14.6,0.795322,Good,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02001715_20110722,S02001715,2011-07-22,18.7,1.000000,High,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001715_20120731,S02001715,2012-07-31,16.6,0.912281,Good,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001725_20120731,S02001725,2012-07-31,15.6,0.853801,Good,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02001715_20130820,S02001715,2013-08-20,15.8,0.865497,Good,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001715_20141008,S02001715,2014-10-08,15.8,0.865497,Good,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001715_20150812,S02001715,2015-08-12,17.8,0.982456,High,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001715_20160825,S02001715,2016-08-25,17.6,0.970760,High,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001725_20160829,S02001725,2016-08-29,16.4,0.900585,Good,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02001715_20170705,S02001715,2017-07-05,17.4,0.959064,High,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001725_20170706,S02001725,2017-07-06,17.2,0.947368,High,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02001715_20180726,S02001715,2018-07-26,16.2,0.888889,Good,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001725_20180726,S02001725,2018-07-26,16.7,0.918129,Good,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02025125_20180726,S02025125,2018-07-26,NaN,NaN,NaN,1035626.0,6806015.0,Rhin-Meuse,ALSACE,TP
S02001725_20190718,S02001725,2019-07-18,17.0,0.935673,Good,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02001715_20190719,S02001715,2019-07-19,17.2,0.947368,High,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001725_20200630,S02001725,2020-06-30,16.4,0.900585,Good,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP
S02001715_20200703,S02001715,2020-07-03,17.3,0.953216,High,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02025125_20210804,S02025125,2021-08-04,16.3,0.894737,Good,1035626.0,6806015.0,Rhin-Meuse,ALSACE,TP
S02001715_20210805,S02001715,2021-08-05,17.4,0.959064,High,1037861.0,6797189.0,Rhin-Meuse,ALSACE,None
S02001725_20210908,S02001725,2021-09-08,15.5,0.847953,Good,1044874.0,6806422.0,Rhin-Meuse,ALSACE,TP